### ISSUE TITLE
Error - rfc.Client is not a function

### ISSUE THREAD

**Issue by donaldhook** [SAP/node-rfc#10]
I am receiving the following error trying to create the client.  Not sure what I have defined incorrectly.

Thanks for your help

Code 
=============
....
// Define the SAP Configuration
var SAPconfig = {
	user: 'xxx',
	passwd: 'xxx',
	ashost: 'xxx',
	sysnr: '010',
	client: '11'
};

var rfc = require('node-rfc');
var client = new rfc.Client(SAPconfig, true);
console.log('** RFC Client Lib Version: ' + client.getVersion());

Console Log
==============
var client = new rfc.Client(SAPconfig, true);
             ^

TypeError: rfc.Client is not a function
    at Object.<anonymous> (c:\Boelter Applications\BoelterIntegrationServer\server.js:57:14)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.runMain [as _onTimeout] (module.js:431:10)
    at Timer.listOnTimeout (timers.js:93:15)

**Comment by bsrdjan** [comment]
The code looks correct. Which nodejs version are you using and on which platform (Linux/Windows) ?

**Comment by heri16** [comment]
rfc.Client. Missed a dot there

**Comment by donaldhook** [comment]
I am using node 5.2 on Windows 10

**Comment by donaldhook** [comment]
I have a dot there in the statement ...rfc.Client

**Comment by bsrdjan** [comment]
node 5.2 was not supported and I just pushed the fix, in the master branch, tested on Linux only. 

To test on Windows the node-rfc binary must be built from source, following the "Build from source" section of the documentation. Did you build the binary from source, from the current master ?

**Comment by donaldhook** [comment]
I did not... I will try it out and let you know the results.  Thanks for
your time and help!

**Comment by donaldhook** [comment]
Ok, need a bot more clarity on how to compile from source to create the .node file for Wndows. Where do i download the source to?  Where do I execute node-gyp build from?    

Thanks and sorry for the inconvenience

**Comment by bsrdjan** [comment]
No inconveniences at all, no worries. The build from source is described [here](http://sap.github.io/node-rfc/install.html#building-from-source). Basically, you need to clone this repository and cd to root folder, default node-rfc. Then check the prerequisites and follow the steps in the documentation:

```shell
git clone https://github.com/SAP/node-rfc.git
cd node-rfc
node-gyp configure --msvs_version=2013
node-gyp build
```

Visual Studio 2015 worked with nodejs 4.2.0 and I suppose it should work with nodejs 5.2.0 as well, but did not test that combination.

Before you start building, the path to  Visual Studio shall be configured in [binding.gyp](https://github.com/SAP/node-rfc/blob/master/binding.gyp#L4). 

You also need SAP NW RFC Library installed, as described in the documentation.

SAP NW RFC Library is available as 32 bit and 64 bit and Windows platforms today are usually 64 bit. If you use 64 bit platform and 64 bit RFC lib, the nodejs shall run in 64 bit mode as well. That is unfortunately not always the default and If you use node version manager `nvm` for example, you may use the command `nvm arch`, to check the current setting. More details in "Usage" section of  https://github.com/coreybutler/nvm-windows

Hope this helps, to start at least.

**Comment by donaldhook** [comment]
Thank you for all your help!! I am getting a connection refused so now I can start to address that.

Thanks!!

LOCATION    CPIC (TCP/IP) on local host PWKSRV29 with Unicode
ERROR       partner '10.2.20.40:3300' not reached
TIME        Thu Dec 17 18:50:42 2015
RELEASE     721
COMPONENT   NI (network interface)
VERSION     40
RC          -10
MODULE      nixxi.cpp
LINE        3283
DETAIL      NiPConnect2: 10.2.20.40:3300
SYSTEM CALL connect
ERRNO       10061
ERRNO TEXT  WSAECONNREFUSED: Connection refused
COUNTER     2
] code: 1, key: 'RFC_COMMUNICATION_FAILURE' }

**Comment by bsrdjan** [comment]
'partner not reached' looks like network issue. In your connection parameters the client is set to '11', should be three digits, you can also send me the connection params to check. SAP network utility `niping` to check the network connectivity to ABAP server, independent of the node-rfc: `niping -CH <server ip and port>`. More details on this in [OSS note 500235](http://service.sap.com/sap/support/notes/500235), [scn](http://wiki.scn.sap.com/wiki/display/ABAP/NIPING).

**Comment by donaldhook** [comment]
WIll do... thank you for all your great help!!

**Comment by bsrdjan** [comment]
Windows 64 bit builds published in branches 4.2.3 and 5.3.0

**Comment by GeorgeMacintoshJr** [comment]
Hello  @donaldhook I've followed the instruction of @bsrdjan  but still i'm getting error. 
![image](https://user-images.githubusercontent.com/30595910/31063037-1bb6a77a-a762-11e7-806e-8401baccedf5.png)

Were you able to connect to SAP system using node-rfc? I'm new to SAP and I'm having a really hard time on setting up. 

Thanks for your help.

**Comment by donaldhook** [comment]
George 

There are 2 dll's that you need to install in the c:\windows\system32 directory ... sapjco3.dll and sapnwrfc.dll

This was a pain to setup, so you are not alone.  I ended up going to Spring Boot to implement my project....

**Comment by bsrdjan** [comment]
@GeorgeMacintoshJr,
the error message is telling the compiler is not finding `sapnwrfc.h` header file. The location where the compiler is looking for this file is defined in [binding.gyp](https://github.com/SAP/node-rfc/blob/master/binding.gyp#L4). To find the file, the env variable SAPNWRFC_HOME shall point to the root folder path of SAPNWRFC library. Further details on SAPNWRFC  lib installation are documented [here](http://sap.github.io/node-rfc/install.html#sap-nw-rfc-library-installation).
Could you please check if this helps?

**Comment by donaldhook** [comment]
I seem to recall there was an option as to which VStools version to use... vs2015 vs2013 ... did you see that anywhere?

**Comment by GeorgeMacintoshJr** [comment]
Hello @donaldhook 
Your project aim is to make a connection from a non-SAP system to a SAP system and retrieve data? 
Were you able to make the connection using the SAP or do you recommend using other method?

Thank you. I'm so glad to hear from you since you were so involved on this.

**Comment by GeorgeMacintoshJr** [comment]
Hello @bsrdjan 
I already set my env variable
![image](https://user-images.githubusercontent.com/30595910/31330284-50d02e50-ad10-11e7-8c78-0636e39265ec.png)

After that when executing node-gyp configure --msvs_version=2015 I was getting this error
![image](https://user-images.githubusercontent.com/30595910/31329628-9c23135c-ad0d-11e7-979e-30724e44d475.png)
what I did to get rid of the error 
Under binding.gyp
1.  Change the <(module_name) to "rfc"
2.  Change the <(module_path) to "."
![image](https://user-images.githubusercontent.com/30595910/31329709-fba3ec2a-ad0d-11e7-9664-f084a853b8dd.png)

Next I execute node-gyp build,the output is 1 warning and 1 error
![image](https://user-images.githubusercontent.com/30595910/31330037-423f4732-ad0f-11e7-8dbb-679d9eb50902.png)
now to overcome the error what I did was 
Under rfc.vcxproj
1. Change sapnwrfc.lib to C:\nwrfcsdk\lib\sapnwrfc.lib 
2. Change libsapucom.lib to C:\nwrfcsdk\lib\libsapucum.lib
because it seems like it cannot find the C:\nwrfcsdk\lib

So after that I was getting this output 
![image](https://user-images.githubusercontent.com/30595910/31330363-ac6e58e0-ad10-11e7-87a8-97b1157b38f3.png)

Now I don't know how to proceed. I'm afraid the warning: MSB8012 can cause incorrect behavior. 
Also how do test the node-rfc ? 

Do I execute the mocha demo inside the node-rfc/demo folder? 
![image](https://user-images.githubusercontent.com/30595910/31330485-4da22b06-ad11-11e7-8f07-61852ed72ba9.png)

Thanks and sorry for the inconvenience. I'd really appreciate any help.

**Comment by bsrdjan** [comment]
just a small hint, the env variable SAPNWRFC_HOME should point to the root folder of SAPNWRFC lib, thus without `\lib` suffix. Starting from that folder, both includes and libraries can be referenced in `binding.gyp`.

mocha tests are executed against one SAP internal test system and some RFMs (Remote Function Modules) used in these tests may not exist in your test system. I would recommend starting from the simple test, like in [README Getting Started](https://github.com/SAP/node-rfc), just adapt connection parameters. Mocha tests can be used as examples to build own tests, in similar manner.

Regarding question which connection method to use from non-SAP to SAP system, it depends on system release and mostly on use-case and application. With SAP systems with HANA, the [node-hdb](https://github.com/SAP/node-hdb) can be used for the integration at table level. In landscapes with SAP NW GATEWAY and ODATA services, that method can be used as well. RFM (node-rfc) integration works with any system, new or old and still the fastest way for executing SAP business logic from nodejs. There are also other methods, like WS-SOAP or IDocs and it depends on use-case which one to use.

**Comment by GeorgeMacintoshJr** [comment]
Thanks @bsrdjan I removed the \lib suffix, after that I don't have to specify the path under rfc.vcxproj.

![image](https://user-images.githubusercontent.com/30595910/31332444-fb3e51a2-ad18-11e7-95e1-6fbc3c9f29cf.png)
To perform a connection I have to perform 3 things
1. Create a client with valid logon credentials
2. Connect to NetWeaver system
3.  Invoke a remote enabled ABAP function module from node

1. I already create a client on SAP. 
2. Connect to NetWeaver System meaning install the NWRFC SDK? 
3. To call the function which is remote enabled on Application Server? 

Do I have to create another folder and create a js file then paste this code 
![image](https://user-images.githubusercontent.com/30595910/31332690-f45340fe-ad19-11e7-9ff6-b4e1a51cea4c.png)

Or I can just use the demo.js? Sorry, I'm really confuse on how to perform a connection on SAP.

**Comment by bsrdjan** [comment]
Now I see, the naming and comments in this source could be better, will enhance.

Once compiled, It is enough to copy and run the `demo.js`, like `node demo`. If the `node-rfc` module not found, it shall be referenced either by node-pre-gyp or direct, like in dev branch [test.js]( https://github.com/SAP/node-rfc/blob/dev/test/test.js#L20).

**Comment by GeorgeMacintoshJr** [comment]
Oh thanks @bsrdjan, I just need to clarify it.  So after executing the node-gyp build I just change directory to the demo folder

C:\Users\Owner\Desktop\Sample\node-rfc> cd demo

and run node demo. But before that I have to add these line of code on demo.js 

var should = require("should");
var binary = require('node-pre-gyp');
var path = require('path');
var rfc_path = binary.find(path.resolve(path.join(__dirname,'../package.json')));
var rfc = require(rfc_path);

otherwise I will node-rfc module not found.

Thank you @bsrdjan, I just need to clarify things for the benefits also of other developers. Because I can see that this module has great potentials.
