### ISSUE TITLE
Segmentation Fault if wrong parameters are passed to RFC

### ISSUE THREAD

**Issue by PaulWieland** [SAP/node-rfc#100]
I just found that if you call an RFC and pass an invalid data type in the structure, you can cause nodeJS to seg fault.

To reproduce it, call `RFC_READ_TABLE` and pass this stucture:

```
    {
        QUERY_TABLE: "MARA",
        OPTIONS: "A string instead of an array"
    }
```

The RFC expects options to be an array, and it throws an error, but then crashes. 

<img width="325" alt="image" src="https://user-images.githubusercontent.com/4663918/63605819-b2fce900-c59c-11e9-84ec-21791f8490cd.png">

**Comment by bsrdjan** [comment]
Thanks for catching this one. The fix will be shipped with next release.

**Comment by bsrdjan** [comment]
Fixed in rc11
