### ISSUE TITLE
Sequential calls to Invoke()

### ISSUE THREAD

**Issue by StephanusRex** [SAP/node-rfc#101]
How does one call Invoke sequentially? In my experience the the second call immediately results in an error and the only way to resolve it is to make the call in callback of first Invoke() call. This works if there's a finite # of calls but if the same RFC needs to be called multiple times, say, in a loop, then this is impossible.

**Comment by bsrdjan** [comment]
Async or similar library might help: [example](https://github.com/SAP/node-rfc/blob/napi/examples/README.md#asyncawait-node-release--760-or-transpiler-required)

**Comment by PaulWieland** [comment]
Use the [async library's queue](https://caolan.github.io/async/v3/docs.html#queue) method. I implemented this for the Node-RED plugin and it works very well.
