### ISSUE TITLE
Working with callbacks using RFC DESTINATION "BACK"

### ISSUE THREAD

**Issue by michaelwiederhold** [SAP/node-rfc#102]
Hi,

some RFCs that we work with do not use importing/exporting tables to return results. Rather, they send the results back to the caller using RFC DESTINATION "BACK". Does node-rfc support getting data that is returned in this way?

Thank you for your help!
Michael

**Comment by bsrdjan** [comment]
Hi Michael,

it would be doable with RFC Server functionality added to node-rfc, similar to already existing Client. There is a working [Python example](https://github.com/SAP/PyRFC/blob/master/material/serverExamples.py) and [documentation](https://sap.github.io/PyRFC/server.html) but I have no capacity atm to add and maintain the Server, in any of RFC connectors.

Kind regards,
Srdjan

**Comment by michaelwiederhold** [comment]
Thanks for the info! I will have a deeper look at the links you provided to see if this is something we would want to pursue
