### ISSUE TITLE
Why no automated testing? Travis CI, CircleCI, AppVeyor, Azure Pipelines, etc?

### ISSUE THREAD

**Issue by cclauss** [SAP/node-rfc#106]
There are [a lot of great tools](https://github.com/marketplace/category/continuous-integration) that would run free tests on every pull request.

**Comment by bsrdjan** [comment]
The project is hosted on external github and npm and the test infrastructure I have to use is inside our corporate firewall. The native library, wrapped by my node add-on, required for testing, is not public available and must not be deployed on external test systems, only internally. Also the testing is running against internally available ABAP systems. We made it work with internal travis but setup was too complicated and after approx. 1 year we had no more fun using it. Need to check if policies eventually changed in the meantime.
