### ISSUE TITLE
xml output

### ISSUE THREAD

**Issue by alogane** [SAP/node-rfc#107]
hi all, more than a issue I would like to know if it is possible to make a console.log () to the final scheme that is being sent to Sap, since we are having problems with sending dates and they are asking me to see that final XML scheme.

**Comment by bsrdjan** [comment]
Could it be your question is posted to wrong repository, see no relation to node-rfc?

**Comment by alogane** [comment]
sorry it was my mistake due to ignorance, I better tell you what my problem is and maybe you can guide me, I am using this connector for communication with SAP with this RFC 'Z_BAPI_PART_VISTA'. Where should I send a date, the problem is that when I send the date in the following format 'YYYYMMDD' SAP returns the message "invalid date" but when I send it 'YYYY-MM-DD' allows the insertion of the date but it is in a bad Format.
According to the information of a log found there is a webservice called 'ZWS_BAPI_PART_VISTA' that was created from the aforementioned RFC, and that also validates the date.
  Is it possible that WS inflicts on the validation of the date if I am declaring the communication to RFC 'Z_BAPI_PART_VISTA?

**Comment by bsrdjan** [comment]
You may test Z_BAPI_PART_VISTA in ABAP system, using the transaction SE37, trying various date values/formats. What works in SE37 shall work from node-rfc as well. Also check with the developer of Z_BAPI_PART_VISTA which date format expected in that particular module.
