### ISSUE TITLE
Question about prerequisites

### ISSUE THREAD

**Issue by rbn-prz** [SAP/node-rfc#108]
Hi guru, I need your help, I was testing your code but it throws me the following error:

est --testTimeout 30000

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
No files found in C: \ Users \ rperez \ Desktop \ RFC_proyect \ node_modules \ node-rfc.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: facebook.github.io/jest/docs/configuration.html
Pattern: - 0 matches
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rfc@1.0.0 test: `jest --testTimeout 30000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rfc@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C: \ Users \ rperez \ AppData \ Roaming \ npm-cache \ _logs \ 2019-10-03T14_28_52_564Z-debug.log

Sorry for my English, I'm using google translator. and I am also new to programming.
Thank you.

**Comment by bsrdjan** [comment]
Test files are not included in the npm install package, only the runtime.

To run the tests you need to clone the repository, install dependencies and change the ABAP system connection parameters in [abapSystem.js](https://github.com/SAP/node-rfc/blob/master/test/abapSystem.js), to your test ABAP system.

**Comment by rbn-prz** [comment]
thank you very much, I needed to configure the% PATH%
