### ISSUE TITLE
node-rfc version 1.0.3 crashes when submitting multiple concurrent requests 

### ISSUE THREAD

**Issue by Sgwser** [SAP/node-rfc#109]
Submitting multiple concurrent requests to invoke BAPIs will crash the nodji. Node-rfc version 1.0.3

**Comment by bsrdjan** [comment]
Could you please share the script reproducing the issue and the platform details: OS version and SAP NWRFC SDK version?

**Comment by Sgwser** [comment]
OS:         window 10 and RedHat 7
SDK:       nwrfc750P_4-70002752

**Comment by bsrdjan** [comment]
Are you using the Connection Pool ? If not, could you please check if the issue happens also when concurrent clients are obtained via Pool?

**Comment by Sgwser** [comment]
Getting a client from a connection pool works well for multiple concurrent requests.

----------------------------------------------------------------------



Confidentiality Notice:  This e-mail message, including any attachments, is for the sole use of the intended recipient(s) to which it is addressed and may contain information that is confidential, privileged or exempt from disclosure under applicable law.  Any unauthorized review, use, disclosure, printing, storing, copying or distribution is prohibited.  If you are not the intended recipient, or if you have received this email in error, please contact the sender by reply e-mail and delete all copies of the original message.  Unless specifically stated otherwise, nothing in this email is intended to serve as an electronic or digital signature.

**Comment by bsrdjan** [comment]
Hi @Sgwser, glad to hear the Pool helps. I see a notice apparently automatically appended to your comments on GitHub. Do you know why that happens and could you eventually write comments directly via GitHub portal? Just for better readability, for other users searching Issues.
