### ISSUE TITLE
Does this plugin support ubuntu machine?

### ISSUE THREAD

**Issue by EdisonDevadoss** [SAP/node-rfc#111]
Hi,
Can we install SAP NW RFC SDK in Ubuntu 18.04.3 LTS?

Help me.

**Comment by bsrdjan** [comment]
Yes, it works also on Ubuntu. Supported platforms are listed in [SAP OSS Note 2573790](https://launchpad.support.sap.com/#/notes/2573790) and although Ubuntu is not on the list here, it uses `libstdc++.so.6` and SAP NWRFC SDK can be used. Customers's support is provided for supported platforms only.

**Comment by EdisonDevadoss** [comment]
@bsrdjan When I try to run ldconfig, terminal shows the following error,

```
/sbin/ldconfig.real: /usr/local/sap/nwrfcsdk/lib/libsapnwrfc.so is not an ELF file - it has the wrong magic bytes at the start.

/sbin/ldconfig.real: /usr/local/sap/nwrfcsdk/lib/libsapucum.so is not an ELF file - it has the wrong magic bytes at the start.

/sbin/ldconfig.real: /usr/local/sap/nwrfcsdk/lib/libicudecnumber.so is not an ELF file - it has the wrong magic bytes at the start.
```

**Comment by bsrdjan** [comment]
Perhaps SAP NWRFC SDK for another platform downloaded and installed on Ubuntu? Or 32 bit instead of 64 bit? What is the output of file or readelf?

```shell
$ file /usr/local/sap/nwrfcsdk/lib/libsapnwrfc.so
/usr/local/sap/nwrfcsdk/lib/libsapnwrfc.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=446e6825b5b6349bb437746a2faed823729596df, not stripped

$ readelf -h /usr/local/sap/nwrfcsdk/lib/libsapnwrfc.so
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x81660
  Start of program headers:          64 (bytes into file)
  Start of section headers:          7881144 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         8
  Size of section headers:           64 (bytes)
  Number of section headers:         35
  Section header string table index: 32
www-admin@d7f9c04864d7:~$
```

SAP NW RFC SDK 7.50 for Linux on x86_64 64 bit should work on Ubuntu and can be downloaded from [SAP Support Portal](https://launchpad.support.sap.com/#/softwarecenter/template/products/_APP=00200682500000001943&_EVENT=DISPHIER&HEADER=Y&FUNCTIONBAR=N&EVENT=TREE&NE=NAVIGATE&ENR=01200314690100002214&V=MAINT)

<img width="1056" alt="Screenshot 2019-12-03 at 12 44 18" src="https://user-images.githubusercontent.com/1697847/70048597-ed7a1700-15ca-11ea-94e3-0da9308a89f7.png">

**Comment by EdisonDevadoss** [comment]
@bsrdjan After I use this **nwrfc750P_5-70002752** version It works successfully.
Thank you.
