### ISSUE TITLE
How to fix connection refused error.

### ISSUE THREAD

**Issue by EdisonDevadoss** [SAP/node-rfc#112]
Hi, 
When I trying to connect with SAP system it returns following error.

```
Client version:  { major: 7500, minor: 0, patchLevel: 5, binding: '1.0.3' }
could not connect to server {
  name: 'RfcLibError',
  code: 1,
  key: 'RFC_COMMUNICATION_FAILURE',
  message: '\n' +
    'LOCATION    CPIC (TCP/IP) on local host edison-HP-Notebook with Unicode\n' +
    "ERROR       partner 'xxx.xx.xx.220:3300' not reached\n" +
    'TIME        Tue Dec  3 18:01:52 2019\n' +
    'RELEASE     753\n' +
    'COMPONENT   NI (network interface)\n' +
    'VERSION     40\n' +
    'RC          -10\n' +
    'MODULE      /bas/753_REL/src/base/ni/nixxi.cpp\n' +
    'LINE        3449\n' +
    'DETAIL      NiPConnect2: xxx.xx.xx.220:3300\n' +
    'SYSTEM CALL connect\n' +
    'ERRNO       113\n' +
    'ERRNO TEXT  No route to host\n' +
    'COUNTER     2'
```

Please help me to fix this error.

**Comment by bsrdjan** [comment]
It shows a network error. Can you reach the system via SAPGUI client?

The cause could be also the error in node-rfc connection parameters mismatch, like inhalid host, port, saprouter ... The parameters used in SAPGUI connection should work with node-rfc as well.

**Comment by ragul-ct** [comment]
@bsrdjan I am able to reach the system via SAPGUI client and logon is successful.

Parameters used are - user, passwd, ashost, sysnr, client, lang, sysid

I am facing the same issue as @EdisonDevadoss does. Did I miss any parameter or something else

**Comment by bsrdjan** [comment]
Saprouter or port parameter might be missing but hard to guess without looking into system. You could add the connection parameter `trace` set to "3"  and check if any more error diagnostics recorded in a trace?

**Comment by EdisonDevadoss** [comment]
@bsrdjan I do not  have **saprouter** value. How can get **saprouter** value?

**Comment by bsrdjan** [comment]
Sorry, if saprouter not used in SAPGUI client, not needed in node-rfc connection either.

You can check if port different than default 3300 configured on message server. ABAP transaction is SMMS and [here](https://wiki.scn.sap.com/wiki/pages/viewpage.action?pageId=314673055) are some nice screenshots. If non-default port, provide the "port" connection parameter. 

Could you please add the connection parameter "trace" set to "3", to capture the communication log and post the trc file?

**Comment by bsrdjan** [comment]
Closed due to inactivity

**Comment by phanindrakoka09** [comment]
Hi bsrdjan,

Can we re-open this I have a similar issue where my system is not able to reach one particular SAP system via RFC connection but Iam able to logon to SAPGUI of that SAP system.

Please find the error message.

>> Error entry 2020-04-10 18:51:28.699 [Thread 1]
Failure to create pool for destination Custom_destination_MIP (ORIGINAL) [NAME=Custom_destination_MIP ASHOST=milsap01 SYSNR=00 ON_CCE=0 CFIT=0x0023 POOL_SIZE=10 MAX_POOL_SIZE=10 IDLE_TIMEOUT=600 IDLE_CHECK_TIME=600 MAX_POOL_WAIT_TIME=0 USER=IT800697 PASSWD=******** CLIENT=010]
SAP.Middleware.Connector.RfcCommunicationException: 
LOCATION    CPIC (TCP/IP) on local host with Unicode
ERROR       partner '168.124.190.134:3300' not reached
TIME        Fri Apr 10 18:51:28 2020
RELEASE     720
COMPONENT   NI (network interface)
VERSION     40
RC          -10
MODULE      nixxi.cpp
LINE        3285
DETAIL      NiPConnect2: 168.124.190.134:3300
SYSTEM CALL connect
ERRNO       10060
ERRNO TEXT  WSAETIMEDOUT: Connection timed out
COUNTER     2

   at SAP.Middleware.Connector.CpicConnection.ConnectAsClient(Dictionary`2 options, Boolean forRepository)
   at SAP.Middleware.Connector.RfcConnection.ConnectAsClient(RfcDestination destination, Boolean forRepository)
   at SAP.Middleware.Connector.RfcConnectionPool..ctor(RfcDestination destination, Boolean forRepositoryCalls)

Please assist and thanks in advance for your help !

**Comment by bsrdjan** [comment]
Could you please open new issue and post connection parameters used in SAPGUI and parameters used in node-rfc connection?

**Comment by guicoutinho-dev** [comment]
I have this problem
![Screenshot_5](https://user-images.githubusercontent.com/72398840/123648069-05de0200-d7ff-11eb-9997-09f8f5546d5c.png)

**Comment by ragul-ct** [comment]
> I have this problem when i try do open my connection on SAP Logon
> ![Screenshot_5](https://user-images.githubusercontent.com/72398840/123648069-05de0200-d7ff-11eb-9997-09f8f5546d5c.png)

It says that endpoint is not reached.

Check if 192.168.146.128:3200 is exposed as public endpoint. 

If it is private endpoint, connect to the same network that your server is connected to and try

**Comment by i353590** [comment]
Hello @bsrdjan,

I am also facing the same issue today. I had created the S4 system from CAL Library, now from RDP also if I try it is not accessible, and the port is also not reachable.
Though, other installations work fine (Installed with S4 instance set up in CAL like Cloud connector)

<img width="458" alt="image" src="https://user-images.githubusercontent.com/66831161/153865209-a650b678-d4ec-4b15-b778-b86f1c0a27cc.png">

Please help me here.

Thanks in advance :)

Regards,
Shubham
