### ISSUE TITLE
Compile for nw.js

### ISSUE THREAD

**Issue by Berdmanfolk** [SAP/node-rfc#118]
Hi,
It is possible to compile for nw.js(node-webkit) environment?

**Comment by bsrdjan** [comment]
According to node-webkit [documentation](https://github.com/nwjs/nw.js/wiki/using-node-modules#3rd-party-modules-with-cc-addons) it should work. I can it give it a try earliest in 6-8 weeks, because on sick leave atm. You could eventually try yourself n the meantime?

**Comment by Berdmanfolk** [comment]
Hello @bsrdjan!
I understand correctly, need to add the following lines to the package.json file:
for example:
```
"cmake-js": {
"runtime": "nw",
"runtimeVersion": "0.33.4",
"arch": "x64"
}
```
or need to change parameters for `prebuild `compilation ?:
`"prebuild": "prebuild --backend cmake-js -r nw --force --strip --verbose --tag-prefix",`
