### ISSUE TITLE
[SOLVED]The SAP NW RFC SDK could not be loaded, check the installation

### ISSUE THREAD

**Issue by fredimartins** [SAP/node-rfc#119]
Hi,

I'm trying to use this lib on windows 10 and i'm receiving this error
![image](https://user-images.githubusercontent.com/8070129/72749316-73ace580-3b98-11ea-8f28-a954926c9187.png)
This error Apparently only occurs in 1.0.2 and 1.0.3 versions

The system:
Windows 10
Node 8.11.2
nwrfc750P_5-70002726

If i try with 1.0.0 and 1.0.1 version i receive this message it seems to work
![image](https://user-images.githubusercontent.com/8070129/72749570-309f4200-3b99-11ea-801c-cb75d5ed2820.png)

**Comment by spencer-uk** [comment]
Hello fredimartins,

Let's start with 1 & 2

1) Check the installation and if all files exists and are placed correctly.
The error message is cropped on the first screenshot. I believe it
reads as "Nao foi possivel encontrar o modulo especificado" that
translates to:
"The specified module could not be found."

It looks like the file sapnwrfc.node is missing in your installation?
This file should match the node release is my understanding.

This file would be deployed with npm install if the node version you
are using is supported.

More details on:

Please refer to the link: https://github.com/SAP/node-rfc/issues/78

2) It could be again a path issue again in this case have a look at my
previous message and you can also run the commands below to double
check if the libs are installed with the right version etc.

cd %SAPNWRFC_HOME%/bin
rfcexec

Again, make sure the 1.0.2 1.0.3 binding version libs you are using
matches your computer architecture 32 or 64 bits.


*Just to repeat myself I do not work for SAP, I am just trying to help
people... :) "

Hope this helps,
Felipe

**Comment by michaelwiederhold** [comment]
Hi,

this is loosely related to issue [#115](https://github.com/SAP/node-rfc/issues/115). Your problem is probably a bit different but I have posted several ways to get to the bottom of it that should be able to help you out. 

Hint: The error message can be misleading. It might be you are not actually missing the correct sapnwrfc lib but rather the correct version of the Visual C++ runtime. 

Hope it helps!

**Comment by fredimartins** [comment]
> Hello fredimartins, Let's start with 1 & 2 1) Check the installation and if all files exists and are placed correctly. The error message is cropped on the first screenshot. I believe it reads as "Nao foi possivel encontrar o modulo especificado" that translates to: "The specified module could not be found." It looks like the file sapnwrfc.node is missing in your installation? This file should match the node release is my understanding. This file would be deployed with npm install if the node version you are using is supported. More details on: Please refer to the link: #78 2) It could be again a path issue again in this case have a look at my previous message and you can also run the commands below to double check if the libs are installed with the right version etc. cd %SAPNWRFC_HOME%/bin rfcexec Again, make sure the 1.0.2 1.0.3 binding version libs you are using matches your computer architecture 32 or 64 bits. *Just to repeat myself I do not work for SAP, I am just trying to help people... :) " Hope this helps, Felipe
> […](#)
> On 20/01/2020, fredimartins ***@***.***> wrote: Hi, I'm trying to use this lib on windows 10 and i'm receiving this error ![image](https://user-images.githubusercontent.com/8070129/72749316-73ace580-3b98-11ea-8f28-a954926c9187.png) This error Apparently only occurs in 1.0.2 and 1.0.3 versions The system: Windows 10 Node 8.11.2 nwrfc750P_5-70002726 If i try with 1.0.0 and 1.0.1 version i receive this message it seems to work ![image](https://user-images.githubusercontent.com/8070129/72749570-309f4200-3b99-11ea-801c-cb75d5ed2820.png) -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #119

For some reason my s-user only see nwrfc750P_5-70002726 was appear to be a linux version. I asked for my basis to download win10 x64 version and now i have this version.
![image](https://user-images.githubusercontent.com/8070129/72805817-83790800-3c32-11ea-9946-99edc25f6354.png)
NOT worked too...
I have all versions of vcredist between 2005 and 2017. 
I try to install again 2015 and 2017 (all x64) AND, NOT worked again.
I Try a vcredist with 2015, 2017 AND 2019 included in same installation AND, IT WORKS!
I Dont know exacly what happened to it works, the only difference is 2019 vcredist, but after install this
https://aka.ms/vs/16/release/vc_redist.x64.exe
The module works with 1.0.3
![image](https://user-images.githubusercontent.com/8070129/72806403-e1f2b600-3c33-11ea-89a1-6c9551e9be23.png)

  "_from": "node-rfc@^1.0.3",
  "_id": "node-rfc@1.0.3",

Tks for the tip!

**Comment by fredimartins** [comment]
Ok, Now i have discovered the problem.
I uninstall vcredist 2015-2019 and tried:
* Install vcredist 2015 x64 - Not able to install, already installed.
* Install vcredist 2017 x64 - Not able to install, already installed.
* Install vcredist 2019 x64 - After install this, node-rfc works well.
SAP NW RFC SDK uses vcredist 2013
![image](https://user-images.githubusercontent.com/8070129/72811039-993ffa80-3c3d-11ea-9b55-4f2f477835a3.png)
maybe sapnwrfc.node was compiled with vcredist2019?

**Comment by fredimartins** [comment]
Yeah, its the case, sapnwrfc.node depends of VCRUNTIME140_1.dll, it appear to came with vcredist2019.
![image](https://user-images.githubusercontent.com/8070129/72812159-c097c700-3c3f-11ea-884e-b707a992b753.png)
https://github.com/RPCS3/rpcs3/issues/6646
https://www.avsim.com/forums/topic/560359-vcruntime140_1dll-was-not-found/

**Comment by fredimartins** [comment]
solved.

**Comment by bsrdjan** [comment]
Current SAP NWRFC SDK requires Microsoft C Runtime DLLs version 12.0, which is a part of  [Microsoft Visual C++ Redistributable Packages for Visual Studio 2013](https://www.microsoft.com/en-US/download/details.aspx?id=40784).

The source of this information is [SAP OSS Note 2573790 - Installation, Support and Availability of the SAP NetWeaver RFC Library 7.50](https://launchpad.support.sap.com/#/notes/2573790).

The build toolchain can use also newer Microsoft Build Tools, like VS 2019. See #124.
