### ISSUE TITLE
Platform not supported linux x64

### ISSUE THREAD

**Issue by ggil** [SAP/node-rfc#12]
I installed node-rfc via "npm install", and via "git clone ..." with both ways the wrong result are the same when I run the first simple test:

node
var r = require('node-rfc');
Platform not supported linux x64
undefined

I have Ubuntu 14.04 LTS
node 5.3.0
npm 3.3.12

I have installed PyRFC and it run fine..

Regards,

**Comment by bsrdjan** [comment]
Please use the git clone method and require one of the pre-compiled binaries directly, like in the unit test:

https://github.com/SAP/node-rfc/blob/master/test/test.js#L18

The package published on npm was obsolete and I removed them, thus npm install is not possible any more, only install by `git clone` or building from source, as described in the documentation.

**Comment by ggil** [comment]
Interesting, I'll try that!

Thanks for your help Bsrdjan!
