### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by Suncatcher** [SAP/node-rfc#120]
The links to RFC client programs in http://sap.github.io/node-rfc are dead. They should these URLs:

https://wiki.scn.sap.com/wiki/display/ABAPConn/SAP+NetWeaver+RFC+SDK+--+RFC+Client+Programs

https://wiki.scn.sap.com/wiki/display/ABAPConn/SAP+NetWeaver+RFC+SDK+--+RFC+Server+Programs

https://wiki.scn.sap.com/wiki/display/ABAPConn/SAP+NetWeaver+RFC+SDK+--+Advanced+Topics

**Comment by Suncatcher** [comment]
Also link to SNC SAP Help docu [here](http://sap.github.io/node-rfc/authentication.html) is dead. Should be
https://help.sap.com/doc/saphelp_nwpi71/7.1/en-US/07/7bfc3d86ff492e9f2ac8a522d56161/frameset.htm

Also same page anchor links [with User PSE](http://sap.github.io/node-rfc/secure-auth-pse), [with X509](http://sap.github.io/node-rfc/secure-auth-x509) dead too.

**Comment by bsrdjan** [comment]
Many thabks @Suncatcher, fix comes with next release.

**Comment by Suncatcher** [comment]
Also ABAP predefined link is outdated [here](http://sap.github.io/node-rfc/intro.html#example-usage)
should be
https://help.sap.com/doc/abapdocu_751_index_htm/7.51/en-US/abenbuilt_in_types_complete.htm
