### ISSUE TITLE
Compile for win32_ia32

### ISSUE THREAD

**Issue by Berdmanfolk** [SAP/node-rfc#124]
Is it possible to compile for win32_ia32? 
I tryed on a Windows 7 32 bit machine with the ia32 target. 

> D:\_node-rfc-1.0.3>node -p "process.arch"
> ia32
> 
> D:\_node-rfc-1.0.3>node -p "process.platform"
> win32
> 
> D:\_node-rfc-1.0.3>node -v
> v12.16.0

But when doing prebuild getting the errors()
Attached a log.
[log_compile_win32_ia32.txt](https://github.com/SAP/node-rfc/files/4215853/log_compile_win32_ia32.txt)

**Comment by bsrdjan** [comment]
Reproduced and investigating

**Comment by bsrdjan** [comment]
After fixing compiler flags, I built the 32 bit binary and attached to 1.0.3 release:

[node-rfc-v1.0.3-napi-v3-win32-ia32.tar.gz](https://github.com/SAP/node-rfc/releases/download/v1.0.3/node-rfc-v1.0.3-napi-v3-win32-ia32.tar.gz)

Please feel free to test. If all works fine, the fix will be shipped with next release.

**Comment by Berdmanfolk** [comment]
Hello @bsrdjan!
Glad to hear, I hope you fully recovered.
I tested with this compilation rfc is working!
What is need to fix for self compile?

**Comment by bsrdjan** [comment]
The build script had to be fixed, as in  #4792d42 

The cross-compilation to 32 bit should work on 64 bit system but I used the 32 bit system with the minimal toolchain:

* [32 bit Windows 10 trial](https://www.microsoft.com/software-download/windows10)
* [32 bit SAP NWRFC SDK](https://launchpad.support.sap.com/#/notes/2573790) requiring
  * [32 bit Microsoft C Runtime DLLs version 12.0 -> Microsoft Visual C++  Redistributable Packages for Visual Studio 2013](https://www.microsoft.com/en-US/download/details.aspx?id=40784)
* [32 bit CMake](https://cmake.org/download/)
* [Microsoft C++ Build Tools for Visual Studio 2019](https://aka.ms/buildtools)

Linux subsystem for Windows is not available for 32 bit Windows and Git client for Windows could be an alternative:

<img width="504" alt="Screenshot 2020-03-02 at 13 16 08" src="https://user-images.githubusercontent.com/1697847/75675741-05c00780-5c88-11ea-96e0-d3294f4c73df.png">

The compilation works both from the standard Windows CLI and from VS x86 CLI.
