### ISSUE TITLE
Can't install node-rfc

### ISSUE THREAD

**Issue by alfarioekaputra** [SAP/node-rfc#13]
i follow the install instruction "npm install node-rfc" i get this error:

npm install node-rfc
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "install" "node-rfc"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/node-rfc
npm ERR! 404
npm ERR! 404  'node-rfc' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rio/Sites/holcim/npm-debug.log

thanks

**Comment by therealstan** [comment]
[node-rfc](https://www.npmjs.com/package/node-rfc) seem not to be on the web-site anymore

**Comment by bsrdjan** [comment]
right, the clone & build is the only supported installation method, just updated the README.

**Comment by dinesh-Rampal** [comment]
request help to on how to build node-rfc on a 64 bit windows 7 pc.

**Comment by therealstan** [comment]
which step causibng you problems?

**Comment by dinesh-Rampal** [comment]
I wouldn't know after i have downloaded the zip file , what are the steps
to compile and build node-rfc to use it in my project. since it is written
that node-rfc cannot be installed using npm (i also tried and i couldn't) i
decided to this, but I am clueless.

You can also point me to some repository from where i can read and try.

Thanks & regards
dinesh

**Comment by therealstan** [comment]
Well at first here [here](http://sap.github.io/node-rfc/install.html#installation).

I had a problem with `binding.gyp` File. In there  i had to set `"msvs_nwrfcsdk_path": "<location of nwrfcsdk>"` manually.

Some issues were adressed[ here](https://github.com/jdorner/node-sapnwrfc) -  so i could manage to solve my problems.  Feel free to post a error message.

**Comment by dinesh-Rampal** [comment]
Thanks for the encouragement. will revert once i give a decent shot!

regards
dinesh
