### ISSUE TITLE
win32 cross compilation issue

### ISSUE THREAD

**Issue by jmarcgit** [SAP/node-rfc#130]
Hi,

I had to install cmake-js 6.x in order to compile a win32 version on a win64 host.
Then all ll I had to do was to set the -A option before running npm install :
npm config set cmake_js_A "Win32"

Problem is that cmake-js version 5.x doesn't support the CMAKE -A option. I'm using VS 16 2019 and the -A option is now mandatory in order to build x86 binaries.

Could you please upgrade cmake-js to version 6 ?

**Comment by bsrdjan** [comment]
Thank you for the hint about so elegant solution. Will test on Windows and add to documentation. 

cmake-js is already upgraded in master, comes out with next npm release.

**Comment by jmarcgit** [comment]
You are welcome, thank you. Took me a while to understand why the parameter was ignored during the build. I will try to compile the master branch.

**Comment by jmarcgit** [comment]
I confirm it works perfectly fine with master branch.
