### ISSUE TITLE
macOS - library validation: library load disallowed by system policy

### ISSUE THREAD

**Issue by stesap** [SAP/node-rfc#140]
I followed the [installation steps](http://sap.github.io/node-rfc/install.html#macos), did copy the nwrfcsdk to the standard path `/usr/local/sap/nwrfcsdk` and executed successfully the [paths_fix.sh script](https://github.com/SAP/PyRFC/blob/master/ci/utils/paths_fix.sh).

## Error
When I require node-rfc lib, a popup is shown with the following error message: 
**“libsapnwrfc.dylib” is damaged and can’t be opened. You should move it to the Bin.**

## Console output
```sh 
Error: dlopen(/Users/<user>/projects/rfc-node-test/node_modules/node-rfc/lib/binding/sapnwrfc.node,

1): Library not loaded: @rpath/libsapnwrfc.dylib
Referenced from: /Users/<user>/projects/rfc-node-test/node_modules/node-rfc/lib/binding/sapnwrfc.node

Reason: no suitable image found.  Did find:
/usr/local/sap/nwrfcsdk/lib/libsapnwrfc.dylib: code signature in (/usr/local/sap/nwrfcsdk/lib/libsapnwrfc.dylib) not valid for use in process using Library Validation: library load disallowed by system policy
```

**Comment by bsrdjan** [comment]
I reproduced and need to investigate further.

The click on "?" in a pop-up, shows a new pop-up:

<img width="709" alt="Screenshot 2020-05-05 at 16 13 56" src="https://user-images.githubusercontent.com/1697847/81076072-7b945980-8eeb-11ea-8459-52ab8380ccbd.png">

SAP lib file is "corrupted" by fix script, changing `@loader_path` to `@rpath`, using Apple `install_name_tool`. After running the script, the lib signature is not valid any more:

```shell
$ codesign --verify libsapnwrfc.dylib
libsapnwrfc.dylib: invalid signature (code or signature have been modified)
In architecture: x86_64
```

It seems Apple security policy changed again, preventing the changed lib to be loaded.  Which macOS version are you using? 

I am on 10.15.4 but installed and "fixed" SAP 7.56 libs with older Darwin version. These libs still work for me but if I download and fix the same lib from SAP portal, I am getting the same error.  

The funny thing is that downloaded and fixed libs, which do not work, are binary identical to currently working libs, showing the same invalid signature (only downloaded and fixed before). 

As a workaround you can:

1. Copy original, non-modified SAP libs into same `lib\binding` folder, where `sapnwrfc.node` is located

2. Fix `sapnwrfc.node` @rpaths to @loader_paths:

```shell
$ cd lib\binding
$ install_name_tool -change @rpath/libsapnwrfc.dylib @loader_path/libsapnwrfc.dylib sapnwrfc.node
$ install_name_tool -change @rpath/libsapucum.dylib @loader_path/libsapucum.dylib sapnwrfc.node 
```

To verify:

```shell
$ otool -L sapnwrfc.node                                                                                 (py380) master ✱
sapnwrfc.node:
        @rpath/sapnwrfc.node (compatibility version 0.0.0, current version 0.0.0)
        @loader_path/libsapnwrfc.dylib (compatibility version 0.0.0, current version 0.0.0)
        @loader_path/libsapucum.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
``` 
3. Remove/rename  `/usr/local/sap/nwrfcsdk` folder

This could help until a better solution found.

**Comment by bsrdjan** [comment]
The loader_path is apparently fixed in SAP NWRFC SDK and post-install script not required any more. The README is updated with simplified installation method: https://github.com/SAP/node-rfc#macos.

**Comment by bsrdjan** [comment]
Doing more testing, found out that [DYLD env vars are purged in spawned child processes](https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/RuntimeProtections/RuntimeProtections.html).

**Comment by nitinsaroha** [comment]
I am facing the same problem. I am on macOS 10.15.5

**Comment by bsrdjan** [comment]
Please use NWRFC SDK PL5 if you have it.

**Comment by prakashpalanichennai** [comment]
If anyone getting the following issue in Mac, then please try the below option.

**Error**
Reason: no suitable image found.  Did find:
        /usr/local/sap/nwrfcsdk/lib/libsapnwrfc.dylib: code signature in (/usr/local/sap/nwrfcsdk/lib/libsapnwrfc.dylib) not valid for use in process using Library Validation: library load disallowed by system policy

**Terminal**
sudo spctl --master-disable

This should enable the app from the undentified developers, please be aware that this relaxes the security & privacy settings of your Mac, so enable it with caution.

**Comment by yaoyuande** [comment]
Can you please give me the  NWRFC SDK PL5  for mac os x,my Email Address is 754716208@qq.com.Thanks

**Comment by yntedero** [comment]
On MacOS 15.0.1 Sequoia, you have run it in Terminal:

Problem with opening file **libsapjco3.dylib**

sudo spctl --master-disable

Then open System Settings, and Privacy & Security. On this page scroll down to the tab Security and you will see your .dylib file with button open anyway. Click it and done
