### ISSUE TITLE
SAP NWRFC SDK on Darwin works for single processes only 

### ISSUE THREAD

**Issue by bsrdjan** [SAP/node-rfc#143]
After Apple security policy elevated, patched SAP NWRFC SDK does not work any more on Darwin 10.15.4, see #140.

Un-patched SDK, from SAP Support Portal, can be used with DYLD_FALLBACK_LIBRARY_PATH env variable set to SDK binaries path (`$SAPNWRFC_HOME/lib` folder) and it works for single process only.

Possible solutions are investigated with SAP NWRFC SDK experts.

**Existing users**

If your SAP NWRFC SDK and node-rfc already work on Darwin, you can upgrade Darwin and node-rfc, keeping the full functionality. If you upgrade SAP NWRFC SDK, it works in single process apps only.

**New users**

Install the SAP NWRFC SDK and set DYLD variable, like described in README. It works in single process apps only until this issue closed.

**Comment by jack0088** [comment]
@bsrdjan I installed the nwrfcsdk, then set the paths as you've stated. I now no longer get the codesign error but somethings still not right.. could you explain what's missing?
<img width="1095" alt="Bildschirmfoto 2020-05-08 um 12 57 36" src="https://user-images.githubusercontent.com/1267980/81399833-0ebbd200-912c-11ea-8739-d331b547b1cf.png">

**Comment by bsrdjan** [comment]
Thank you @jack0088. Please consider that [DYLD* variables are purged in child processes](https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/RuntimeProtections/RuntimeProtections.html), now matter if set in shell, node app etc. I came across that after having a simple node script working stand-alone with DYLD* and failing when executed by for example `jest` test framework,. The DYLD* variables were set in the node app itself, just before loading the lib, but did not help.

**Comment by bsrdjan** [comment]
Did you try using previous, PL5 NWRFC SDK version, with the patch, until this issue solved?

**Comment by PaulWieland** [comment]
to people affected by this, I would recommend using Docker as it specifically addresses issues like this.

@bsrdjan I'm working on getting a light docker container working with node and node-rfc, if there is interest in SAP including or publishing this dockerfile I will share.

**Comment by bsrdjan** [comment]
Yes. that would be another nice workaround for users affected with Darwin/PL6 issue, we still work on. Would you publish here, inside the new docker folder for example, as a contributor, or on docker hub?

**Comment by PaulWieland** [comment]
I would suggest publishing the dockerfile here on github and the built docker image on dockerhub.
It's not something I would publish directly as technically I would be redistributing the precompiled nwsdk libraries. I'm sure that violates a EULA somewhere...

**Comment by guptar85** [comment]
@bsrdjan @PaulWieland - I am using below Docker File. My use-case was different as I want to call SAP from Pivotal Cloud Foundry so I hosted container on PKS. I guess below DockerFile will work for any scenario.

### Dockerfile

`#Create a layer from the node:lts Docker image.`
`FROM node:lts`

`#Copying SDK from local to the desired location`
`ADD nwrfcsdk /usr/local/sap/nwrfcsdk`

`#Settign environment variable as mentioned in the document`
`ENV SAPNWRFC_HOME=/usr/local/sap/nwrfcsdk`

`RUN echo /usr/local/sap/nwrfcsdk/lib > /etc/ld.so.conf.d/nwrfcsdk.conf && ldconfig`

`#Changing the Working directory `
`WORKDIR /usr/app`

`#Copying the source code to /usr/app/src from current directory`
`COPY src/ .`

`#Running NPM install`
`RUN npm i`

`#Exposing the PORT`
`EXPOSE 3000`

`#Running the application`
`CMD [ "node", "index.js" ]`

### .dockerignore

`.git`
`.gitignore`
`**/node_modules`

Thanks!

**Comment by PaulWieland** [comment]
Thanks for sharing your dockerfile @guptar85. The node:lts base image is quite large at nearly 1GB.

I'm trying to reduce the image size by building off of one of the really small base images for node (Alpine Linux is 5mb, and alpine + node is ~40mb for example). It's proving to be a challenge because the NWRFCSDK doesn't work in MUSL based linux environments. I am making progress with some of the other "slim" glibc based images.

I still think it should be possible to get a working node + node-rfc base image that is in the 200mb or less range, but we will see :)

**Comment by guptar85** [comment]
@PaulWieland - Yes initially I tried with Alpine but it didn't work with NWRFCSDK. If you change the version of Node from `lts` to `lts-slim` in Dockerfile and size will reduce to 377MB (where `lts-slim` is 142 MB and NWRFCK folder is 50MB and remaining is my src folder along with node_modules)

  Below screenshot is few comparisons with different tag's I tried with the dockerfile

![image](https://user-images.githubusercontent.com/63718017/84572180-1408de00-adb6-11ea-83df-67a2d9e216fd.png)


Thanks!

**Comment by stesap** [comment]
just to be mentioned, there is also a official Dockerfile avail. by SAP https://github.com/SAP/devops-docker-images/tree/master/node-rfc

**Comment by ankri** [comment]
Is there a recommended way to get the PL 5 Version of the NWRFCSDK for Catalina? I am only able to download the PL6 from the Launchpad.

**Comment by bsrdjan** [comment]
Sorry, the PL5 is not available on SAP Support Portal.
