### ISSUE TITLE
NW.js and Electron platforms support

### ISSUE THREAD

**Issue by yerkeyzet** [SAP/node-rfc#144]
Hi Team,

There is an issue when running node-rfc with NW.js or Electron on Windows 10. After running "npm start" it throws an error:
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\?\C:\Storage\code\nwjs-hands-on\node_modules\node-rfc\lib\binding\sapnwrfc.node

It is easy to reproduce, just download my ready to run codes, npm install, and npm start - you will get the error in Dev tools console.
[nwjs-hands-on.zip](https://github.com/SAP/node-rfc/files/4611490/nwjs-hands-on.zip)

I have tried rebuilding node-rfc with MSVS 2012, 2013, 2015, 2017, 2019 - none of them helped.
Command I used is:
npm install node-rfc --build-from-source --runtime=node-webkit --target=0.45.5 --target_arch=x64

On the other hand node-rfc works perfectly with Node.js app on the same Windows 10 machine.

What exact Visual Studio version do you use to compile C/C++ codes for this module?
Any ideas how to proceed further?

**Comment by yerkeyzet** [comment]
You may need to run the following, if nw does not install automatically:

npm install nw@0.45.5-sdk

**Comment by bsrdjan** [comment]
Please feel free to try workarounds mentioned in [napi#269](https://github.com/nodejs/node-addon-api/issues/269#issuecomment-627391423), until the solution found.

**Comment by yerkeyzet** [comment]
Thanks a lot for your feedback.

I went through the topic and found that one of the add-on developers could resolve this problem in his add-on a couple of days ago. I have asked him to update on the root cause, lets wait and see if it is applicable for node-rfc.

**Comment by yerkeyzet** [comment]
He answered in the thread above, please have a look if you see any hints...

I tried step 2 from workaround below, but no result. Can you apply step 1 from your side?
_1. Add set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "/DELAYLOAD:node.exe" ) to the Windows version of our native module in CMakeLists.txt
2. Add a delay load hook based on the code here: https://github.com/billti/create-vs-napi/blob/master/template/win_delay_load_hook.cc.txt_

I also opened a new issue on their page based on your message, as the topic above was already closed and there is no guarantee that they will consider further activities of a closed topic.

**Comment by bsrdjan** [comment]
I tried step 1 alone and it did not help but both steps together could eventually make a difference. Where exactly did you add the step 2 ?

The step 1 requires one line insert into `CMakeLists.txt`, after LTCG parameter at [line 173](https://github.com/SAP/node-rfc/blob/master/CMakeLists.txt#L173): 

```cmake
target_link_options(${PROJECT_NAME} PUBLIC
    /NXCOMPAT
    /SWAPRUN:NET
    /OPT:REF
    /NOLOGO
    /LTCG
    /DELAYLOAD:node.exe
)
```
You can add the line and build sapnwrfc.node from source, running `npm run prebuild`. 

Here the Windows build with step 1 only:
[sapnwrfc.node.zip](https://github.com/SAP/node-rfc/files/4621465/sapnwrfc.node.zip)

**Comment by yerkeyzet** [comment]
1) I put `win_delay_load_hook.cc` to these locations:

`npm install node-gyp -g`

`C:\Users\Yerkebulan\AppData\Roaming\npm\node_modules\node-gyp\src\`
`C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\`

2) I modified `C:\Storage\code\electron-quick-start_RFC\node_modules\node-rfc\CMakeLists.txt` as you said, then ran `npm run prebuild` under `C:\Storage\code\electron-quick-start_RFC\node_modules\node-rfc\`, but error still exists.

3) I downloaded your `sapnwrfc.node` file and placed it to `C:\Storage\code\electron-quick-start_RFC\node_modules\node-rfc\lib\binding\`

But still it gives me an error :(

What am I doing wrong?

My Node,js version is 14.2.0
Electron 8.2.5

**Comment by yerkeyzet** [comment]
I also tried with Node 12.13.0 as you do -- but still an error.

My Windows 10 version is 1909
I compile with Visual Studio 2019

What is your VS version?

**Comment by bsrdjan** [comment]
I am using VS2019 and used Node 12.13.0 because that version used in Electron 8.

**Comment by bsrdjan** [comment]
Why NW.js is mentioned if initial/top comment, when the issue is about Electron?

**Comment by yerkeyzet** [comment]
I first faced this issue in NW.js, then tried in Electron and got same error there.

For now both of them don't work for me.

> Here the Windows build with step 1 only: sapnwrfc.node.zip
I now realized that you attached a build only with step 1. Can you please attached a build that worked for you on Windows 10?

**Comment by bsrdjan** [comment]
Sorry, no build worked for me on Windows and I did not test NW. 

Please have a look into Electron [documentation](https://www.electronjs.org/docs/tutorial/using-native-node-modules) and try if any of methods described there eventually work for you?

None of them worked for me and I asked prebuild and Electron teams for help:

* [prebuild/](https://github.com/prebuild/prebuild/issues/269)

* [Electron/#23587](https://github.com/electron/electron/issues/23587)

**Comment by yerkeyzet** [comment]
I've been struggling with this issue for about a week and have tested all possible methods including this...

Ok, thanks for contacting with other teams!
I hope we will manage to create SAP RFC desktop apps with JS.

**Comment by vullnet-kurti** [comment]
I'm getting the same error but with zeit/pkg. 
Any updates on this? or any workarounds?

**Comment by yerkeyzet** [comment]
Hi,

Unfortunately no updates so far...

**Comment by KSchala** [comment]
Also getting the error with zeit/pkg.. are there any updates?

**Comment by bsrdjan** [comment]
Tested again on Windows 10, with SAP NWRFC SDK 7.50 PL7 and node-rfc 2.3.0 and the same issue occurs.

The Process Monitor shows SDK libraries are found and for some reason still not loaded:

<img width="1088" alt="Screenshot 2020-10-27 at 12 26 58" src="https://user-images.githubusercontent.com/1697847/97303175-5bba6e80-185a-11eb-9841-56a5d5db3d7f.png">

Although it works on Linux and MacOS, the SAP NWRFC SDK is not supported on Electron platform. You may create SAP feature request for `SAP Cloud Platform Connectivity Service` subtopic of the [SAP Cloud Platform - Integration Suite](https://influence.sap.com/sap/ino/#/campaign/2282).

**Comment by bung87** [comment]
I solve this by 
`set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "${CMAKE_SHARED_LINKER_FLAGS}" ) `  
I use cmake-js  CMAKE_SHARED_LINKER_FLAGS  equals `/DELAYLOAD:node.exe`  
I install my native module runtime to `electron` and works fine on windows now.

`target_link_libraries(${PROJECT_NAME} ${CMAKE_JS_LIB} ${OS_LIBS}` while OS_LIBS contains "DelayImp.lib"  

CMAKE_JS_LIB contains `node.lib`  

also follow cmake Include N-API wrappers section 

```
execute_process(COMMAND node -p "require('node-addon-api').include"
        WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
        OUTPUT_VARIABLE NODE_ADDON_API_DIR
        )
string(REPLACE "\n" "" NODE_ADDON_API_DIR ${NODE_ADDON_API_DIR})
string(REPLACE "\"" "" NODE_ADDON_API_DIR ${NODE_ADDON_API_DIR})
target_include_directories(${PROJECT_NAME} PRIVATE ${NODE_ADDON_API_DIR} )
```

so I think here is 3 key points:
1.  LINK_FLAGS `/DELAYLOAD:node.exe`  
2. link library "DelayImp.lib"  and `node.lib`  
3.  include_directories "require('node-addon-api').include"  

these mentioned in electron's document and cmake-js's readme but they don't provide a full example.

**Comment by bsrdjan** [comment]
Could you please try with node-rfc@3.0.0-rc.2

**Comment by bsrdjan** [comment]
Electron is supported as of node-rfc@3.1, also on Windows
