### ISSUE TITLE
The specified module could not be found.

### ISSUE THREAD

**Issue by AmnahZia** [SAP/node-rfc#159]
I have installed node-rfc will all the prerequisites and have followed all the troubleshooting steps that are running  fine. 
I am currently only trying to run the following lines of code:

"use strict";
const Client = require("node-rfc").Client;

![Capture](https://user-images.githubusercontent.com/41870347/88506836-55ff8380-cff4-11ea-964f-1db93e55f27f.PNG)

and getting the error that it can not find the module sapnwrfc.node. Though, the file is present at the same location that it specifies.

I am using nwrfc750P_6-70002755 and
The latest version of node LTS 12.18.3

Please help me find the bug.

Thank You

**Comment by bsrdjan** [comment]
The `sapnwrfc.node` is found and the error complains about not being able to find or load the SAP NWRFC SDK.

Here more info on SDK installation and few troubleshooting tips:
https://github.com/SAP/node-rfc/blob/master/doc/installation.md#sap-nwrfc-sdk-installation

**Comment by AmnahZia** [comment]
None of the mentioned solutions worked for me. I have found an alternate way to make things work. I copied all the files from sapnwrfc/lib folder, pasted them to C:\\windows\system32 and it's working like a charm.
Though, i still can't figure out the logic behind this making it work.

**Comment by bsrdjan** [comment]
It sounds like SAP NWRFC SDK `lib` folder was not on Windows PATH, or the user did not have permissions for SAP NWRFC SDK `lib` folder.

**Comment by AmnahZia** [comment]
It was on the windows PATH, might be an issue with the permission.
