### ISSUE TITLE
Error when calling RFC BAPI_BUPA_CENTRAL_GETDETAIL from node.js application

### ISSUE THREAD

**Issue by sap2019** [SAP/node-rfc#163]
Hi,

I am getting error "Error invoking BAPI_BUPA_CENTRAL_GETDETAIL [TypeError: Char expected when filling field BUSINESSPARTNER of type 0] while calling RFC BAPI_BUPA_CENTRAL_GETDETAIL from node.js locally.
Below is my source code
var client = new rfc.Client(abapSystem);
      var  BPARTNER_str = {
          BPARTNER : "407"
        };
	
client.connect(function(err) {
    if (err) {
        return console.error('could not connect to server', err);
    }	
    client.invoke('BAPI_BUPA_CENTRAL_GETDETAIL', {
			BUSINESSPARTNER: BPARTNER_str
        },
        function(err, res) {
            if (err) {
                return console.error('Error invoking BAPI_BUPA_CENTRAL_GETDETAIL', err);
            }
		console.log('Result BAPI_BUPA_CENTRAL_GETDETAIL:', res);
        });	
});

**Comment by bsrdjan** [comment]
It is a bug, need to be fixed.

**Comment by bsrdjan** [comment]
Checked the RFM signature and the `node-rfc` works correct. The `BUSINESSPARTNER` is a variable, not the structure.

Try:

```node
    client.invoke(
        "BAPI_BUPA_CENTRAL_GETDETAIL",
        {
            BUSINESSPARTNER: "407",
        },
```

**Comment by sap2019** [comment]
@bsrdjan : thanks alot. Its working now.
