### ISSUE TITLE
Could it be possible to get rid of limitation in form of Microsoft Studio Build Tools?

### ISSUE THREAD

**Issue by DenisTis** [SAP/node-rfc#169]
Probably earlier it was free-to-use, but now it is commercial access only.
Could there be a workaround?

**Comment by bsrdjan** [comment]
Not sure I understand 100% but MSVS Build Tools are required only when building the node-rfc from source and and the Community version is still available free of charge: https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019

What exactly is now commercial, could you please share the link?

**Comment by DenisTis** [comment]
Hi Srdjan, thank you for the support and quick answer, I oversaw the link to build tools for C++ during installation and thought that Visual Studio itself is needed (and its most limited version is only students-free).
Thank you again, I will close the issue.
