### ISSUE TITLE
Unable to run the go.file

### ISSUE THREAD

**Issue by Sapna100** [SAP/node-rfc#170]
I am facing the below issue when i try to run the go.file on Windows
PFB the error:

D:\Go_Folder\src\sap_con>go run sap_connection.go
 #github.com/sap/gorfc/gorfc
..\..\pkg\mod\github.com\sap\gorfc@v0.1.0\gorfc\gorfc.go:52:10: fatal error: sapnwrfc.h: No such file or directory
 #include <sapnwrfc.h>
compilation terminated.

Please suggest.

**Comment by bsrdjan** [comment]
This repository is for node-rfc and NodeJS related issues, pplease create the gorfc issue.
