### ISSUE TITLE
ERROR MESSAGE : "internal error"

### ISSUE THREAD

**Issue by SimJH** [SAP/node-rfc#174]
Hi,

I checked error message through dev_rfc.trc.

RFC invoke works well, but sometimes error messages like the following occur.

Do you know why it happened??

I also want to know what Counter means.

I'd appreciate it if you could check it out.

**** Trace file opened at 2020-08-31, 17:21:01 Central Daylight Time
 RFC library: 721, Current working directory: D:\app, Program: node
 Hardware: PC with Windows NT 8x AMD64 Level 6 (Mod 85 Step 4), Operating_system: Windows NT 6.3, Kernel_release: 721 patchlevel 42
 Hostname: "SAPSERVER", IP address: "IP", IP address_v6: "IP"

LOCATION    CPIC (TCP/IP) on local host with Unicode
ERROR       internal error
TIME        Mon Aug 31 17:21:01 2020
RELEASE     721
COMPONENT   NI (network interface)
VERSION     40
RC          -1
DETAIL      NiErrSet
COUNTER     8

LOCATION    CPIC (TCP/IP) on local host with Unicode
ERROR       internal error
TIME        Mon Aug 31 19:00:29 2020
RELEASE     721
COMPONENT   NI (network interface)
VERSION     40
RC          -1
DETAIL      NiErrSet
COUNTER     12

LOCATION    CPIC (TCP/IP) on local host with Unicode
ERROR       internal error
TIME        Mon Aug 31 19:00:53 2020
RELEASE     721
COMPONENT   NI (network interface)
VERSION     40
RC          -1
DETAIL      NiErrSet
COUNTER     6

**Comment by bsrdjan** [comment]
I will try to find more info on this particular error message.

The trace shows an old SAP NWRFC SDK release is used, not supported any more. Can you try the current SDK version and check if errors still occurs? The error message in newer releases is maybe more descriptive.

**Comment by SimJH** [comment]
Thank you. I'll try the latest version and show you a clearer error message.

**Comment by EdisonNetcon** [comment]
@bsrdjan can you give any idea about what **counter** means?

**Comment by bsrdjan** [comment]
Hello @EdisonNetcon,

the COUNTER field is context dependent and one C-PIC trace is required to interpret this value. If needed, the CPIC trace can be shared via customer ticket for component BC-MID-RFC-SDK, in https://sap.service-now.com/
