### ISSUE TITLE
Request Compatibility with official NodeJS Docker Image

### ISSUE THREAD

**Issue by PaulWieland** [SAP/node-rfc#176]
I referred to this in [issue 165](https://github.com/SAP/node-rfc/issues/165), but decided it should be it's own thread.

Right now it is not possible to use `npm install node-rfc` under [NodeJS's official docker images](https://hub.docker.com/_/node) because the version of `libstdc++6` that comes with those images is slightly too old. There is no easy way to upgrade it either because the package the library comes in is already at the latest available revision.

That leaves us with having to build a base image with all the compiler tools, compile node-rfc, then copy the package to a slim container (and then get npm to play nice with it). If anyone knows a cleaner/faster way, please let me know.

I would imagine that these docker images are the starting place for many node developers, so I don't think I'm alone here.

**Details:**

- The node-rfc package was compiled on `Ubuntu:latest` which has `GLIBCXX_3.4.26`, and so that's what ndoe-rfc requires. 
- The nodejs base images are built on Debian, with [buster](https://wiki.debian.org/DebianReleases) being the latest release. This comes with `GLIBCXX_3.4.25`.
- `npm install node-rfc` completes successfully, but when you try and include node-rfc the dreaded `Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found` is thrown.

**Comment by bsrdjan** [comment]
Thanks @PaulWieland, the lower GLIBC version makes sense. The next releases will be compatible with glibc >= 2.17 and libstdc++ >= 6.0.20 (GLIBCXX_3.4.20, which are available on distributions natively supporting GCC 4.9, such as Ubuntu 14.04 and Debian 8.

The build toolchain is now exactly the same one used for official NodeJS builds, based on Centos and devtoolset-8:

[nodejs/node/BUILDING.md#supported-toolchains](https://github.com/nodejs/node/blob/master/BUILDING.md#supported-toolchains)

The Centos docker image used for node-rfc builds is now maintained within SAP fundamental-tools project, please feel free to test:

[fundamental-tools/docker](https://github.com/SAP/fundamental-tools/tree/master/docker)

**Comment by PaulWieland** [comment]
I just wanted to say that this update has been a huge help. My docker images are now 40% of the size they used to be, and they build that much faster.
