### ISSUE TITLE
Unable to install node-rfc on Ubuntu 16.04

### ISSUE THREAD

**Issue by eshikafe** [SAP/node-rfc#18]
austin@analytics:~/node-rfc$ npm install
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> node-rfc@0.1.5 install /home/austin/node-rfc
> node-gyp rebuild

make: Entering directory '/home/austin/node-rfc/build'
  CXX(target) Release/obj.target/rfc-v6.9.1/src/rfc.o
In file included from ../src/rfc.cc:19:0:
../src/Client.h:23:22: fatal error: sapnwrfc.h: No such file or directory
compilation terminated.
rfc-v6.9.1.target.mk:109: recipe for target 'Release/obj.target/rfc-v6.9.1/src/rfc.o' failed
make: **\* [Release/obj.target/rfc-v6.9.1/src/rfc.o] Error 1
make: Leaving directory '/home/austin/node-rfc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-31-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/austin/node-rfc
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! node-rfc@0.1.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rfc@0.1.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-rfc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-rfc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-rfc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/austin/node-rfc/npm-debug.log
austin@analytics:~/node-rfc$ node

**Comment by eshikafe** [comment]
austin@analytics:~/node-rfc$ node -v
v6.9.1
austin@analytics:~/node-rfc$ npm -v
3.10.8
austin@analytics:~/node-rfc$

**Comment by bsrdjan** [comment]
It seems that the compiler cant find sapnwrfc include files:

```shell
In file included from ../src/rfc.cc:19:0:
../src/Client.h:23:22: fatal error: sapnwrfc.h: No such file or directory
```

Could you please check if SAPNWRFC_HOME env variable is set and points to the root folder of the SAP NW RFC Lib, like `/usr/local/sap/nwrfcsdk`, for example ?

**Comment by bsrdjan** [comment]
closed due to inactivity
