### ISSUE TITLE
V2.1.0 Client Version is undefined

### ISSUE THREAD

**Issue by izzuddin-noormy** [SAP/node-rfc#180]
Hi,

I just found out, that version 2.1.0 whenever my script hit this line of code it says undefined

// create new client
const client = new Client(sapConfig.SAP_DEV);

// echo SAP NWRFC SDK and nodejs/RFC binding version
console.log("Client version: ", client.version);

**Comment by bsrdjan** [comment]
The `client.version` is replaced with `client.environment.noderfc.nwrfcdk` see [2.0 breaking changes](https://github.com/SAP/node-rfc/blob/master/CHANGES#L73)

```javascript
  noderfc: {
    version: '2.2.0',
    nwrfcsdk: { major: 7500, minor: 0, patchLevel: 7 }
  }
```

**Comment by izzuddin-noormy** [comment]
Perfect thank you @bsrdjan
