### ISSUE TITLE
Unreadable characters on RFC reponse data

### ISSUE THREAD

**Issue by valix999** [SAP/node-rfc#182]
I'm trying to call RFC from my nodejs application and found that the response structure of RFC is combining with some unreadable characters.

![image](https://user-images.githubusercontent.com/31177435/97960919-e532e900-1de4-11eb-944f-5c78be9b52ee.png)

**Comment by bsrdjan** [comment]
If you recently upgraded SAP NWRFC SDK to PL7, the node-rfc needs an upgrade too: #181

If not, could you please post the output of:

```shell
$  node -p "require('node-rfc').environment"
```

and 

```shell
$ npx envinfo --system --binaries 
```

**Comment by bsrdjan** [comment]
You can try this workaround for PL7: https://github.com/SAP/node-rfc/issues/189#issuecomment-736527285
