### ISSUE TITLE
TypeError: Client constructor requires an argument

### ISSUE THREAD

**Issue by wush2000** [SAP/node-rfc#185]
Hello, according to your documentation try catch is working but at least in case of wrong ip or wrong username/password it doesnt work for me.
While the trace log is showing hostname 'asdf' unknown the app just crash with this:
throw new TypeError(`Client constructor requires an argument`);

Can you confirm please ?

Example Code:

       try { 
       var rfcClient = await rfcPool.acquire();
           } catch (e) {
        console.log(e);
    }

thank you

**Comment by bsrdjan** [comment]
Wrong ip and credentials are covered by unit tests and I need some more info. 

What is the output of:

```shell
$ node -p "require('node-rfc').environment"  
```

Could you please share the full test script to reproduce the issue, including the output.

**Comment by wush2000** [comment]
Following code is working and as soon as I change any connection parameter (abapSystem) to something wrong the app still just crash. I would like to have a proper error message in case of wrong username/password.  I wonder if that is possible. 

Complete Code:


const abapSystem =   {
    SYSNR:'00',
    ASHOST:'v75',
    CLIENT:'800',
    USER:'ddic',
    PASSWD:'password',
    LANG:'en',
    CODEPAGE:'8400',
    TRACE:'2'
};

const noderfc  =  require ('node-rfc');
const pool =  new noderfc.Pool({ connectionParameters: abapSystem, poolOptions: { low: 2, high: 10 }} );

  module.exports =  (async () =>  {
       try { 
       var rfcClient = await pool.acquire();
       var download = await rfcClient.call("BAPI_USER_GETLIST", {MAX_ROWS: 10});  
            } catch (err) {
        console.log(err);
            }
            finally {
        rfcClient.release();
        console.log("entering and leaving the finally block");
    return download;             
}

     
})();

**Comment by bsrdjan** [comment]
Thank you for the example. Yes, it is bug and fixed in main branch for now: [src/ts/wrapper/sapnwrfc-pool.ts](https://github.com/SAP/node-rfc/commit/54a82b677d71e1807bdb23d18fe56728fd15e3c8#diff-56006b5e996d8bcf7d3f23fdb669984b2163e2774cf343466377709f753c4e1d)

**Comment by wush2000** [comment]
Hello !
you are amazing! Thank you so much. Cannot wait to test it.
but, I am afraid, currently im having problems to update node-rfc. 
Im pretty surprised and lost for now.


Even a fresh installation goes wrong:
Command-Line: https://pastebin.com/GaTxuwMr
Log: https://pastebin.com/EEcE2Y66


Is it a personal problem or could it maybe a problem in general ?
Any hint would be highly appreciated .

**Comment by bsrdjan** [comment]
Yes, the general problem, will be fixed in next release.

The installation and build from source work for [N-API 7 node versions only](https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix): >= 12.19.0, >= 14.12.0.

For now, you can install with these N-API 7 node versions and use from any node-version.

**Comment by wush2000** [comment]
Thank you for the instruction.

I have tested all scenarios I could think of and its just working perfect.
Thank you. Ticket can be closed.

**Comment by bsrdjan** [comment]
Glad to hear. I will open another ticket for the installation issue.
