### ISSUE TITLE
noderfc_binding.Client is not a constructor

### ISSUE THREAD

**Issue by nvokrri** [SAP/node-rfc#188]
Having this issue with the Client constructor. Using rfc sdk version 7.5 PL6 and node-rfc version 2.0

**Comment by bsrdjan** [comment]
Please post the script to reproduce the issue, including full error log.

**Comment by nvokrri** [comment]
So this is a typescript project bundled using webpack and then I am running it using node version 12.18.3 on a windows 2012 server. When I attempt to create a Client and call an RFC the following error gets thrown:
`Clientnoderfc_bindings_1.noderfc_binding.Client is not a constructor`
`TypeError: noderfc_bindings_1.noderfc_binding.Client is not a constructor`
   ` at new Client (/test-project/dist/index.js:3211:19)`
I have the LD_LIBRARY_PATH environment variable set to point to the lib directory of the rfc sdk

**Comment by bsrdjan** [comment]
Why you set the Linux LD_LIBRARY_PATH on Windows?

Could you please update to the latest node-rfc and post the test script to reproduce the error? Need also the output of, executed from your node project root:

```shell
PS>  node -p "require('node-rfc').environment"
```

**Comment by bsrdjan** [comment]
Please reopen if the question still open
