### ISSUE TITLE
Node 6 support

### ISSUE THREAD

**Issue by soulchild** [SAP/node-rfc#19]
After upgrading to Node 6 and recompiling the node-rfc library, I'm getting "Segmentation faults" on `invoke()` calls. Is this just me or is Node 6 not officially supported yet?

**Comment by bsrdjan** [comment]
need to check in detail, the version 6.3.1 is getting compiled, the 6.9.1 not.

**Comment by bsrdjan** [comment]
fixed by v0.1.6
