### ISSUE TITLE
is there a simple working example? 

### ISSUE THREAD

**Issue by sas10x** [SAP/node-rfc#205]
Hello Guys,

Is there a simple working example?

Where it has the basic needs?

Even bapi_salesorder_getlist example.

Where do you put the .ini file?

Thanks.

**Comment by bsrdjan** [comment]
Simple example can be found in [README#getting-started](https://github.com/SAP/node-rfc#getting-started)

More examples are here, also the Sales Order, incl. getlist bapi.

`sapnwrfc.ini` default location is documented here and can be changed as described.

**Comment by sas10x** [comment]
Thank you so much sir! Got it working now.
