### ISSUE TITLE
Question: Can you convert a program associated to a tcode to BAPI?

### ISSUE THREAD

**Issue by sas10x** [SAP/node-rfc#208]
Sorry for my question. Can't find the answer on the internet. Can you convert a program associated to a tcode to BAPI? I'm not an abap. Thank you.

**Comment by bsrdjan** [comment]
There is no automatic / generic converter. Some tcodes already run on BAPIs, some not at all, some partly. 

In general, ABAP developer can check which BAPIs are already available and which logic shall be "wrapped" into into Remote Enabled Function Module (RFM), providing a consistent business object (BO) API: select, read, update, create + BO specific actions like install, dismantle of Equipment. Some more info: 

- [SAP/fundamental-tools/doc/app.md#abap-api](https://github.com/SAP/fundamental-tools/blob/main/doc/app.md#abap-api)
- [SAP/fundamental-tools/doc/exposure#business-logic-exposure](https://github.com/SAP/fundamental-tools/tree/main/doc/exposure#business-logic-exposure)
