### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by vyking60** [SAP/node-rfc#210]
I have installed SAP RFC SDK 750 on win X64. All post installation checks are OK, till loading node-rfc modules.
Copying nwrfcsdk\lib files (dll,...) to widows\system32 also didn't help

Environment looks OK:
C:\Users\si4uoh>@echo off
findstr Patch "%SAPNWRFC_HOME%\lib\sapnwrfc.dll"
750 Patch Level 7

Also PATH is OK

STARTRFC returns OK response form target SAP system (SAP system ID , netweaver version,...)

BUT    node -p "require('node-rfc')"       returns:
```shell
PS C:\_Data\_DEVELOPMENT\Node\saprfc> node -p "require('node-rfc')"
C:\_Data\_DEVELOPMENT\Node\saprfc\node_modules\node-rfc\lib\wrapper\noderfc-bindings.js:45
    throw ex;
    ^

Error: The specified module could not be found.
\\?\C:\_Data\_DEVELOPMENT\Node\saprfc\node_modules\node-rfc\lib\binding\sapnwrfc.node

 The SAP NW RFC SDK could not be loaded, check the installation: https://github.com/SAP/node-rfc/blob/master/doc/installation.md#sap-nwrfc-sdk-installation
environment: {
  "platform": {
    "name": "win32",
    "arch": "x64",
    "release": "10.0.15063"
  },
  "env": {
    "SAPNWRFC_HOME": "C:\\Program Files\\SAP RFC SDK 750\\nwrfcsdk",
    "RFC_INI": "",
    "nwrfcsdk_lib_on_path": true
  },
  "versions": {
    "node": "14.16.1",
    "v8": "8.4.371.19-node.18",
```

How I can find where the problem is?

**Comment by bsrdjan** [comment]
Is it maybe running on Microsoft IIS: https://github.com/SAP/node-rfc/issues/139 ?

How is node-rfc installed? Locally/globally, using `npm install` or built from source?

**Comment by bsrdjan** [comment]
If nothing of above helps, the `procmon` can help find the missing part: https://github.com/SAP/node-rfc/issues/127#issuecomment-600020359

**Comment by vyking60** [comment]
Thanks for quick response!
IIS is not used. I am working directly in VSCode
C++ 2013 is installed - even both x386 and X64
node-rfc is installed with npm locally. 
During debugging I see that exception is catched in noderfc-bindings.js on line 36:

    exports.noderfc_binding = noderfc_binding = require("../binding/sapnwrfc");

And I see file sapnwrfc.node in bindings folder.

How can I get help procman?

**Comment by bsrdjan** [comment]
procman can trace the DLLs loading chain, to find out which DLL exactly fails. Example: https://github.com/SAP/node-rfc/issues/127#issuecomment-600020359

The VSCode itself does not matter but the re-distributable is important (Add/Remove Programs screenshot):

<img width="518" alt="Screenshot 2021-04-15 at 14 32 49" src="https://user-images.githubusercontent.com/1697847/114869785-b0957580-9df7-11eb-985f-e7dd2ff5a960.png">

If x86 not needed, best remove it and/or try to re-install the re-distributable.
 
You can trace runtime info before exception, adding something like this in `node_modules/node-rfc/lib/wrapper/noderfc-bindings.js`
```node
// verify SAP NWRFC SDK is on PATH
console.log(process.env.PATH)
try {
    exports.noderfc_binding = noderfc_binding = require("../binding/sapnwrfc");
}
```

Could you please post the output of:

```shell
dir %SAPNWRFC_HOME%\lib
```

**Comment by vyking60** [comment]
Visual C+ x386 is uninstalled;  
Visual C++ 2013 X64 is  still installed

Console.log of PATH and SAPNWRFC_HOME before  exports.noderfc...:
![image](https://user-images.githubusercontent.com/82108033/114883406-2eac4900-9e05-11eb-89fc-ff63de5eab37.png)

dir %SAPNWRFC_HOME%\lib     from TERMINAL node app folder:   Variable not evaluated!!
![image](https://user-images.githubusercontent.com/82108033/114883514-47b4fa00-9e05-11eb-8f2e-de086afa5beb.png)

dir     ​from Command prompt; 
![image](https://user-images.githubusercontent.com/82108033/114883786-834fc400-9e05-11eb-88bd-6e535ea53b8b.png)

**Comment by bsrdjan** [comment]
> `dir %SAPNWRFC_HOME%\lib` from TERMINAL node app folder: Variable not evaluated!!

The PowerShell syntax is `dir $env:SAPNWRFC_HOME\lib`, should be fine

The NWRFC SDK looks like correct 64 bit version, no idea what else to check. 

Perhaps to try with another Windows user or fresh new Windows installation. C++ redistributable re-installations do not always work as expected. Some users reported in Issues that only re-installation helped.

Or trace with procmon first.

**Comment by vyking60** [comment]
Reinstallation would be the last option.
I played with procmon and created one file. 
Can you check it if there is anything to see. Otherwise I would need some help to produce usefull one
[Logfile.zip](https://github.com/SAP/node-rfc/files/6324775/Logfile.zip)

**Comment by vyking60** [comment]
Problem solved. Thanks for help, Srdjan.
(Re)Installation of C++ Build tools  helped (MSVC 14.28)
