### ISSUE TITLE
how integrate node-rfc inside of @ui5 openui5

### ISSUE THREAD

**Issue by t82990582** [SAP/node-rfc#213]
Can i use node-rfc inside openui5, i hace issues integrating with Shims in yaml file. which is the js file. Failed to load component for container container - Error: failed to load 'resource/lib/wrapper/sapnwrfc-client.js' from ../node_modules/node-rfc/lib/wrapper/sapnwrfc-client.js: script load error

**Comment by bsrdjan** [comment]
Node-rfc is server side module, not supported inside web browsers. The integration with openui5 works the same way like with ui5-react and other ui frameworks: https://github.com/SAP/fundamental-tools
What would be advantage of direct (browser) integration?
