### ISSUE TITLE
Queuing requests

### ISSUE THREAD

**Issue by PatroxGaurab** [SAP/node-rfc#216]
Is it possible to add the requests coming from NodeJS to RFC in a queue?

**Comment by bsrdjan** [comment]
In general yes and the solution depends on what kind of queue is needed. Can you share some more info on use-case ?

RFC calls sequencing and scheduling can be added at application level on NodeJS client side. That is independent of `node-rfc` and 3rd party libraries cam be used.

Transactional integrity queues are currently not supported by `node-rfc`. These are supported by SAP NWRFC SDK and API is not exposed in `node-rfc` That would be a feature request for node-rfc and here are some references:

- [NW RFC SDK Part 3: Advanced Topics](http://go.sap.com/docs/download/2016/09/1a831fe1-8a7c-0010-82c7-eda71af511fa.pdf)

- [SAP NW RFC SDK ProgrammingGuide - Transactional RFC Client, pg. 39](https://support.sap.com/content/dam/support/en_us/library/ssp/products/connectors/nwrfcsdk/NW_RFC_750_ProgrammingGuide.pdf)

**Comment by PatroxGaurab** [comment]
Thanks for sharing, basically we are running one application using node-rfc in production. Due to month end heavy load, it sometimes gets max connection exceeding error. The solution that is coming to our mind is using a queue, similar to what we are using in case of DB operation or communication between microservices. If you have any other suggestive solutions, you can let me know. 
And also everytime RFCLibError of connection exceeds arise, the PM2 restarts itself, resulting in temporary disruption of the service.

**Comment by bsrdjan** [comment]
What the PM2 stands for?

[Connection Pool](https://github.com/SAP/node-rfc/blob/main/doc/api.md#connection-pool) might help restrict the total number of parallel connections by implementing new `maxConnections` config parameter for example. Max connections exceeded would be in that case raised by the Pool, before RfcLibError raised on ABAP side. But also with this addition some sort of queue would be needed at application level, to "park" the RFC call until the Pool is free again. Would that be of any help?

**Comment by PatroxGaurab** [comment]
PM2 a process manager for NodeJS.
We have been using connection pool, will try tweaking the connection parameters and check.
For the application level queue, are you suggesting put pool.acquire, or client.call which one in the queue?
Also how does the application know when the pool is free to accept calls? can you pls throw some lights on it

**Comment by bsrdjan** [comment]
Tweaking pool parameters will not help. There is no limit in Pool how many connections could be opened (`maxConnections` parameter is not implemented) and no events from Pool when it is empty or full. That could be the solution in the future.

An RFC call from Node to ABAP is JS callback or promise. I would suggest application level queue for handling desired number of callbacks or promises.
