### ISSUE TITLE
Call RFC(BAPI) from AWS Lambda using NodeJS

### ISSUE THREAD

**Issue by public2public2** [SAP/node-rfc#220]
Dear Srdjan,

I hope my note make you happy & safe!

I have one request, can you please explain how to call SAP BAPI using NodeJS and AWS lambda.
I have gone through your material shared earlier in [https://github.com/sap/node-rfc]

But I don't know from where I should start?

What I have understood so far....

1. - Create nodejs project
2. - Install node-rfc module along with other dependency
3. - RFC port of the backend must be exposed public to internet
4. - Download the LINUX ON X86_64 64BIT version( Because Lambda run on Linux AMI)
5. - SAP connectivity from your AWS Lambda- Both should be hosted on same premises
6. - AWS Lambda layers- A Lambda Layer is a ZIP archive that contains libraries.
7. - Docker container- not much understood
8. - Create sapnwrfc.ini- for server connection details
9. - Create a program to call RFM(Remote Function Module) with BAPI name

Please help me start and guide me step by step so I can deploy lambda to call BAPI using nodeJS

Thanks in Advance.

**Comment by bsrdjan** [comment]
I am not using Lambda and can't provide more detailed steps. It should work just like from on-premise Linux.

If on-premise system is S4HANA >= 1909 the new Websocket RFC protocol can be used, over HTTPS port exposed in internet. SAP Business Connector is required otherwise.

The detailed configuration can be provided as a consulting service, if needed.

**Comment by gimapei** [comment]
I think, you can't using lambda. there are no netweaver sdk. lambda doesn't support netweaver sdk. 
that's why you can't using node-rfc on lambda service.

**Comment by frumania** [comment]
It is working, but the setup is slightly more complex as SAP is not shipping binaries :(.
See here
https://github.com/SAP/node-rfc/issues/121
https://www.youtube.com/watch?v=rhY4jVtl0k8&t=39s

**Comment by bsrdjan** [comment]
Thanks for the input. Potential users shall consider that node-rfc cloud to on-prem connections via SAP Cloud Connector are not supported yet: #121
