### ISSUE TITLE
Question: Cancel connection

### ISSUE THREAD

**Issue by Berdmanfolk** [SAP/node-rfc#231]
Hello @bsrdjan!
Can you please to clarify how to use Client cancellation.
I was compile for last version 2.5.1. but now when I try to call method Cancel() I gett error that method is not found.
In devetools of browser I don see this method:
```
this: Islet
_client: Client
_alive: (...)
_config: (...)
_connectionHandle: (...)
_id: (...)
_pool_id: (...)
[[Prototype]]: Object
close: ƒ close()
connectionInfo: ƒ connectionInfo()
constructor: ƒ Client()
invoke: ƒ invoke()
open: ƒ open()
ping: ƒ ping()
release: ƒ release()
resetServerContext: ƒ resetServerContext()
_alive: (...)
_config: (...)
_connectionHandle: (...)
_id: (...)
_pool_id: (...)
get _alive: ƒ ()
get _config: ƒ ()
get _connectionHandle: ƒ ()
get _id: ƒ ()
get _pool_id: ƒ ()
[[Prototype]]: Object
```
I was try also to get timeout by ​event is using such code:
But timeout is not  arise.
```
	try {
		Rfc = require('./sapnwrfc.node').Client;
		const client = new Rfc(curconnection, {timeout: 3});

		client.open(function (err) {
			if (err) {
				reject(err);
			} else { 
				resolve(client);
			}
		});													
	} catch {

	}	
```
Can you pleaswe clarify what I do wrong?

**Comment by bsrdjan** [comment]
A longer RFC call can be simulated by calling `RFC_PING_AND_WAIT` ABAP function module. It will wait for a number of seconds, provided in input parameter SECONDS, and return.

The timeout can be tested by calling this function module with `SECONDS: 5` for example and setting connection timeout to 3 seconds. After 3 second the timeout event will be fired, as shown in [direct-callback.mjs](https://github.com/SAP-samples/node-rfc-samples/blob/main/integration/clientConnectionCancel/direct-callback.mjs) source code example.  Few more examples are provided in a [parent folder](https://github.com/SAP-samples/node-rfc-samples/tree/main/integration/clientConnectionCancel) 

The `client.cancel()` can be tested in a similar way. Call `RFC_PING_AND_WAIT` and while waiting for the call to complete, call the `cancel()` method, exposed at addon, pool or client level. Examples can be found in [unit tests](https://github.com/SAP/node-rfc/tree/main/test/client/cancel), like [client.cancel.spec.js](https://github.com/SAP/node-rfc/blob/main/test/client/cancel/client.cancel.spec.js)

Hope this helps further.

**Comment by Berdmanfolk** [comment]
I think, I understand - we are talking about when the connection to the sap system has already taken place.
And if it is possible to interrupt the connection when the connection to the stand-alone system has not yet been completed, but due to some network problems it takes a long time?

**Comment by bsrdjan** [comment]
Please re-open if needed.

**Comment by Berdmanfolk** [comment]
Oh, It is need

**Comment by bsrdjan** [comment]
Only opened connection can be cancelled. The cancel() method requires connection handle and the handle is known only after connection opened. How would you like to use cancellation, can you describe the usage scenario?
