### ISSUE TITLE
Connection count limited to 4

### ISSUE THREAD

**Issue by MrSJS** [SAP/node-rfc#232]
I only get 4 concurrent Connections to SAP. Is there a setting for this? If I make an rfc call five times, the fifth has to wait until one of the four has finished. Therefore, the fifth needs a minute longer.

```
    var newPool = require('node-rfc').Pool;
    console.log("new");
    var pool = new newPool({ 
        connectionParameters: {
            user: "RFC_USER",  //your credentials
        	passwd: "passwd",
        	ashost: "sap.ppp.local",
    	    sysnr: "00",
        	client: "100",
    	    lang: "EN"
        }
        , clientOptions: {stateless:true}
    });

var connect = function(){
	pool.acquire().then(client => {
	
		var date = new Date();
		var start = ("0" + date.getHours() ).slice(-2) + ":" + ("0" + date.getMinutes()).slice(-2) + ":" + ("0" + date.getSeconds()).slice(-2);

		console.log("start ping: " + start);
    
		//(only 4 calls parallel?)
		client.call("SPTA_RFC_PING_AND_WAIT", {"SECONDS": 60}).then(res => {
					    
			pool.release(client);

			console.log(res);
		
			var date = new Date();
			var end = ("0" + date.getHours() ).slice(-2) + ":" + ("0" + date.getMinutes()).slice(-2) + ":" + ("0" + date.getSeconds()).slice(-2);

			console.log("from: " + start + " end: " + end);
		
		}).catch(err => {
			console.error("[sapRFC:call] ", err);
			pool.release(client);
		});
	
	}).catch(err => {
		console.error("[sapRFC:pool.aquire] ", err);
	});
};

// 5 requests
connect();
connect();
connect();
connect();
connect();
```

![image](https://user-images.githubusercontent.com/37208686/131102896-fedfc73f-9723-42c7-aeaa-10a198db6197.png)

**Comment by MrSJS** [comment]
It seems like Node.js can't use its Asynchronous system APIs for node-rfc. Asynchronous system APIs are used by Node.js whenever possible, but where they do not exist, libuv's threadpool is used to create asynchronous node APIs based on synchronous system APIs.

https://nodejs.org/api/cli.html#cli_uv_threadpool_size_size

**Comment by bsrdjan** [comment]
> It seems like Node.js can't use its Asynchronous system APIs for node-rfc. Asynchronous system APIs are used by Node.js whenever possible, but where they do not exist, libuv's threadpool is used to create asynchronous node APIs based on synchronous system APIs. And libuv is not thread safe.

Correct, the Node.js Worker Pool async API is using libuv to offload/displace operations of C++ add-ons (like node-rfc) from the event loop: 

https://nodejs.org/en/docs/guides/dont-block-the-event-loop/

Other async API could start and notify on RFC call completion but would also block the main loop. The current libuv maximum thread pool size is 1024. Would it be enough for your scenario as well?

**Comment by MrSJS** [comment]
Tank you very much. Of course, 1024 would be enough for my scenario. I think it would be ideal if node-rfc could avoid the fallback to libuv. So is there no way that node-rfc can use the asynchronous system APIs from Node.js for this project?

**Comment by bsrdjan** [comment]
I don't see the possibility to use something else instead of libuv but we can also ask the Node.js team. libuv is listed as [Node.js standard dependency](https://nodejs.org/en/docs/meta/topics/dependencies/#libuv) and I am not aware of alternatives.

Which problem would be solved by not using libuv?

**Comment by MrSJS** [comment]
In relation to the [link](https://nodejs.org/en/docs/guides/dont-block-the-event-loop/) you sent:

> You can create and manage your own Worker Pool dedicated to computation rather than the Node.js I/O-themed Worker Pool. The most straightforward ways to do this is using [Child Process](https://nodejs.org/api/child_process.html) or [Cluster](https://nodejs.org/api/cluster.html).

and...

> I/O-intensive tasks involve querying an external service provider (DNS, file system, etc.) and waiting for its response. While a Worker with an I/O-intensive task is waiting for its response, it has nothing else to do and can be de-scheduled by the operating system, giving another Worker a chance to submit their request.

and...

> If you rely on only one Worker Pool, e.g. the Node.js Worker Pool, then the differing characteristics of CPU-bound and I/O-bound work may harm your application's performance.
> 
> For this reason, you might wish to maintain a separate Computation Worker Pool.

That would of course be very nice if in our case a thread with an RFC call waits for its response that this thread could process another RFC call in the meantime, as described above.

**Comment by bsrdjan** [comment]
Reading the link it should be indeed doable.

Considering efforts required for analysis, fundamental re-factoring and testing, the development is unlikely to start any time soon. 

Using the environment variable the bottleneck is removed. If there is a business case or other advantages, to justify development efforts?

**Comment by MrSJS** [comment]
well, because the architecture of Node.js is like that.

> Node.js scales well, sometimes better than more heavyweight approaches like Apache. The secret to the scalability of Node.js is that it uses a small number of threads to handle many clients. If Node.js can make do with fewer threads, then it can spend more of your system's time and memory working on clients rather than on paying space and time overheads for threads (memory, context-switching). But because Node.js has only a few threads, you must structure your application to use them wisely.

> You may wish to distinguish between CPU-intensive and I/O-intensive tasks because they have markedly different characteristics.
If you rely on only one Worker Pool, e.g. the Node.js Worker Pool, then the differing characteristics of CPU-bound and I/O-bound work may harm your application's performance.
For this reason, you might wish to maintain a separate Computation Worker Pool.

And finally, for analytical purposes, I don't know whether uv_threadpool_size is big enough at all times during the run time. If it is not big enough, Node.js blocks all other activities in the meantime. That could unnecessarily cost performance unnoticed. And if I set too many threads, according to other articles on the net, it could also cost performance. Some articles write that we should only use as many threads in Node.js as we have logical cores in our hardware ... 
And that would currently not be enough, because each parallel RFC call needs an extra thread.

https://dev.to/johnjardincodes/increase-node-js-performance-with-libuv-thread-pool-5h10

**Comment by bsrdjan** [comment]
Yes, it might make sense and should be investigated in detail. Considering current priorities and capacity allocated for node-rfc project maintenance, the re-factoring is unlikely to start soon. 

If the inquiry is related to customer requirement or similar business case please contact me via LinkedIn. Pull request is welcome as well.

**Comment by bsrdjan** [comment]
I will be on vacation till end of September but feel free to discuss with Node.js team, responding to above mentioned issue.

This issue stays open until the documentation is updated.

**Comment by MrSJS** [comment]
Ok thank you very much.

**Comment by bsrdjan** [comment]
Per https://github.com/nodejs/node-addon-api/issues/1060 outcome we keep the libuv.
