### ISSUE TITLE
Exception UCON RFC Rejected

### ISSUE THREAD

**Issue by AnkitSomani22** [SAP/node-rfc#233]
Dear Srdjan,

While using Websocket RFC connection for QM7 system we are getting below exception
"UCON RFC Rejected; CPROG:node DEST ...".

With same connection parameters i tried to call abap-api-tools library with that I am able to fetch BAPI parameters but same is not working while execution of BAPI.
BAPI Name : "STFC_STRUCTURE"

Websocket RFC parameters are set as mentioned in [authentication.md](https://github.com/SAP/node-rfc/blob/main/doc/authentication.md#websocket-rfc) document( user/password).

**Comment by bsrdjan** [comment]
Hello Ankit,

it looks like Unified Connectivity (UCON) is configured in ABAP system and authorizations are not configured in UCON to call affected BAPI from external clients (another ABAP system, node app ...)

Here SAP OSS note describing required configurations:

https://userapps.support.sap.com/sap/support/knowledge/en/2616341

Kind regards, Srdjan

**Comment by AnkitSomani22** [comment]
Thank You Srdjan,

Link has explanation of above issue.
