### ISSUE TITLE
Question - Use of node-rfc with HANA Cloud Connector

### ISSUE THREAD

**Issue by NilsFrkal** [SAP/node-rfc#24]
Hi experts,

We were hoping that you could help us with some questions we have around the usage of this library and some more generic questions around the usage of SAP HANA Cloud connector and destinations.

We have deployed a nodejs app using the SAP HANA Cloud Platform, Starter Edition for Cloud Foundry Services (Beta). We have also installed and configured the cloud connector on our on-premise ABAP system and corresponding settings on HCP. We would now like to call the RFCs on the ABAP backend from our nodejs app.

Questions:

1. Is it possible to consume the connector destinations directly from our nodejs app? There is a JCo API for Java applications but we could not find any documentation to use the connector destinations from nodejs.

2. Using the node-rfc library, what is the relation to the HANA Cloud connector? Can this library be used in combination with the connector or will this establish a direct connection to the ABAP system i.e. the connector is actually bypassed?

3. How can the NWGW SDK (prerequisit) be deployed/installed within the cloud foundary instance? Do we need to SSH into the instance and do this manually or is there an automated way to do this?

Thank you very much.

Best regards, Nils

**Comment by bsrdjan** [comment]
Hi Nils,

I try to help clarify 1. and 2. Regarding 3. I would suggest asking in sap cloud foundry forum.

1.  SAP HANA Cloud Connector, as described on its [help page](https://help.hana.ondemand.com/help/frameset.htm?e6c7616abb5710148cfcf3e75d96d596.html), supports only Java runtime environment currently. The consumption from nodejs app is not possible, unless eventually with getting the nodejs to run on JVM somehow. That might be starting from JVM8 possible but not practical (simple), for the most of nodejs projects where cost considered.

2. There is not relation at all. The node-rfc library can't be used in combination with SAP HANA Cloud Connector.

Hope this helps.

Best regards,
srdjan
