### ISSUE TITLE
NodeJS Process Termination w/o exception when rfmParams contains empty string key in client.call

### ISSUE THREAD

**Issue by tvormweg** [SAP/node-rfc#242]
**Describe the bug**
Nothing urgent, but when you pass an object with an empty string key in it for the parameter rfmParams to client.call (see screenshot) it will terminate the NodeJS Process without throwing an exception.

**To Reproduce**
Installed via npm locally. Test script:
``` js
const noderfc = require("node-rfc");
const pool = new noderfc.Pool({ connectionParameters: { 
    dest: "MME", // sap test system connection params
    USER:"BPINST",
    PASSWD:"Welcome1",
    ASHOST:"",
    SYSNR:"00",
    CLIENT:"100",
    LANG:"EN",
} });

(async () => {
    try {
        // get a client connection instance
        const client = await pool.acquire();
        const result = await client.call("RFC_PING", {
            "": ""
        })
        console.log(result);
    } catch (err) {
        // connection and invocation errors
        console.error(err);
    }
})();
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11425915/144624243-686a4377-6f47-4857-9544-2763d922acba.png)

**Environment**
![image](https://user-images.githubusercontent.com/11425915/144624582-1dcbc1d9-f026-4028-96d8-4653c606707f.png)

**Additional context**

**Comment by bsrdjan** [comment]
Thank you for reporting this bug. It will be fixed in next release.
