### ISSUE TITLE
Question on licensing

### ISSUE THREAD

**Issue by uxkjaer** [SAP/node-rfc#245]
I've got a more general question in regards to license.
I understand that the node-rfc package is licensed under the apache license, but the binaries used to call the RFC is still not open source and under the developer license. 

If I was to build a product to distribute to SAP customers and they called the RFC with a communication user, would that be a breach of license as the customer themselves would have the right for the product?

**Comment by mtolksdorf** [comment]
Redistribution of NW RFC SDK is not allowed and would be a breach of the license. See also https://support.sap.com/connectors#section_561121760

Best regards,
Markus

**Comment by bsrdjan** [comment]
Please reopen if more clarifications needed
