### ISSUE TITLE
ARM platform support: 'uv.h' file not found

### ISSUE THREAD

**Issue by end0cr1ne** [SAP/node-rfc#249]
**Describe the bug**
In file included from /Users/.../node_modules/node-rfc/src/Client.cc:5:
/Users/.../node_modules/node-rfc/src/Client.h:9:10: fatal error: 'uv.h' file not found
#include <uv.h>
^~~~~~
1 error generated.

**To Reproduce**
run npm install node-rfc on an M1 mac(not sure if that matters)

Describe steps to reproduce the behavior, including the test script.

**Screenshots**

**Environment**
 - MODULE_NOT_FOUND`

**Additional context**

**Comment by bsrdjan** [comment]
Which node version and architecture do you use? Could you please post the full console log?

The node-rfc requires SAP NWRFC SDK, which is not supported on arm64 architecture: https://launchpad.support.sap.com/#/notes/2573790

The node-rfc is therefore neither tested, nor supported on arm64. Perhaps you can make it work on M1 like described here: https://www.jurnalanas.com/node-js-mac-m1/

**Comment by ria92** [comment]
Node version: 14.18.3
Architecture: arm64

**Comment by bsrdjan** [comment]
is clear then, arm64 is not supported. Did you try the above mentioned workaround?

**Comment by elinanna** [comment]
Hi @bsrdjan ,

I did try the work-around, but got the following error:
./rfcexec
dyld[41770]: Library not loaded: @loader_path/libsapnwrfc.dylib
  Referenced from: /usr/local/sap/nwrfcsdk/bin/rfcexec
  Reason: tried: '/usr/local/sap/nwrfcsdk/bin/libsapnwrfc.dylib' (no such file), '/usr/local/lib/libsapnwrfc.dylib' (no such file), '/usr/lib/libsapnwrfc.dylib' (no such file)

echo `strings $SAPNWRFC_HOME/lib/libsapnwrfc.dylib | grep "Patch Level"`
750 Patch Level 9
environment: {
  "platform": {
    "name": "darwin",
    "arch": "x64",
    "release": "21.2.0"
  },
  "env": {
    "SAPNWRFC_HOME": "/usr/local/sap/nwrfcsdk",
    "RFC_INI": ""
  },
  "versions": {
    "node": "16.14.0",
    "v8": "9.4.146.24-node.20",
    "uv": "1.43.0",
    "zlib": "1.2.11",
    "brotli": "1.0.9",
    "ares": "1.18.1",
    "modules": "93",
    "nghttp2": "1.45.1",
    "napi": "8",
    "llhttp": "6.0.4",
    "openssl": "1.1.1m+quic",
    "cldr": "40.0",
    "icu": "70.1",
    "tz": "2021a3",
    "unicode": "14.0",
    "ngtcp2": "0.1.0-DEV",
    "nghttp3": "0.1.0-DEV"
  }

**Comment by bsrdjan** [comment]
Feature request for ARM platform support by SAP NW RFC SDK

**Comment by elinanna** [comment]
> Running in the same problem. @elinanna Did you find a workaround?

Unfortunately not.

**Comment by bsrdjan** [comment]
Darwin on ARM is supported as of [node-rfc@2.7.1](https://github.com/SAP/node-rfc/releases/tag/v2.7.1)
