### ISSUE TITLE
Unable to Connect to SAP Logon - connection refused error

### ISSUE THREAD

**Issue by i353590** [SAP/node-rfc#250]
Hello,

I am facing the issue of connecting to the SAP S4 System using SAP GUI. I had created the S4 system from CAL Library, now from RDP also if I try it is not accessible, and the port is also not reachable.
I have created the system using CAL, and only I am able to access RDP, but not the system
S4 system in running on on-prem (newly created)
SAP GUI connection is failing, only the logon app I am able to launch.

![image](https://user-images.githubusercontent.com/66831161/153874326-d9a9d5e7-c15a-4437-abe6-0e9c218d5b77.png)

Please let me know if you want me to provide more info.

Thanks,
Shubham

**Comment by bsrdjan** [comment]
Please check if RFC connectivity is enabled in ABAP system: https://launchpad.support.sap.com/#/notes/460089

> I have created the system using CAL, and only I am able to access RDP, but not the system

Which RDP is accessed? Why RDP used when the system is on premise?

**Comment by i353590** [comment]
Hello,

RDP because it was a separate installation itself using CAL & the S4 was installed inside that system (RDP)

**Comment by bsrdjan** [comment]
Does the node RFC client is running within the same RFP landscape and did you check the above mentioned oss note ?

**Comment by i353590** [comment]
Hello,

I think the issue was with the DB, DB was not started due to some reason. I had tried to restart the system initially, that didn't help, but later the restart actually helped. the DB instance was working fine and then the ports were also reachable.

Thanks for your help :)

Kind Regards,
Shubham
