### ISSUE TITLE
stealth mode can't be disabled on my mac

### ISSUE THREAD

**Issue by vivianxh** [SAP/node-rfc#251]
Due to company policy, we are not about to disable the stealth mode, please see the terminal:

> ~ % sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode off
> Password:
> Firewall settings cannot be modified from command line on managed Mac computers.

So the step was failed to set. Then I tried the next stpes without stealthmode off.
I got another error when running [paths_fix.sh](https://github.com/SAP/PyRFC/blob/master/ci/utils/paths_fix.sh)

> nwrfcsdk % sudo ./paths_fix.sh
> Password:
> error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't open file: *.dylib (No such file or directory)
> error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't open file: *.dylib (No such file or directory)
> error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't open file: libicui18n.50.dylib (No such file or directory)

Please have a try on your company mac, maybe you will get the same error.
Is there any workaround to bypass the error?

**Comment by bsrdjan** [comment]
Which NWRFC SDK version are you using and why paths' fix needed?

**Comment by vivianxh** [comment]
Hi @bsrdjan 

NWRFC SDK version: nwrfc750P_8-80002761.
I followed the guide you provided in this repo, see the readme:
https://github.com/sap/node-rfc/blob/main/doc/installation.md#macos

Thanks,
Vivian

**Comment by bsrdjan** [comment]
The disabled stealth mode is not required any more, the requirement will be removed from the documentation.
