### ISSUE TITLE
CallBack data is incorrect

### ISSUE THREAD

**Issue by jedsada-sw** [SAP/node-rfc#253]
I have an issue when calling the function module, In SAP GUI **PERS_AVAIL** has data but node-rfc is return an empty array.

**SAP GUI**
![messageImage_1648634982308](https://user-images.githubusercontent.com/59214786/160808061-539010cc-4871-439d-8781-33a1422da1e2.jpg)

**node-rfc**
![Screen Shot 2565-03-30 at 5 28 15 PM](https://user-images.githubusercontent.com/59214786/160811464-6f6096b5-41bd-4b1a-b5eb-9f68fc590833.png)

**Comment by bsrdjan** [comment]
Most likely one or more input parameters have Conversion Exit (ALPHA Exit): [RFM call results differ from expected](https://github.com/SAP/node-rfc/blob/main/doc/troubleshooting.md#rfm-call-results-differ-from-expected)

**Comment by jedsada-sw** [comment]
Resolved. Thank you.
