### ISSUE TITLE
Passing Fields Parameter

### ISSUE THREAD

**Issue by ewcindia** [SAP/node-rfc#26]
We are facing an issue while passing multiple parameters for FIELDS:

`client.invoke('RFC_READ_TABLE', { QUERY_TABLE: 'AGR_1016', OPTIONS: [{ TEXT: "" }], FIELDS: [{ FIELDNAME: "PROFILE,AGR_NAME,PSTATE" }] }, function(err, res) { debugger; if (err) { throw err } console.log(res); }); });`

Getting exception code 5 'FIELD_NOT_VALID'. Please advise on how to pass multiple fields as a parameter to FIELDS. Also, we wish to extract data in JSON format, any help here is welcomed.

**Comment by bsrdjan** [comment]
Sorry for the late response and please consider that RFC_READ_TABLE is not recommended. IS support still needed?

**Comment by bsrdjan** [comment]
Closed due to inactivity

**Comment by junyichiu** [comment]
`
FIELDS: [
    { FIELDNAME: "PROFILE" },
    { FIELDNAME: "AGR_NAME" },
    { FIELDNAME: "PSTATE" }
]
`
