### ISSUE TITLE
Node RFC connection with ABAP is disconnected after 1 min. For that reason big data is not coming from the ABAP

### ISSUE THREAD

**Issue by sanjaysarkar1997** [SAP/node-rfc#265]
**Describe the bug**

**To Reproduce**
Describe how the `node-rfc` is installed, like locally or globally and using `npm install` or build from source.

Describe steps to reproduce the behavior, including the test script.

**Screenshots**

**Environment**
 - The output of `node -p "require('node-rfc').environment"`

**Additional context**

**Comment by sanjaysarkar1997** [comment]
Please help on that

**Comment by sanjaysarkar1997** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Describe how the `node-rfc` is installed, like locally or globally and using `npm install` or build from source.
> 
> Describe steps to reproduce the behavior, including the test script.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Environment**
> 
> * The output of `node -p "require('node-rfc').environment"`
> 
> **Additional context** Add any other context about the problem here.

please help

**Comment by bsrdjan** [comment]
node-rfc supports client or connection [timeout](https://github.com/SAP/node-rfc/blob/main/doc/usage.md#client-options), both inactive by default. If these options not used, ABAP server can also terminate RFC connection after 1 min, if configured that way. ABAP consultant shall check ABAP server settings, if connection timeout configured there.

Is the connection idle or the termination occurs during an ongoing RFC call?

Can you activate the RFC connection tracing, by setting RFC_TRACE connection parameter to "3", reproduce the issue and send the logs?

**Comment by bsrdjan** [comment]
Closed as no response
