### ISSUE TITLE
Package fails to install under NodeJS 16.17

### ISSUE THREAD

**Issue by benjamin-sieffert** [SAP/node-rfc#266]
**Describe the bug**
Installation of this package just fails in the prebuild-install step under node 16.17.

**To Reproduce**
Compare installation under 16.16 to 16.17. Should be pretty easy to reproduce, since it fails both locally for me (Arch Linux) and on the official GH Ubuntu runner (`ubuntu-latest`).
Note that there seems to be an abundance of sub-procs created and a lot of scripts named like `/tmp/dependencies-####.sh` are created.

**Screenshots**
From GH pipeline:
![ii-rfc](https://user-images.githubusercontent.com/109514252/188830285-24b7b046-574e-43c3-b366-a10d036b2e61.png)

From local installation attempt:
![ii-tmp](https://user-images.githubusercontent.com/109514252/188830624-68b02319-cfe8-4b89-9370-db98e053807e.png)

**Additional context**
This could as well be a NodeJS bug, but probably you have a better shot than me in digging into _what exactly_ is failing when trying to install under 16.17, and then filing a bug with NodeJS if applicable.

Best regards

**Comment by bsrdjan** [comment]
The node-rfc installation works fine with node 16.17.0 on ubuntu latest docker container.

Why do you think the issue is related to node-rfc? Can you share the full installation log?
