### ISSUE TITLE
RCF Server not able to reach javascript application 

### ISSUE THREAD

**Issue by KunalBurangi** [SAP/node-rfc#267]
I have created a JS project where i am creating a RFC server.
In SAP system i have created a RFC. 
When i am Executing the RFC the function that i have added in rfc server is not getting executed. 

**To Reproduce**
Describe how the `node-rfc` is installed, like locally or globally and using `npm install` or build from source.

Describe steps to reproduce the behavior, including the test script.

**Screenshots**
This is my RFC
![image](https://user-images.githubusercontent.com/37167732/190107418-8a062641-2290-4706-b890-70fa751ab27e.png)
This is the execution result
![image](https://user-images.githubusercontent.com/37167732/190107538-ab782e6a-aeb7-4202-adb2-f284cc46320b.png)
![image](https://user-images.githubusercontent.com/37167732/190108653-7f5abe21-2a48-4765-b44a-26ba76fb6cd1.png)

What i want is after execution my JS code should reach...  and print the logs but it is not happening... 
![image](https://user-images.githubusercontent.com/37167732/190108873-b0c06984-d1b0-4f85-aedf-fd1ac149fa8a.png)

This is the output in my  vscode terminal
![image](https://user-images.githubusercontent.com/37167732/190134081-d11f0fc2-1b9a-4186-aee4-d5bcfb33f8c5.png)

**Comment by bsrdjan** [comment]
The server functionality is not supported, see https://github.com/SAP/node-rfc/issues/209#issuecomment-1262172717
