### ISSUE TITLE
Facing issues with node-rfc installation on windows

### ISSUE THREAD

**Issue by prajyot1708** [SAP/node-rfc#268]
@bsrdjan I am trying to install node-rfc on local machine. I installed Cmake and also downloaded node-rfc sdk. Copied it to C:\nwrfcsdk and also set its path in environment variable. but I am facing the below issue and I dont want to set ca=null / NODE_TLS_REJECT_UNAUTHORIZED = 0. Please find the below screenshot for reference.

![image](https://user-images.githubusercontent.com/26087423/192498223-aa900794-3528-4e54-89fb-1f793cb3b4c8.png)

**Comment by bsrdjan** [comment]
You can set 

```shell
npm config set strict-ssl false
```

or clone the repository and build from source

```shell
cd node-rfc
npm install
```

**Comment by bsrdjan** [comment]
is it working now?

**Comment by prajyot1708** [comment]
I am running it behind the corporate firewall and where I am unable to install it as mentioned in the screenshot.
