### ISSUE TITLE
Issues in make a request on a SAP function by an API running on docker

### ISSUE THREAD

**Issue by odevbruno** [SAP/node-rfc#274]
![image](https://user-images.githubusercontent.com/100795687/209718829-8a84d6a9-e554-48fe-9dd8-4bb0b1bf5821.png)

This problem only happens when I try to run in Docker, by local gulp it works normally

**Comment by bsrdjan** [comment]
Are SAP NWRFC SDK libraries for Linux installed on Docker system, as described here https://github.com/SAP/node-rfc/blob/main/doc/installation.md#linux ?

What is the output of `ldconfig -p | grep sap` ?

If you are using Windows Subsystem for Linux (WSL), SAP NWRFC SDK libraries which work on Windows host, do not work in WSL. SAP NWRFC SDK for Linux is required in WSL.

**Comment by odevbruno** [comment]
> Are SAP NWRFC SDK libraries for Linux installed on Docker system, as described here https://github.com/SAP/node-rfc/blob/main/doc/installation.md#linux ?
> 
> What is the output of `ldconfig -p | grep sap` ?
> 
> If you are using Windows Subsystem for Linux (WSL), SAP NWRFC SDK libraries which work on Windows host, do not work in WSL. SAP NWRFC SDK for Linux is required in WSL.

This problem happened, because template structure of API of enterprise where i work not allows
