### ISSUE TITLE
SAP GUI for Windows 770. Logon balancing error 88. 

### ISSUE THREAD

**Issue by dIPSEY** [SAP/node-rfc#283]
Hello! 
Could you please help?
Logon balancing error 88. 

![1](https://user-images.githubusercontent.com/33335153/228533793-a1a2a5bf-73bb-4551-a0e9-93b46b7c8ff8.png)

** Describe how the `node-rfc` is installed, like locally or globally and using `npm install` or build from source.
The output of `node -p "require('node-rfc').environment"` - if it helps to solve the problem than how to check that?

Thank you

**Comment by bsrdjan** [comment]
the issue is not related to node-rfc or this repostory

**Comment by dIPSEY** [comment]
> 

oh I see, sorry. Could you please advice what repository it might be related to?

**Comment by bsrdjan** [comment]
SAP Community eventually: https://community.sap.com/topics/gui
