### ISSUE TITLE
dev_rfc log file path

### ISSUE THREAD

**Issue by simonegaffurini** [SAP/node-rfc#288]
Hello, I can't seem to find documentation for this.
It looks like that when connecting to a system, a file called dev_rfc.log is created on the project directory.
I was wondering if there's a way to change that log file creation path to something else, and, if not, add it as a feature.

**Comment by bsrdjan** [comment]
Hello @simonegaffurini,

at the moment there is now way to de-activate or relocate this log file. It is written by SAP NWRFC SDK and required by other SAP NWRFC SDK consumers (eg. SAPGUI) to be written in current project working directory. 

The development will check if the solution can be provided for node-rfc and other open source consumers. 

There is a school holiday over here and some colleagues are on vacation and I hope to have an update in week or two.

**Comment by blumvit** [comment]
I achieved this by setting this environment variable: `RFC_TRACE_DIR`.

**Comment by bsrdjan** [comment]
yes, RFC_TRACE_DIR solves the issue, thanks @blumvit
