### ISSUE TITLE
RFC_COMMUNICATION_FAILURE

### ISSUE THREAD

**Issue by CodingQueries2023** [SAP/node-rfc#291]
On server I am getting the error RFC_COMMUNICATION_FAILURE and it is automatically trying to connect to our IP with PORT 3300, which is a wrong port. My correct PORT is 3629 but instead of 3629 it is trying to connect to 3300 and is getting failed to connect to. In my docker file I have mentioned the PORT 3629 and not 3300. Is there anything that you can suggest about the issue?

**Comment by bsrdjan** [comment]
Hello @CodingQueries2023,

docker port is irrelevant for RFC connection configuration. Please check similar questions
- https://github.com/SAP/PyRFC/issues/79
- https://github.com/SAP/node-rfc/issues/146
- https://github.com/SAP/PyRFC/issues/202
- https://github.com/SAP/PyRFC/issues/212
Regards,
Srdjan

**Comment by CodingQueries2023** [comment]
I talked to our cloud ops team and they checked and told me the server on which the node-rfc code is hosted is able to access the SAP server and there is no connectivity issue in it.  My server is ubuntu X86_64 and the SAP SDK I am using is Linux on X86_64 64 bit. But I am getting the following error:
<img width="596" alt="serverError" src="https://github.com/SAP/node-rfc/assets/129358704/4c77a930-2c9f-435d-afd7-5373c0d782af">

Could you please suggest how to debug or go about this issue

**Comment by bsrdjan** [comment]
Which connection parameters are you using and did you already test with niping:

- https://github.com/SAP/node-rfc/issues/10#issuecomment-165689192
- https://github.com/SAP/PyRFC/issues/45#issuecomment-293371975

**Comment by CodingQueries2023** [comment]
Hi @bsrdjan ,

I am using these parameters:
new nodeRfc.Pool({ connectionParameters: { dest: 'MME', ASHOST: 'IP',GWSERV:'3629',CLIENT:'200', PASSWD: password, USER: userid } });

Could you please let me know if there is any issue with the parameter or if need to change anything here.

**Comment by bsrdjan** [comment]
GWSERV is used for server connections. in combination with GWHOST, not ASHOST. I cannot help with connection parameters' details because it depends on your ABAP system settings. Connection parameters are documented in sapnwrfc.ini file, in SAP NW RFC SDK folder "demo". There you may find when and how to use which parameter. You can also check with your ABAP system admin. If you have access to SAPGUI client, you can use the same parameters used in SAPGUI client for your ABAP system.

**Comment by bsrdjan** [comment]
Please re-open if needed
