### ISSUE TITLE
npm install node-rfc : doesnt work 

### ISSUE THREAD

**Issue by shyamkumarc** [SAP/node-rfc#30]
Looks like the dependency libraries are pointing to a wrong address . the following github address is a dead link. And hence the installation of package fails 

node-pre-gyp ERR! Tried to download(404): https://github.com/sap/node-rfc/releas
es/download/0.1.10/rfc-v0.1.10-node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-rfc@0.1.10 and node@7.9.
0 (node-v51 ABI) (falling back to source compile with node-gyp)

**Comment by bsrdjan** [comment]
If the binary for the particular nodejs release not published, the installer falls back to building from source, just like your log excerpt is telling.

Does the build from source starts/complete in your case, what is exactly the issue?

**Comment by shyamkumarc** [comment]
I'm trying to install node-rfc and i'm getting this error as below , and the module installation fails .
I'm using node - v 7.9 ,  and npm v 4.2.

_```
_C:\Users\shyam.chelathur\yug>npm install node-rfc

> node-rfc@0.1.11 preinstall C:\Users\shyam.chelathur\yug\node_modules\.staging\
node-rfc-b791f563
> npm install node-pre-gyp

node-rfc@0.1.11 C:\Users\shyam.chelathur\yug\node_modules\.staging\node-rfc-b791
f563
`-- node-pre-gyp@0.6.32
  +-- mkdirp@0.5.1
  | `-- minimist@0.0.8
  +-- nopt@3.0.6
  | `-- abbrev@1.1.0
  +-- npmlog@4.1.2
  | +-- are-we-there-yet@1.1.4
  | | +-- delegates@1.0.0
  | | `-- readable-stream@2.3.2
  | |   `-- string_decoder@1.0.3
  | +-- console-control-strings@1.1.0
  | +-- gauge@2.7.4
  | | +-- aproba@1.1.2
  | | +-- has-unicode@2.0.1
  | | +-- object-assign@4.1.1
  | | +-- signal-exit@3.0.2
  | | +-- string-width@1.0.2
  | | | +-- code-point-at@1.1.0
  | | | `-- is-fullwidth-code-point@1.0.0
  | | |   `-- number-is-nan@1.0.1
  | | +-- strip-ansi@3.0.1
  | | | `-- ansi-regex@2.1.1
  | | `-- wide-align@1.1.2
  | `-- set-blocking@2.0.0
  +-- rc@1.1.7
  | +-- deep-extend@0.4.2
  | +-- ini@1.3.4
  | +-- minimist@1.2.0
  | `-- strip-json-comments@2.0.1
  +-- request@2.81.0
  | +-- aws-sign2@0.6.0
  | +-- aws4@1.6.0
  | +-- caseless@0.12.0
  | +-- combined-stream@1.0.5
  | | `-- delayed-stream@1.0.0
  | +-- extend@3.0.1
  | +-- forever-agent@0.6.1
  | +-- form-data@2.1.4
  | | `-- asynckit@0.4.0
  | +-- har-validator@4.2.1
  | | +-- ajv@4.11.8
  | | | +-- co@4.6.0
  | | | `-- json-stable-stringify@1.0.1
  | | |   `-- jsonify@0.0.0
  | | `-- har-schema@1.0.5
  | +-- hawk@3.1.3
  | | +-- boom@2.10.1
  | | +-- cryptiles@2.0.5
  | | +-- hoek@2.16.3
  | | `-- sntp@1.0.9
  | +-- http-signature@1.1.1
  | | +-- assert-plus@0.2.0
  | | +-- jsprim@1.4.0
  | | | +-- assert-plus@1.0.0
  | | | +-- extsprintf@1.0.2
  | | | +-- json-schema@0.2.3
  | | | `-- verror@1.3.6
  | | `-- sshpk@1.13.1
  | |   +-- asn1@0.2.3
  | |   +-- assert-plus@1.0.0
  | |   +-- bcrypt-pbkdf@1.0.1
  | |   +-- dashdash@1.14.1
  | |   | `-- assert-plus@1.0.0
  | |   +-- ecc-jsbn@0.1.1
  | |   +-- getpass@0.1.7
  | |   | `-- assert-plus@1.0.0
  | |   +-- jsbn@0.1.1
  | |   `-- tweetnacl@0.14.5
  | +-- is-typedarray@1.0.0
  | +-- isstream@0.1.2
  | +-- json-stringify-safe@5.0.1
  | +-- mime-types@2.1.15
  | | `-- mime-db@1.27.0
  | +-- oauth-sign@0.8.2
  | +-- performance-now@0.2.0
  | +-- qs@6.4.0
  | +-- safe-buffer@5.1.1
  | +-- stringstream@0.0.5
  | +-- tough-cookie@2.3.2
  | | `-- punycode@1.4.1
  | +-- tunnel-agent@0.6.0
  | `-- uuid@3.1.0
  +-- rimraf@2.5.4
  | `-- glob@7.1.2
  |   +-- fs.realpath@1.0.0
  |   +-- inflight@1.0.6
  |   +-- minimatch@3.0.4
  |   | `-- brace-expansion@1.1.8
  |   |   +-- balanced-match@1.0.0
  |   |   `-- concat-map@0.0.1
  |   +-- once@1.4.0
  |   `-- path-is-absolute@1.0.1
  +-- semver@5.3.0
  +-- tar@2.2.1
  | +-- block-stream@0.0.9
  | +-- fstream@1.0.11
  | | `-- graceful-fs@4.1.11
  | `-- inherits@2.0.3
  `-- tar-pack@3.3.0
    +-- debug@2.2.0
    | `-- ms@0.7.1
    +-- fstream-ignore@1.0.5
    +-- once@1.3.3
    | `-- wrappy@1.0.2
    +-- readable-stream@2.1.5
    | +-- buffer-shims@1.0.0
    | +-- core-util-is@1.0.2
    | +-- isarray@1.0.0
    | +-- process-nextick-args@1.0.7
    | +-- string_decoder@0.10.31
    | `-- util-deprecate@1.0.2
    `-- uid-number@0.0.6


> node-rfc@0.1.11 install C:\Users\shyam.chelathur\yug\node_modules\node-rfc
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/sap/node-rfc/releas
es/download/0.1.11/rfc-v0.1.11-node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-rfc@0.1.11 and node@7.9.
0 (node-v51 ABI) (falling back to source compile with node-gyp)

C:\Users\shyam.chelathur\yug\node_modules\node-rfc>if not defined npm_config_nod
e_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\no
de_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\shyam.chelathur\yug\node_modules\node-rfc>if not defined npm_config_nod
e_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\no
de_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\U
sers\shyam.chelathur\yug\node_modules\node-rfc\build\rfc\rfc.node --module_name=
rfc --module_path=C:\Users\shyam.chelathur\yug\node_modules\node-rfc\build\rfc )
  else (node "" configure --fallback-to-build --module=C:\Users\shyam.chelathur\
yug\node_modules\node-rfc\build\rfc\rfc.node --module_name=rfc --module_path=C:\
Users\shyam.chelathur\yug\node_modules\node-rfc\build\rfc )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_mod
ules\npm\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\grac
eful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:114:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--f
allback-to-build" "--module=C:\\Users\\shyam.chelathur\\yug\\node_modules\\node-
rfc\\build\\rfc\\rfc.node" "--module_name=rfc" "--module_path=C:\\Users\\shyam.c
helathur\\yug\\node_modules\\node-rfc\\build\\rfc"
gyp ERR! cwd C:\Users\shyam.chelathur\yug\node_modules\node-rfc
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallb
ack-to-build --module=C:\Users\shyam.chelathur\yug\node_modules\node-rfc\build\r
fc\rfc.node --module_name=rfc --module_path=C:\Users\shyam.chelathur\yug\node_mo
dules\node-rfc\build\rfc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\shyam.chelathu
r\yug\node_modules\node-rfc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)

node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\shya
m.chelathur\\yug\\node_modules\\node-rfc\\node_modules\\node-pre-gyp\\bin\\node-
pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\shyam.chelathur\yug\node_modules\node-rfc
node-pre-gyp ERR! node -v v7.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\
shyam.chelathur\yug\node_modules\node-rfc\build\rfc\rfc.node --module_name=rfc -
-module_path=C:\Users\shyam.chelathur\yug\node_modules\node-rfc\build\rfc' (1)
npm WARN yug@1.0.0 No description
npm WARN yug@1.0.0 No repository field.
npm WARN Error: EPERM: operation not permitted, scandir 'C:\Users\shyam.chelathu
r\yug\node_modules\tar-pack\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\Users\shyam.chela
thur\yug\node_modules\tar-pack\node_modules'
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\Users\\shyam.chelathur\\yug\\node_modules\\tar-pack\\node_
modules' }
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "node-rfc"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! node-rfc@0.1.11 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rfc@0.1.11 install script 'node-pre-gyp install --fa
llback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-rfc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-rfc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-rfc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\shyam.chelathur\AppData\Roaming\npm-cache\_logs\2017-06-27
T09_15_43_145Z-debug.log_
```_

**Comment by bsrdjan** [comment]
The nodejd addon build tool `node-gyp` requires python, which seems not be installed or not found on your system. Please check [node-gyp prerequisites](https://github.com/nodejs/node-gyp).

**Comment by bsrdjan** [comment]
close due to inactivity

**Comment by t82990582** [comment]
Can i use node-rfc inside openui5, i hace issues integrating with Shims in yaml file. which is the js file. 2021-05-02 09:06:23.388955 Failed to load component for container container - Error: failed to load 'resource/lib/wrapper/sapnwrfc-client.js' from ../node_modules/node-rfc/lib/wrapper/sapnwrfc-client.js: script load error

**Comment by bsrdjan** [comment]
@t82990582  could you please open new issue for this question, because not related to to this closed issue.
