### ISSUE TITLE
Error message when running npm i node-rfc

### ISSUE THREAD

**Issue by MartinStenzig** [SAP/node-rfc#300]
I am simply trying to do the first step and install node-rfc. My node environment is usually working well and I am using it to i.e. develop SAP CAP applications

I am running on a MAC M1 Max in a bash terminal and node version is: v18.16.0

Below you find the console log output
; npm i node-rfc
npm ERR! code 1
npm ERR! path /Users/martinstenzig/dev/MartinStenzig/noderfc/srv/node_modules/node-rfc
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! CXX(target) Release/obj.target/sapnwrfc/src/cpp/addon.o
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@18.16.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
npm ERR! gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/martinstenzig/.npm-global/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/martinstenzig/dev/MartinStenzig/noderfc/srv/node_modules/node-rfc/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/martinstenzig/.npm-global/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/martinstenzig/Library/Caches/node-gyp/18.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/martinstenzig/Library/Caches/node-gyp/18.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/martinstenzig/.npm-global/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/martinstenzig/Library/Caches/node-gyp/18.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/martinstenzig/dev/MartinStenzig/noderfc/srv/node_modules/node-rfc',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/cpp/addon.cc:5:
npm ERR! In file included from ../src/cpp/Client.h:9:
npm ERR! ../src/cpp/Log.h:6:10: fatal error: 'sapnwrfc.h' file not found
npm ERR! #include <sapnwrfc.h>
npm ERR!          ^~~~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/sapnwrfc/src/cpp/addon.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/martinstenzig/.npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 22.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/martinstenzig/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/martinstenzig/dev/MartinStenzig/noderfc/srv/node_modules/node-rfc
npm ERR! gyp ERR! node -v v18.16.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

**Comment by bsrdjan** [comment]
Hello Martin,

node-rfc is SAP Open Source but its dependency SAP NW RFC SDK is not and must be installed (copied) separately. Here the instructions: https://github.com/SAP/node-rfc#sap-nw-rfc-sdk-750-pl12

sapnwrfc.h include file is part of it and should be found after the SDK is in your system and SAPNWRFC_HOME env variable points to SDK files "root" folder (one level below include folder)

Regards, Srdjan

**Comment by MartinStenzig** [comment]
Thx, while I have you. How would/could you translate that into a SAP BTP - MTA based deployment so I can use the node-rfc library in i.e. a CAP project?

**Comment by bsrdjan** [comment]
Some deployment options are listed in [fundamental-tools](https://github.com/SAP/fundamental-tools/blob/main/doc/app.md#deployment-options), but partly in SAP VPN. Do you access there?

**Comment by MartinStenzig** [comment]
I unfortunately don't have access to SAP internal sites.

**Comment by Uday-Kiran** [comment]
Is your issue resolved?
Even I'm facing the issue while installing node-rfc ,seems logs are bit different. Someone kindly help here.

C:\Users\uday.kiran.ramaiah\Documents\IDP\Angular\Wireframe\final-project> npm i node-rfc        
npm ERR! code 1
npm ERR! path C:\Users\uday.kiran.ramaiah\Documents\IDP\Angular\Wireframe\final-project\node_modules\node-rfc
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build
npm ERR! addon.cc
npm ERR!   Log.cc
npm ERR!   nwrfcsdk.cc
npm ERR!   Client.cc
npm ERR!   Pool.cc
npm ERR!   Server.cc
npm ERR!   Throughput.cc
npm ERR!   win_delay_load_hook.cc
npm ERR! LINK : fatal error LNK1181: cannot open input file 'sapnwrfc.lib' [C:\Users\uday.kiran.ramaiah\Documents\IDP\Angular\Wireframe\final-project\node_modules\node-rfc\build\sapnwrfc.vcxproj]
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@20.7.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.4 found at "C:\Users\uday.kiran.ramaiah\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp info find VS using VS2022 (17.7.34031.279) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\uday.kiran.ramaiah\AppData\Local\Programs\Python\Python310\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\uday.kiran.ramaiah\\Documents\\IDP\\Angular\\Wireframe\\final-project\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\uday.kiran.ramaiah\\Documents\\IDP\\Angular\\Wireframe\\final-project\\node_modules\\node-rfc\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\uday.kiran.ramaiah\\Documents\\IDP\\Angular\\Wireframe\\final-project\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\uday.kiran.ramaiah\\AppData\\Local\\node-gyp\\Cache\\20.7.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\uday.kiran.ramaiah\\AppData\\Local\\node-gyp\\Cache\\20.7.0', 
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\uday.kiran.ramaiah\\Documents\\IDP\\Angular\\Wireframe\\final-project\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\Users\\\uday.kiran.ramaiah\\\AppData\\\Local\\\node-gyp\\\Cache\\\20.7.0\\\<(target_arch)\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\uday.kiran.ramaiah\\Documents\\IDP\\Angular\\Wireframe\\final-project\\node_modules\\node-rfc',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\uday.kiran.ramaiah\\Documents\\IDP\\Angular\\Wireframe\\final-project\\node_modules\\node-rfc\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe   
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\uday.kiran.ramaiah\Documents\IDP\Angular\Wireframe\final-project\node_modules\node-gyp\lib\build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\uday.kiran.ramaiah\\Documents\\IDP\\Angular\\Wireframe\\final-project\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\uday.kiran.ramaiah\Documents\IDP\Angular\Wireframe\final-project\node_modules\node-rfc
npm ERR! gyp ERR! node -v v20.7.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

**Comment by bsrdjan** [comment]
@Uday-Kiran, it looks like different issue. Could you please create new issue and post the verbose installation log there:

```shell
npm install node-rfc --loglevel verbose
```

**Comment by bsrdjan** [comment]
@MartinStenzig, for update on deployment options check `Deployment options` section of SAP community blog https://blogs.sap.com/2023/10/12/powerful-web-applications-with-old-and-new-abap-systems/

**Comment by MartinStenzig** [comment]
Thx, once I have some time I will try to assemble a cflinux4 compliant custom build pack and try to test it out.

**Comment by bsrdjan** [comment]
Hope this helps: https://blogs.sap.com/2023/10/26/abap-rfc-connectivity-from-btp-node.js-buildpack/
