### ISSUE TITLE
BAPI_HU_GETLIST not giving any output or error

### ISSUE THREAD

**Issue by vishalshingate** [SAP/node-rfc#301]
Description:-
BAPI_HU_GETLIST is giving me an empty response; on the sap GUI client, I'm able to see the HUKY is getting in response.

On SAP GUI this is result:-
![image](https://github.com/SAP/node-rfc/assets/44058055/4d882c31-2da7-4dc1-a97a-8b5799ff0558)

When I call the bapi from node_rfc client following the response I'm getting.

{
  "NOTEXT": "",
  "ONLYKEYS": "X",
  "HIGHESTLEVEL": [],
  "HUHEADER": [],
  "HUHISTORY": [],
  "HUITEM": [],
  "HUKEY": [],
  "HUNUMBERS": [],
  "HUOBJECTS": [
    {
      "OBJECT": "09",
      "OBJKEY": "000070001048"
    }
  ],
  "NOTFOUNDHUS": [],
  "RETURN": [
    {
      "TYPE": "",
      "ID": "",
      "NUMBER": "000",
      "MESSAGE": "",
      "LOG_NO": "",
      "LOG_MSG_NO": "000000",
      "MESSAGE_V1": "",
      "MESSAGE_V2": "",
      "MESSAGE_V3": "",
      "MESSAGE_V4": "",
      "PARAMETER": "",
      "ROW": 0,
      "FIELD": "",
      "SYSTEM": ""
    }
  ]
}

Steps to reproduce:-
Sap side:-
You have to create the process order by using the cor1 transaction. After that, you have to create a handling unit for that transaction using cowbpack transaction code.

We have used the following code to call the BAPI:-

function invokeRFC(client, rfcName, options, callback) {
    if (!client) return callback('Client not found')
    client.invoke(rfcName, options, function (err, res) {
        if (err) {
            return callback(err)
        }
        return callback(null, res)
    })
}

Input :-

rfcName:- BAPI_HU_GETLIST

options:-{
  "HIGHESTLEVEL": [],
  "HUHEADER": [],
  "HUHISTORY": [],
  "HUITEM": [],
  "HUKEY": [],
  "HUNUMBERS": [],
  "HUOBJECTS": [
    {
      "OBJECT": "09",
      "OBJKEY": "000070001048"
    }
  ],
  "NOTEXT": "",
  "NOTFOUNDHUS": [],
  "ONLYKEYS": "X",
  "RETURN": [
    {
      "FIELD": "",
      "ID": "",
      "LOG_MSG_NO": "",
      "LOG_NO": "",
      "MESSAGE": "",
      "MESSAGE_V1": "",
      "MESSAGE_V2": "",
      "MESSAGE_V3": "",
      "MESSAGE_V4": "",
      "NUMBER": "",
      "PARAMETER": "",
      "SYSTEM": "",
      "TYPE": ""
    }
  ]
}
The expected output should be the same as the SAP output, but we are not getting the expected result.

**Screenshots**
![image](https://github.com/SAP/node-rfc/assets/44058055/2e099bc8-9d0c-4b9b-9a6a-3b9d1b953b1b)

**Environment**
 I have used node_rfc 3.3.0 and 1.0.1 same result I'm getting.

Can someone please check why there is a difference in the output of SAPGUI and node_rfc call output?

**Comment by bsrdjan** [comment]
Could you please send the screenshot of the selection data used in SAPGUI, like how the key 000070001048 looks in HUOBJECTS table record in SAPGUI:
<img width="273" alt="Screenshot 2023-09-01 at 11 07 04" src="https://github.com/SAP/node-rfc/assets/1697847/34d49198-069c-4199-b304-48440b171991">

You can also set the external breakpoint at the beginning of BAPI_HU_GETLIST and see in ABAP debugger the difference in selection data. More info here: [RFM call results differ from expected](https://github.com/SAP/node-rfc/blob/main/doc/troubleshooting.md#rfm-call-results-differ-from-expected)

To check if ABAP User Exit used for selection field, you can use`abap` utility from [SAP/fundamental tools](https://github.com/SAP/fundamental-tools)

```shell
mkdir tmp
cd tmp
npm init -y
npm install abap-api-tools
# create sapnwrfc.ini file, here in tmp folder, with your system connection parameters
# like
# sysId
# DEST=mySysId
# USER=demo
# PASSWD=welcome
# ASHOST=coevi51
# SYSNR=00
# CLIENT=620
# LANG=EN

# get ABAP metadata of your function module
abap get yourSysMME BAPI_HU_GETLIST

# inspect fields with user exits, search for ALPHA in editor, or from command line
grep ALPHA api/bapi_hu_getlist.js
```
It would help find out if selection field(s) have user-exits and if leading zeroes for example should be sent from Node.js

**Comment by vishalshingate** [comment]
Hi @bsrdjan ,
Thanks for the quick response on this.

From sap GUI too, I'm providing the leading zeros.
![image](https://github.com/SAP/node-rfc/assets/44058055/2f9ef56c-ff2a-4bb0-b102-325a6ca97730)

**Comment by bsrdjan** [comment]
I tested with the latest and older node-rfc versions and in remote enabled debugger the selection data look the same, no matter if called from node-rfc or from SAPGUI:

<img width="835" alt="SAPGUI" src="https://github.com/SAP/node-rfc/assets/1697847/75fa3a1a-71d6-4ee1-9b1b-78da6aa2f79c">

I would suggest to get in touch with Functional Consultant to check if any configuration in the system has influence on RFC call of this particular BAPI.

If no progress could you please open customer incident for BC-MID-RFC-SDK component, provide the url of this issue there and also update this issue with the incident number.

Customer incident helps that more experts can analyse if needed. Next three weeks I am on vacation with very limited access to system.

**Comment by vishalshingate** [comment]
Hi @bsrdjan ,
1. You must first create the process order using the cor1 transaction code.
![image](https://github.com/SAP/node-rfc/assets/44058055/005e986f-e7dc-49b0-ae1f-e7ab84fdc30b)

2. Then, by using cowbpack transaction code, you have to create the handling units.
![image](https://github.com/SAP/node-rfc/assets/44058055/6420a6f9-e2ff-48f7-94d5-91d19463b19b)

3. Then you have to provide the 09 and the objkey = your process order number that you have created.

**Comment by vishalshingate** [comment]
Hi @bsrdjan If you want, we can set up a call and check the behavior in my system.

**Comment by vishalshingate** [comment]
Hi @bsrdjan 
The root cause of this issue is when we pass any return parameter. Suppose you are passing a message to this to return then in that at the line n0 89 getting some problem and it does not execute the 107 line that adds the hukey to hukey array.
![image](https://github.com/SAP/node-rfc/assets/44058055/f48e3c8a-c912-4f5e-ac4a-854a04df8c3b)

![image](https://github.com/SAP/node-rfc/assets/44058055/0d425905-a574-46e8-ae6f-775eac5887fe)
So I don't know if it is expected behavior or if it should not happen.

**Comment by bsrdjan** [comment]
The question can be discussed with Functional/ABAP Consultant. PyRFC support can help with technical and integration issues, related to Python RFC connections. For questions about particular BAPIs it is recommended to reach out to Functional Consultants or SAP ABAP Community.

**Comment by bsrdjan** [comment]
Which field exactly causes the issue when returned as empty string? Could you please provide the example of RETURN parameter with empty string, which causes the issue?

**Comment by vishalshingate** [comment]
From our node js code, we previously provided this input. Because of this, it's not giving us the expected output.

"RETURN": [
{
"FIELD": "",
"ID": "",
"LOG_MSG_NO": "",
"LOG_NO": "",
"MESSAGE": "",
"MESSAGE_V1": "",
"MESSAGE_V2": "",
"MESSAGE_V3": "",
"MESSAGE_V4": "",
"NUMBER": "",
"PARAMETER": "",
"SYSTEM": "",
"TYPE": ""
}
]

If you see line number 89, it's saying if the return is initialized, if we are passing the input to any field that array then this array will get initialized Because of that might following statements will not be executed.
![image](https://github.com/SAP/node-rfc/assets/44058055/ad46c72b-bfb0-4b86-ae4a-0b91ea390c69)

**Comment by bsrdjan** [comment]
The support here can't help with questions related to ABAP functional logic. Is there an issue with ABAP RETURN parameter which is not handled properly by node-rfc? Can you provide an example of such ABAP RETURN parameter and describe what the node-rfc issue exactly is?

I am asking because the above comment is not clear to me:

> The issue is happening because we are passing an empty string in the RETURN parameter array like the following:-

The example following this sentence shows non-empty structure and I am not sure which empty string is mentioned here?

**Comment by vishalshingate** [comment]
If we pass this to Return then it will not work

"RETURN": [
{
"FIELD": "",
"ID": "",
"LOG_MSG_NO": "",
"LOG_NO": "",
"MESSAGE": "",
"MESSAGE_V1": "",
"MESSAGE_V2": "",
"MESSAGE_V3": "",
"MESSAGE_V4": "",
"NUMBER": "",
"PARAMETER": "",
"SYSTEM": "",
"TYPE": ""
}
]

if we pass 
RETURN = [];
then it will work
