### ISSUE TITLE
 The specified module could not be found. node.napi.node

### ISSUE THREAD

**Issue by juanele121976** [SAP/node-rfc#303]
**Describe the bug**
Error: The specified module could not be found.
\\?\C:\BackendPDA\backend\node_modules\node-rfc\prebuilds\win32-x64\node.napi.node
environment: {
  "platform": {
    "name": "win32",
    "arch": "x64",
    "release": "10.0.17763"
  },
  "env": {
    "SAPNWRFC_HOME": "c:\\nwrfcsdk",
    "RFC_INI": "",
    "nwrfcsdk_lib_on_path": true
  },
  "versions": {
    "node": "18.18.0",
    "acorn": "8.10.0",
    "ada": "2.6.0",
    "ares": "1.19.1",
    "brotli": "1.0.9",
    "cldr": "43.1",
    "icu": "73.2",
    "llhttp": "6.0.11",
    "modules": "108",
    "napi": "9",
    "nghttp2": "1.55.0",
    "nghttp3": "0.7.0",
    "ngtcp2": "0.8.1",
    "openssl": "3.0.10+quic",
    "simdutf": "3.2.14",
    "tz": "2023c",
    "undici": "5.22.1",
    "unicode": "15.0",
    "uv": "1.46.0",
    "uvwasi": "0.0.18",
    "v8": "10.2.154.26-node.26",
    "zlib": "1.2.13.1-motley"
  }
}
******** dependencies***********
"dependencies": {
    "bcryptjs": "^2.4.3",
    "cors": "^2.8.5",
    "dotenv": "^16.3.1",
    "express": "^4.18.2",
    "express-graphql": "^0.12.0",
    "graphql": "^16.8.1",
    "jsonwebtoken": "^9.0.2",
    "moment": "^2.29.4",
    "mysql2": "^3.6.1",
    "node-rfc": "^3.3.0",
    "nodemailer": "^6.9.5",
    "twix": "^1.3.0",
    "typeorm": "^0.3.17",
    "uuid": "^9.0.1"
  },
  "devDependencies": {
    "@types/bcryptjs": "^2.4.4",
    "@types/cors": "^2.8.14",
    "@types/dotenv": "^8.2.0",
    "@types/express": "^4.17.18",
    "@types/jsonwebtoken": "^9.0.3",
    "@types/nodemailer": "^6.4.11",
    "@types/uuid": "^9.0.4",
    "ts-node-dev": "^2.0.0",
    "typescript": "^5.2.2"
  }

******system****
System:
    OS: Windows 10 10.0.17763
    CPU: (1) x64 Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz
    Memory: 4.34 GB / 8.00 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Managers:
    pip3: 23.2.1 - ~\AppData\Local\Programs\Python\Python311\Scripts\pip3.EXE
  Utilities:
    Curl: 8.0.1 - C:\Windows\system32\curl.EXE
  IDEs:
    VSCode: 1.83.1 - C:\Users\iusr_kpffact01\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Python: 3.11.6
  Browsers:
    Chrome: 118.0.5993.72
    Internet Explorer: 11.0.17763.2989

**Comment by bsrdjan** [comment]
I need some more info how to reproduce? Which statements/actions lead to error, can you copy & send here the console log?

Did you check [prerequisites](https://github.com/SAP/node-rfc#requirements) for Windows platform?

Did you try the [troubleshooting](https://github.com/SAP/node-rfc/blob/main/doc/installation.md#troubleshooting) and what was the outcome?

**Comment by juanele121976** [comment]
hello,
Thank you very much for the support, I installed Nodejs again, in addition to the C++ redistributable and it worked without problems
