### ISSUE TITLE
Can't able to upload excel file using node rfc

### ISSUE THREAD

**Issue by nilesh-bhoi** [SAP/node-rfc#308]
We have created an function in sap . whenever we call this function we will take excel file from file manager now i have to implement this by using node rfc library, can you help me to resolve this issue

**Comment by bsrdjan** [comment]
Hello @nilesh-bhoi,

you basically need to stream the local FILE object. The example below might help: 

Check ui component to select or drag/drop file to upload:
[ui-file.html](https://github.com/SAP/fundamental-tools/blob/main/abap-api-tools/web-application-code-explorer/client/src/resources/elements/inputs/ui-file.html)
[ui-file.js](https://github.com/SAP/fundamental-tools/blob/main/abap-api-tools/web-application-code-explorer/client/src/resources/elements/inputs/ui-file.js)

and check the this Python service "POST" method for DMS document upload. It works the same way with nodejs
[server/serve.py#L302](https://github.com/SAP/fundamental-tools/blob/main/abap-api-tools/web-application-code-explorer/server/serve.py#L302)

If more support needed, consulting services can be provided, not free of charge.
