### ISSUE TITLE
Change we change the default port 3300 to 3600 without changing connection string

### ISSUE THREAD

**Issue by vishalshingate** [SAP/node-rfc#309]
My ABAP system has RFC port 3600 open but Im not able to connect it through RFC .

**To Reproduce**
 I am not able to connect it through rfc because I'm using this connection string let client = new rfcClient({
    user: userName,
    passwd: password,
    ashost: host,
    sysnr: sysnr,
    client: clientid,
    lang: lang
  })
  I am providing the sysnr = 00 and it trying to connect the 3300 because that's how it works, but I wanted to connect without changing connection string is there any way to do that?
**Environment**

I have tried your suggestion from the https://github.com/SAP/node-rfc/issues/146 this issue.
Im not sure what I'm doing wrong , I have changed my services file from  C:\Windows\System32\drivers\etc I have added this sapdp70  3600/tcp there.

**Comment by bsrdjan** [comment]
> My ABAP system has RFC port 3360 open but Im not able to connect it through RFC .

The port selection logic is described here https://github.com/SAP/PyRFC/issues/79#issuecomment-466369061

When 3360 is open did you try sysnr=60 ?

**Comment by vishalshingate** [comment]
Hi, @bsrdjan Thanks for the quick response My bad, the port is not 3360 its a 3600.

**Comment by kimzeevaarders** [comment]
Hi @bsrdjan, I have the same problem on MacOs (ARM). I need to connect to port 3672 (sysnr=72) but for the love of god I cannot get it to work by specifying hte PORT param in the .ini file. Any suggestions on how to change the default port to 3600 instead of 3300 🙏 ?

**Comment by bsrdjan** [comment]
Hello @kimzeevaarders 

connection parameters depend on ABAP system configuration and examples of connection parameters combinations are given in `sapnwrfc.ini` file, in SAP NW RFC SDK demo folder (`$SAPNWRRC_HOME/demo/sapnwrfc.ini`).
Can you get in touch with your ABAP system administrator and clarify?

Can you connect to ABAP system using SAPLogon client? Which connection parameters are maintained there?
