### ISSUE TITLE
r3connect - lean wrapper of node-rfc

### ISSUE THREAD

**Issue by jaulz** [SAP/node-rfc#31]
Hi, though `node-rfc` makes it easy to invoke RFCs in back-ends I thought that it deserves some more functionality to make it even simpler to use. Hence, I created a new project that builds on top of `node-rfc` and you can find it here: [r3connect](https://github.com/hundeloh-consulting/r3connect) 

Its main advantages are:
- Based on ES6 Promises
- Pooling of connections to improve performance (i.e. keep existing connections open and reuse them later) and queue function calls (otherwise at some point the system will not allow to make more RFCs)
- Built-in REST API
- Built-in Docker file in order to containerize `node-rfc`
- Use it as CLI (global node module) or as a local node module within existing scripts

I am looking forward to getting feedback on the project and am happy about any contributions! :-)

**Comment by bsrdjan** [comment]
Like it ! The name could be less restrictive, it works with S/4 as well, not only R/3 👍

**Comment by jaulz** [comment]
Sure it does but I couldn't come up with any other creative name :( Any suggestion?
Do you think it would be possible to add it to the readme under REST API? Shall I create a PR?

**Comment by bsrdjan** [comment]
Added to readme
