### ISSUE TITLE
Build process failing

### ISSUE THREAD

**Issue by wilchemh** [SAP/node-rfc#32]
after following the clone and build method I am getting an error

c:\os\node-rfc>npm install

> node-rfc@0.1.11 preinstall c:\os\node-rfc
> npm install node-pre-gyp

+ node-pre-gyp@0.6.36
removed 30 packages and updated 1 package in 2.92s

> node-rfc@0.1.11 install c:\os\node-rfc
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/sap/node-rfc/releases/download/0.1.11/rfc-v0.1.11-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-rfc@0.1.11 and node@8.4.0 (node-v57 ABI) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
c:\os\node-rfc\build\rfc.vcxproj(20,3): error MSB4019: The imported project "c:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Imp
ort> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\os\node-rfc\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\os\\node-rfc\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=c:\\os\\node-rfc\\build\\rfc\\rfc.node" "--module_name=rfc" "--module_path=c:\\os\\node-rfc\\build\\rfc"
gyp ERR! cwd c:\os\node-rfc
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe c:\os\node-rfc\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=c:\os\node-rfc\build\rfc\rfc.node --module_name=rfc --module_path=c:\os\node-rfc\build\rfc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (c:\os\node-rfc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\os\\node-rfc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd c:\os\node-rfc
node-pre-gyp ERR! node -v v8.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe c:\os\node-rfc\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=c:\os\node-rfc\build\rfc\rfc.node --module_name=rfc --module_path=c:\os\node-rfc\build\rfc' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rfc@0.1.11 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rfc@0.1.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wilchemh\AppData\Roaming\npm-cache\_logs\2017-08-16T17_57_33_080Z-debug.log

**Comment by TheGreenToaster** [comment]
I had this issue. My problem was my path was not set correctly with the NWRFCSDK lib path. Described [here](http://sap.github.io/node-rfc/install.html)

**Comment by bsrdjan** [comment]
Please see if my answer in https://github.com/SAP/node-rfc/issues/35 helps?

**Comment by bsrdjan** [comment]
Closing, looks solved.
