### ISSUE TITLE
Call for Maintainers & Support

### ISSUE THREAD

**Issue by SebastianWolf-SAP** [SAP/node-rfc#329]
We regret to inform you that we can no longer maintain this project due to changing priorities. As you might have seen, the latest version of this project is built with an older RFC SDK, which is no longer supported by SAP. Therefore, the processing of issues and pull requests is on hold for now.
 
However, we would like to avoid having to archive the project in Q4/2024 and would like to hand it over to new maintainers. We are therefore looking forward to potential volunteers who would be willing to take over this project. In this case, please contact [ospo@sap.com](mailto:ospo@sap.com). We will then get in touch with you as soon as possible.
 
Thank you for your understanding,
SAP Open Source Program Office

**Comment by SebastianWolf-SAP** [comment]
Dear community,

**I regret to inform you that we will archive the project by the end of 2024** as we haven’t been able to properly transfer the ownership to new maintainers. The reasons for that are mainly resource constraints on our side as well as the fact that we currently cannot provide the necessary prerequisites for a successful restart (e.g. access to the RFC SDK under an open-source license, backend test systems etc.). 

Of course, we will keep working on these topics in the background, but there is currently no guarantee that we can resolve them. Consequently, we recommend starting a fork or a completely new project to address the use cases that have previously been covered by this project. We know that this is challenging especially with respect to the boundary conditions mentioned. However, it is probably better than keeping the question of a transfer to new maintainers open for a longer time. 

Though we move the repository to our archive, **we will keep the issues open to enable you a central point for coordination between the different stakeholders in case you need it**.  

In case of any questions or feedback, please reach out directly to us at [ospo@sap.com](mailto:ospo@sap.com). Thank you in advance for your understanding and again apologies for this step that we need to take now unfortunately.

SAP Open Source Program Office

**Comment by juanele121976** [comment]
por favor no lo dejen de mantener , que se puede hacer para ayudar

**Comment by IqbalLx** [comment]
I highly recommend @anshry
