### ISSUE TITLE
Fatal Error when invoking: RFC FM "SO_NEW_DOCUMENT_SEND_API1"

### ISSUE THREAD

**Issue by doronoded** [SAP/node-rfc#33]
I got a fatal error when trying to invoke this function (that creates a new document in SAPOffice and sends it to a list of users (receivers).

```
#
# Fatal error in ..\..\src\heap\heap.cc, line 3609
# Check failed: map->instance_type() == JS_REGEXP_TYPE || map->instance_type() == JS_OBJECT_TYPE || map->instance_type() == JS_ARRAY_TYPE || map->instance_type() == JS_SPECIAL_API_OBJECT_TYPE.
#
```

I think it has to do with the input Table (array) RECEIVERS, The first field (RECEIVER) looks kinda special in SAP GUI:
![image](https://user-images.githubusercontent.com/3406805/29808680-c77dd640-8ca1-11e7-9a6d-8c88f7dbd08b.png)

I have tried to transfer it (in javascript) as: 
`{RECEIVERS: [{RECEIVER: "SOMEUSERNAME"}]}`

And also as:
`{RECEIVERS: [{RECEIVER: {RECEIVER: "SOMEUSERNAME"}}]}`

Both caused the fatal error, and the whole node process to break.

Doron

**Comment by bsrdjan** [comment]
Hi Doron,

using the test script below I could not reproduce. The test environment is:

SAP S/4 HANA 1610, Basis: 7.51 / SP3
SAP NW RFC SDK: 7.4
nodejs: 6.11
node-rfc: current master

Could you please post the details about your environment, also try this script in your environment?

```javascript
var rfcClient = new rfc.Client(abapSystem);

console.log('rfcClient:', rfcClient.getVersion());

console.log('RFC Client is connecting...');
rfcClient.connect(function(err) {
  if (err)
    return console.error('(rfc.Client) Could not connect to server', err);
  console.log('RFC Client is connected.');

  console.log('Calling RFC function...');
    rfcClient.invoke('SO_NEW_DOCUMENT_SEND_API1', {RECEIVERS: [{RECEIVER:'TEST'}]}, (rfcErr, rfcRes) => {
      if (rfcErr)
        return console.error('Error invoking function:', rfcErr);
      console.log('Result from RFC function:', rfcRes);
    });
});
```

Kind regards,
srdjan

**Comment by bsrdjan** [comment]
Closed due to inactivity
