### ISSUE TITLE
node-pre-gyp ERR! Tried to download(404)

### ISSUE THREAD

**Issue by GeorgeMacintoshJr** [SAP/node-rfc#36]
git clone https://github.com/SAP/node-rfc.git
cd node-rfc
npm install

After the command npm install i'm getting this error 
![image](https://user-images.githubusercontent.com/30595910/31063168-4e983874-a763-11e7-9e04-572470a570ed.png)
when I tried to visit https://github.com/sap/node-rfc/releases version 57 is not available. 

Thanks for your help

**Comment by TheGreenToaster** [comment]
I had this issue. My problem was my path was not set correctly with the NWRFCSDK lib path. Described [here](http://sap.github.io/node-rfc/install.html)

**Comment by GeorgeMacintoshJr** [comment]
Hello @TheGreenToaster 
Thanks for your response. Did you set your path this way?
![image](https://user-images.githubusercontent.com/30595910/31331463-fa674c42-ad14-11e7-9f68-208378dda09f.png)

I think I was getting the error because of my nodejs version. It was v57 instead of v48 and the available downloadable files are v48.

**Comment by TheGreenToaster** [comment]
Hey @GeorgeMacintoshJr 
I set mine by appending it to the PATH variable and not as its own.
![image](https://user-images.githubusercontent.com/5624799/31686009-9fffab96-b34a-11e7-819f-703a5db90fa5.png)

**Comment by bsrdjan** [comment]
The build process shall be able to find `\lib` and `\include` subfolders of sapnwrfcsdk. The SAPNWRFC_HOME env variable in [binding.gyp](https://github.com/SAP/node-rfc/blob/master/binding.gyp#L4) shall be therefore set to sapnwrfcsdk root ("home") folder,  C:\nwrfcsdk in this case.

The Path env variable shall include `\lib` subfolder and I usually set it like `%SAPNWRFC_HOME%\lib`. This way, if the sapnwrfcsdk folder ever changed,  both the `binding.gyp` and Path are automatically fixed setting SAPNWRFC_HOME to new location.

If you find this convenient, shall I update the [installation documentation](http://sap.github.io/node-rfc/install.html) or add to README eventually?

**Comment by staskorz** [comment]
I can confirm the `SAPNWRFC_HOME` environment variable must point to the root of the `SAP NetWeaver RFC Library`, not to `lib`. Thanks @bsrdjan .

**Comment by bsrdjan** [comment]
Closing, looks solved.
