### ISSUE TITLE
Error fetching SAP document (workflow task attachment) using 'SO_DOCUMENT_READ_API1'

### ISSUE THREAD

**Issue by doronoded** [SAP/node-rfc#37]
Hi,
I was trying to read an attachment data (bmp image) that was attached to a workflow task using the function SO_DOCUMENT_READ_API1, and I couldn't recreate the image on the client side. The data received was corrupted. I have also notice some kind of 'node-rfc' error in the returning structure.
What is the correct way to retrieve an attachment from SAP?

![image](https://user-images.githubusercontent.com/3406805/31672556-92c5bff4-b365-11e7-91a9-f8ff89c96514.png)

**Comment by doronoded** [comment]
Hi, Has anyone noticed this issue?

**Comment by fujifish** [comment]
PR #39 should address this issue (use CONTENTS_HEX instead of OBJECT_CONTENT)

**Comment by bsrdjan** [comment]
Thank you @fujifish ! The issue should be fixed with 0.1.12. Could you please test?
