### ISSUE TITLE
the second value "true"

### ISSUE THREAD

**Issue by Berdmanfolk** [SAP/node-rfc#4]
var client = new rfc.Client(connParams, true);
What Is responsible the second value "true"?

**Comment by bsrdjan** [comment]
The parameter is described in detail in [Python RFC connector documentation](https://sap.github.io/PyRFC/client.html#client-connectionconfig-rstrip) and works the same way in node-rfc. 

The [default value is "true"](https://github.com/SAP/node-rfc/blob/master/src/Client.cc), thus can be omitted unless different behaviour needed. As changing this parameter default not expected in the most of use cases (other RFC connectors work the same way), I removed from the README as well.
