### ISSUE TITLE
[Question] Forwarding authentication from SCP

### ISSUE THREAD

**Issue by dellagustin** [SAP/node-rfc#44]
Hello @bsrdjan ,

I would like to know if there is any form to forward a SAP Cloud Platform authentication when consuming resources through RFC using node-rfc and the Cloud Connector.

I lack the background to judge by myself how this could be done.

Best Regards,
Guilherme.

**Comment by mtolksdorf** [comment]
Hi Guilherme,

for the time being it is not possible to use node-rfc to access On-Premise systems via Cloud Connector. In SAP Cloud Platform Neo it is a matter of configuration on cloud side and configuring trust properly in Cloud Connector and the involved On-Premise systems 

Best regards,
Markus
