### ISSUE TITLE
Getting "No_Data_Found" Error with correct parameters.

### ISSUE THREAD

**Issue by OzcanI** [SAP/node-rfc#45]
Hi,
I am trying to fetch data from st03 via fm "SWNC_COLLECTOR_GET_AGGREGATES".
I can use it in the system but when I try it in node-rfc with same parameters passed, It gives me No_Data_Found error.

![image](https://user-images.githubusercontent.com/35952982/38140053-d22870b4-343a-11e8-90fb-dfc0593c45bc.png)

I have tried to pass date so many different types, no result at all. I can use test fm and a few others fm's like TH_WPINFO etc. I am only struggling with this fm.

**Comment by bsrdjan** [comment]
Hi @OzcanI,

according to PERIODSTART Data Dictionary definition, the start period should be supplied in YYMMDDDD format:

<img width="573" alt="screen shot 2018-04-01 at 17 58 16" src="https://user-images.githubusercontent.com/1697847/38175047-a8281e16-35d6-11e8-92c7-4d7684862eef.png">

Could you please try with '20180318' ?

Please be aware that SAP Conversion Routines ("ALPHA Exits") are inactive in RFC communication (see first section: http://sap.github.io/node-rfc/remarks.html) and i/o data in SE37 transaction for example may be different from data in RFC communication.

**Comment by OzcanI** [comment]
Thank you, that worked. I dont know how I missed it. 👍

**Comment by bsrdjan** [comment]
New utility helpful in troubleshooting such cases: https://www.npmjs.com/package/rfmcall
