### ISSUE TITLE
npm install fails on Windows

### ISSUE THREAD

**Issue by seal-ss** [SAP/node-rfc#48]
I tried the 0.1.14 release on Windows with Node.js 8.9.4, but it fails with

```
Tried to download(404): https://github.com/sap/node-rfc/releases/download/0.1.14/rfc-v0.1.14-node-v57-win32-x64.tar.gz
```

Is it possible to provide the v57 files for Windows as well?

**Comment by bsrdjan** [comment]
Added.

**Comment by seal-ss** [comment]
Thanks. npm install works now!
