### ISSUE TITLE
unable to compile the node-rfc

### ISSUE THREAD

**Issue by aakashkumar667** [SAP/node-rfc#49]
Hi,
I am unable to compile  node-rfc module and i am getting the following error , please help me,

Error: The specified module could not be found.
\\?\C:\Users\Aakash Kumar\AppData\Roaming\npm\node_modules\node-rfc\build\rfc\rfc.node

**Comment by bsrdjan** [comment]
Could you please describe steps before the error, how do you try to install / compile? You can simply post the full console log.

**Comment by bsrdjan** [comment]
No idea what ex.js is. Could you please create empty package.json (`npm init`), run `npm install --save node-rfc`, enter the node console and require the rfc module, like on a screenshot below:

![screen shot 2018-04-04 at 14 54 48](https://user-images.githubusercontent.com/1697847/38308711-46b82074-3818-11e8-9cb0-b68defe6c5f3.png)

If any issues, please post the full log/screenshot, from `npm install` to `require`.

**Comment by aakashkumar667** [comment]
sure i will try and let u know.

**Comment by aakashkumar667** [comment]
Hi bro ,
i tried the same command but still not getting please help bro,

![image](https://user-images.githubusercontent.com/35538689/38310202-9a6407f8-3839-11e8-99dd-8d05802f8942.png)

**Comment by aakashkumar667** [comment]
![image](https://user-images.githubusercontent.com/35538689/38310359-f8adb732-3839-11e8-89b8-5e33a9f6a3dc.png)

**Comment by aakashkumar667** [comment]
even I am getting the same error in Linux too, seems to be the same problem

![image](https://user-images.githubusercontent.com/35538689/38311294-741e652c-383c-11e8-930c-2fbc21cc3f7d.png)

**Comment by aakashkumar667** [comment]
Hi bsrdjan,
i tried everything but still i am facing same issue

**Comment by bsrdjan** [comment]
Linux log is more expressive, showing that SAP NW RFC Library is not properly installed.

Did you check [Platform and Prerequisites](https://github.com/SAP/node-rfc) README section and [installation instructions](http://sap.github.io/node-rfc/install.html) ?

**Comment by aakashkumar667** [comment]
Hi bsrdjan,
One simple doubt can u please tell me where to download that file I tried a lot to get that file but I am unable to get it.

**Comment by bsrdjan** [comment]
Hi,
SAP NW RFC Library is only available in SAP Service Marketplace. To download it from there, customer or partner account is required. Are you connecting to customer or partner SAP system and could customer/partner download it for you?

**Comment by aakashkumar667** [comment]
Hi bsrdjan bro,
I am usinng the  same instruction which u had given in the readme if u want i will share my screen and show u. I am here bit confuse what i have to do next i am completly block.

**Comment by bsrdjan** [comment]
Closing as this is not actionable, but feel free to continue the discussion.

**Comment by bodyrock** [comment]
I had this issue and fixed it by using a pentium based computer.  shocking.  I had an amd.
