### ISSUE TITLE
Add v59 win32 to the release?

### ISSUE THREAD

**Issue by vicboyv** [SAP/node-rfc#51]
```
node-pre-gyp ERR! Tried to download(404): https://github.com/sap/node-rfc/releases/download/0.1.14/rfc-v0.1.14-node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-rfc@0.1.14 and node@9.10.1 (node-v59 ABI, unknown) (falling back to source compile with node-gyp)
```

Using **v9.10.1**

It tried compiling it from source but failed, is that normal for unsupported versions?

EDIT: Oops, should have read the description. Anyway, the fallback to build doesn't work with it.

**Comment by bsrdjan** [comment]
Added to new 0.1.15 release, please try.

**Comment by bsrdjan** [comment]
If any issues please reopen.
