### ISSUE TITLE
Clustered table

### ISSUE THREAD

**Issue by Berdmanfolk** [SAP/node-rfc#54]
Hi, @bsrdjan! 
I used node-rfc to get the data of the clustered table. Data received in Uint8Array(). Is there a way to further decode this data? 
I use FM application_data_get.

thanks,

**Comment by bsrdjan** [comment]
Hi @Berdmanfolk,

there is no way to decode these data on nodejs side. The function module can be on ABAP side wrapped into new RFC, in which the RAW data can be decoded using [ABAP IMPORT statement](https://help.sap.com/doc/abapdocu_752_index_htm/7.52/en-US/abapimport_data_cluster.htm). 

Examples can be found by searching the ABAP source and the correct syntax depends on how the data are written. Looks like a task for ABAP consultant:

![image001](https://user-images.githubusercontent.com/1697847/41725657-a8e4c744-7570-11e8-9f00-ec2baf068b87.png)
Hope this helps,
Srdjan

**Comment by bsrdjan** [comment]
Please search for MONI(TB) and if further support needed please let me know.

**Comment by Berdmanfolk** [comment]
@bsrdjan thank you very much for your explanations
