### ISSUE TITLE
MacOS - Appears to have NW RFC Library available

### ISSUE THREAD

**Issue by ajonp** [SAP/node-rfc#58]
"OS X and ARM platforms are currently not supported, as SAP NW RFC Library is not available for those platforms"

Could this be opened up to allow for MacOS development?

![image](https://user-images.githubusercontent.com/3102249/46429164-c3ea0500-c713-11e8-8ec3-ac5d0ee784cd.png)

**Comment by bsrdjan** [comment]
The experimental support is provided in @next 1.0.0-rc4 and perhaps someone could help clarify following.

In which folder should SAP NW RFC Library be installed on MacOS ? Are there best practices, with locations where such libraries should/must be installed?

After SAP NW RFC Library installed, the node-rfc should be able to find it and I am not sure about optimal solution here. 

Using DYLD* environment variables is inconvenient as [MacOS SIP removes these variables from sub-processes context](https://github.com/rbenv/rbenv/issues/962#issuecomment-275843624). That way, mocha for example, or any other node script with subprocess, is not any more able to find SAP NW RFC Library.

This library can't be bundled and shipped with node-rfc and perhaps the prerequisite could be using fixed location (which one?), the same I am using on test/dev Mac ?

Asked also [here](https://github.com/nodejs/node-addon-api/issues/378#issuecomment-433739186). Feedback/ideas from MacOS experts would be helpful.

**Comment by bsrdjan** [comment]
Clarifications are still ongoing how SAP NW RFC SDK dylibs for MacOS should be best installed on MaOC system. MacOS bindings are provided as of prerelease 6 (just published).
You may download SAP NW RFC SDK into any folder and adjust the `rpath` in `sapnwrfc.node` and SAP NW RFC SDK libs, like

```shell
install_name_tool --rpath <old-path> <new-path> <file>
```

**Comment by bsrdjan** [comment]
Please find the macOS section added to documentation. Please feel free to try and let me know if works for you.
