### ISSUE TITLE
Overflow?

### ISSUE THREAD

**Issue by joystick** [SAP/node-rfc#6]
Hello Srdjan,

When I extract BSEG-PSWBT and BSEG-DMBTR from document
![image](https://cloud.githubusercontent.com/assets/168422/9386176/fe86fd32-4762-11e5-96e1-e8e31ad9d891.png)
with `RFC_READ_TABLE` in my result I have truncated (overflown?) figures:
```
Headers: PSWBT,DMBTR
[ [ 'PSWBT', 'DMBTR' ],
  [ '4184374221.00', '4184374221.00' ],
  [ '8995269802.00', '8995269802.00' ],
  [ '1071702116.00', '1071702116.00' ],
  [ '40501469.00', '40501469.00' ],
  [ '*291847608.00', '*291847608.00' ] ]
```
Could you please advise on this?
Thank you,
Alexei

**Comment by bsrdjan** [comment]
Could you please let me know ABAP types of affected fields ?

**Comment by joystick** [comment]
It's CURR (Currency field, stored as DEC).
