### ISSUE TITLE
Invoking RFC with import parameter of table with no structure

### ISSUE THREAD

**Issue by cjbailey** [SAP/node-rfc#61]
I think this may be a limitation of RFCs rather than node-rfc but I was wondering if there is a way to invoke an RFC where I have an import parameter which is of a table type with a line type of a raw byte sequence?

For reference, the table type is SXMSMGUIDT and line type SXMSMGUID which is simply a data type of RAW (16 char length).

I try to pass the table as:

`
    const IM_MESSAGE_LIST = [
        "FAEC7430D2C711E8C95A00000203FBFE"
    ];
`

But when I invoke the RFC I get an error message returned:

`
{"name":"RfcLibError","code":20,"key":"RFC_INVALID_PARAMETER","message":"field '0' not found"}
`

I have also tried passing the table as:

`
    const IM_MESSAGE_LIST = [
        { "0": "FAEC7430D2C711E8C95A00000203FBFE" }
    ];
`

... to no avail.

**Comment by bsrdjan** [comment]
Yes, the error message here is a kind of unintuitive (refers to field index) and the correct syntax is:

 `[ { "": "FAEC7430D2C711E8C95A00000203FBFE" } ]` 

Passing and getting simple arrays in such cases, like `[ "FAEC7430D2C711E8C95A00000203FBFE" ]` for example, will be provided in next NAPI release, with 9bc30daeb27ac1b3365fe522ca5fc3e311eafe11 fix.

You can of course clone this branch, build from source and pre-test.

**Comment by cjbailey** [comment]
Ahh excellent!  Thank you so much for clarifying that bsrdjan.
