### ISSUE TITLE
Passing GUID (RAW type) import data

### ISSUE THREAD

**Issue by cjbailey** [SAP/node-rfc#62]
For the life of me I can't figure out how to pass a GUID to function module: SXMB_GET_MESSAGE_STATUS

The import parameter is a table with rows of type: SXMSMGUID which in turn is derived from a data type of RAW (length 16).

I've tried using a Uint8Array, a Buffer object, plain string, encoded string (converting a Buffer back to a string) to no avail.  
e.g.
IM_MESSAGE_LIST.push( { "": Buffer.from( req.params.id, "hex" ).toString( "utf-8" ) } );

and,

IM_MESSAGE_LIST.push( { "": new Uint8Array( [216, 211, etc....] ) } );

I'm sure this must be possible but I can't fathom how to do it.  Sorry if I'm asking this question in the wrong place as this may not be an issue with node-rfc itself, just my lack of understanding.

edit: To clarify, the invoke is actually working but it fails to return anything because it seems to be mapping the GUID incorrectly.  I can see from the response that the byte array returned is different to the one passed in.

**Comment by cjbailey** [comment]
Aw man, I can't believe it didn't cross my mind to debug it!  (I've done that in the past with .NET Connector so it really should have been in my mind)

Thanks for your help again Srdjan.  I'll try to use my brain next time!  :laughing: 

I'll try your suggestions out now and report back shortly.

**Comment by cjbailey** [comment]
It still doesn't seem right.

If I pass in...
`IM_MESSAGE_LIST.push( { "": Buffer.from( '\x40' ) } );`

This seems to get passed through correctly so in ABAP debug I see: "40000000000000000000000000000000" for the GUID.  All good!

However, if I pass in...
`IM_MESSAGE_LIST.push( { "": Buffer.from( '\xD8' ) } );`

This seems to translate to 2 chars in node-rfc...
```
0:195
1:152
```
So in ABAP debug I see...
"C3980000000000000000000000000000" as my GUID

It seems anything up to 0x7F is correct, so Buffer.from must create a signed int rather than unsigned (I'm new to Buffer so maybe this is obvious to others?).  I can work around this by using Buffer.writeUInt8 or Buffer.writeUIntBE I guess.

On that basis I'm happy to close this issue as it seems more to do with my lack of understanding of Buffer than anything else.

**Comment by cjbailey** [comment]
On second thoughts, maybe it's not me.

If I use:
`byteGuid.writeUInt8('0x7F', 0);`

Then I notice in ABAP debug I see the same value passed through.

However, if I write:
`byteGuid.writeUInt8('0x80', 0);`

or, in fact, any value above 0x80 I always get the value 0xEFBFBD showing up in ABAP debug which seems to be some character replacement if it can't determine what the character is (according to Google)?!

So now I'm unsure whether this is a bug or still me not understanding what I'm doing?

**Comment by bsrdjan** [comment]
hi @cjbailey,

thanks for the great example and there is nothing more you could do. The node-rfc was using utf8 encoding also for BYTE and XSTRING operations, adding garbage bytes to input strings/buffers.
Following this [documentation](https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings), I fresh new @next rc4 release. Please check [unit tests examples](https://github.com/SAP/node-rfc/blob/napi/test/datatypes.spec.js#L124), searching for "XBYTES". 
Not sure if binary strings could be more convenient on nodejs, instead of Buffers and need to check if possible to pass them to node-rfc (N-API removed String.Length ...) but let test and see.

**Comment by cjbailey** [comment]
Excellent!  I shall update now, give it a go and get back to you.

Thank you so much for your help Srdjan.

**Comment by cjbailey** [comment]
At least, I would test it but I'm suddenly getting the dreaded:

> gyp ERR! stack Error: unable to get local issuer certificate

when running: 
`npm install node-rfc@next`
and:
`node-pre-gyp ERR! Completion callback never invoked!`
if I try to reinstall plain "node-rfc".

Aggh!

**Comment by bsrdjan** [comment]
perhaps this helps
https://stackoverflow.com/questions/46688217/gyp-err-npm-is-unable-to-get-local-issuer-certificate

**Comment by cjbailey** [comment]
Thanks Srdjan.  Apologies for not getting back sooner, I was on a break last week.  I think my local package must have got very confused.  Deleted the node_modules folder and started again.  Appears to install fine now so I can finally get around to testing it.

**Comment by cjbailey** [comment]
Replicating my last test using:

`byteGuid = Buffer.from( '\xD8\xD3\x85\xF6\xC8\x94\x1E\xD8\xB5\xBB\xF3\xFA\x81\x3B\x1C\x46', "binary" );`

Now works perfectly!  Many thanks Srdjan!
:)
