### ISSUE TITLE
RFCTYPE_BCD (number values output as string)

### ISSUE THREAD

**Issue by mploigtweber** [SAP/node-rfc#63]
I know that BCD handling has been changed elsewhere because otherwise it could lead to rounding errors when calculating currencies. The workaround was that now all BCD numbers are output as strings.

This makes it necessary for a large number of BAPIs, which output numerical values in BCD format, to parse them back into numbers, if they want to continue calculating with them.

The question is also whether the same rounding error would not occur again if you would convert the BCD string back with parseFloat.

It would be very nice if it were possible to parameterize this behavior. There should be an option where you can specify that you have issued the BCDs as a string or as a number.

Thanks in advance

**Comment by mploigtweber** [comment]
Here is **one** example from BAPI **MD_STOCK_REQUIREMENTS_LIST_API**

![image](https://user-images.githubusercontent.com/2803448/47584313-4bfdac00-d95a-11e8-82f2-e2b903b86eb5.png)

**Comment by bsrdjan** [comment]
Would you agree we close this one and continue with re-opened #52, discussing the same?

**Comment by mploigtweber** [comment]
Yes of course. Thanks for the answer.
