### ISSUE TITLE
Async/Await version?

### ISSUE THREAD

**Issue by zig999** [SAP/node-rfc#65]
Hi there!
In the examples page, https://github.com/SAP/node-rfc/blob/napi/examples/README.md,
shows one where it's possible to use async/await methods like open and call.
Which version is that?

**Comment by zig999** [comment]
Thanks @bsrdjan .
Just a fast sugestion, ou guys shouls add a note at README.md for windows users, something like:
"Add env variable SAPNWRFC_HOME pointing to your SAP NW RFC SDK root  folder."
It breaks when trying to build.

**Comment by bsrdjan** [comment]
Thanks for the suggestion. SAPNWRFC_HOME is actually required on all platforms and I would add the link in README, to already existing [documentation](http://sap.github.io/node-rfc/install.html)

**Comment by bsrdjan** [comment]
Added to README and [documentation](http://sap.github.io/node-rfc/install.html).
