### ISSUE TITLE
Can't load module sapnwrfc.node 

### ISSUE THREAD

**Issue by haexhub** [SAP/node-rfc#66]
Hi,

I installed node-rfc@next and get the error "can't load module ...\node_modules\node-rfc\lib\binding\win32-x64-node-v64\sapnwrfc.node. The Path is correct and the file exists, but can't be loaded.
I'm using:
node: 10.13.0
npm: 6.4.1
node-rfc@next

Any advice would be appreciated

**Comment by bsrdjan** [comment]
Could you please post the full error log and check if prerequisite [SAP NWRFC SDK Library] (
http://sap.github.io/node-rfc/install.html#sap-nw-rfc-library-installation) properly installed?

**Comment by haexhub** [comment]
Hello Srdjan,

thanks for your quick response. This was much faster than the usual SAP response time! :smile: 
I thought I can use the "normal" rfc library from my SAP Netweaver, I already have installed. But it seems, you have to use the files you mentioned. After downloading, extracting and creating system variable, it's working.
So I guess you can close my issue.
Thanks again for the quick response!
