### ISSUE TITLE
Exporting Table Parameter

### ISSUE THREAD

**Issue by haexhub** [SAP/node-rfc#68]
Hi,

I played arround with node-rfc and it is working quite nice. But I have a problem with exporting tables as export parameter. The rfc fuba is working and the table there has the right values. so the abap part is working correctly. 
Errormessage:
{"name":"RfcLibError","code":12,"key":"RFC_SERIALIZATION_FAILURE","message":"Parameter T_VALUES: After a value an end tag must follow. That did not happen in \"\""}

What am I supposed to do?
Best regards
haex

**Comment by bsrdjan** [comment]
Could you please post some screenshots of  RFC FuBa signature and DDIC element of T_VALUES?

Did you try testing using SE37 transaction and post values working in SE37?

**Comment by haexhub** [comment]
Hi,
the signature is pretty simple. There is just one export parameter.
![image](https://user-images.githubusercontent.com/29780781/48714169-6271ed00-ec12-11e8-8da9-ba29ca72da20.png)

DDIC
![image](https://user-images.githubusercontent.com/29780781/48714317-c1376680-ec12-11e8-9e24-13d799f2796a.png)


se37
![image](https://user-images.githubusercontent.com/29780781/48714269-9f3de400-ec12-11e8-9a3e-b0f13b1ca74d.png)

![image](https://user-images.githubusercontent.com/29780781/48714288-abc23c80-ec12-11e8-8166-c466856155cc.png)

**Comment by haexhub** [comment]
Wired things happen. Not sure what I've changed, but it's working now. :confused: 
Sorry for any inconvenience!
