### ISSUE TITLE
Invalid parameter 'RFC_CONNECTION_HANDLE' was passed to the API call

### ISSUE THREAD

**Issue by anupong-s** [SAP/node-rfc#69]
I use node-rfc version 1.0.0-rc5. I found error (some time)

`Error invoking RFC_READ_TABLE: { name: 'RfcLibError',
code: 20,
key: 'RFC_INVALID_PARAMETER',
message: 'Invalid parameter \'RFC_CONNECTION_HANDLE\' was passed to the API call' }
`

let client = new rfc.Client(config.sap_vdp);
        client.connect((err)=> {
            if (err) {
                console.log('######## ERROR Connection (bapi) #######', err);
            }

            client.invoke(bapiName, filter, function(err, res) {
                if (err) {
                    console.error('Error invoking RFC_READ_TABLE:', err);
                    return reject(err);
                }
                let json = convertBapiToJSON(res, fields);
                return resolve(json);
            });

        });

**Comment by bsrdjan** [comment]
The error usually indicates a conflict when two or more threads access a SAP NW RFC SDK instance.

As described in [this thread](https://github.com/SAP/PyRFC/issues/46#issuecomment-310601082), you may try the Pool functionality available in pre-release and also upgrade to rc7.

**Comment by anupong-s** [comment]
This problem was fixed after I have upgrade to rc8 and use Pool connection.
