### ISSUE TITLE
Question: Which Port is used for RFC connections to SAP System?

### ISSUE THREAD

**Issue by haexhub** [SAP/node-rfc#71]
Hi,

I just have a question. I want to use the web-rfc library in a docker environment. For security reasons (company policy), I have to know the port, which the web-rfc is using to unlock them. Can you please give me this information? Is the web-rfc using one specific port for RFC connections to an SAP system or an address range?
Thanks

**Comment by bsrdjan** [comment]
Hi @haexhub,

web-rfc is is not related to node-rfc and questions about web-rfc should be discussed elsewhere.

To check the port you can ask the sys admin or open the SMICM transaction in your ABAP system:

![1](https://user-images.githubusercontent.com/1697847/52042119-a2235200-253c-11e9-9be1-e3d205c6562d.png)

![2](https://user-images.githubusercontent.com/1697847/52042134-aa7b8d00-253c-11e9-8099-2932d44c5e1c.png)

Kind regards,
Srdjan
