### ISSUE TITLE
Is there any roadmap?

### ISSUE THREAD

**Issue by mcanalesmayo** [SAP/node-rfc#75]
Is there any roadmap for this tool? Would like to know new features that we can expect in next versions, when are they planned to be released, etc...

**Comment by bsrdjan** [comment]
As of now the node-rfc development is driven by GitHub users' requirements and by requirements of SAP internal projects using the nodejs/RFC connectivity, thus fulfilling users' real needs.

Some new features are initiated by new SAP product features, like recent SAP NWRFC SDK macOS support, and some by nodejs eco-system ([Known Issues](https://github.com/SAP/node-rfc/tree/napi#known-issues)).

Would you like to see some specific features/improvements implemented ?

**Comment by mcanalesmayo** [comment]
We are specially interested in the Mac OS support, and would like to know if there's a planned release date for this. Once this is supported, we will try out this library and maybe contribute based on our experience.

**Comment by bsrdjan** [comment]
macOS is already supported in napi branch:

1. Check [prerequisites](https://github.com/SAP/node-rfc/tree/napi#macos)

2. Install SAP NWRFCSDK for macOS, following the [documentation](http://sap.github.io/node-rfc/install.html#sap-nw-rfc-sdk-installation)

After the SAP NWRFC SDK for macOS locally installed, please don't run the **set_paths.sh** script from the documentation, but [the latest version](https://github.com/SAP/node-rfc/issues/58#issuecomment-446544151) from the #58.

Please feel free to test and let me know if any issues.
