### ISSUE TITLE
SAP RFC destination port

### ISSUE THREAD

**Issue by kunhuanglexicon** [SAP/node-rfc#76]
I'm use node-rfc to connect SAP.
It looks like the rfc client use port 3300 as SAP service port, in my env, the SAP is using port 3350, can we change the default port when creating the rfc client?

var client = new rfc.Client({ 'user': 'user', 'passwd': 'password', 'ashost': '11.22.33.44', 'sysnr': 'ee', 'client': '100', 'lang': 'EN' });

User above code as example, has the field like 'port' or 'serviceport'
 
Thanks!

**Comment by bsrdjan** [comment]
Yes, just add the `sysno: '50'` to connection parameters. More details in[SAP/PyRFC/#79](https://github.com/SAP/PyRFC/issues/79#issuecomment-466369061).

**Comment by bsrdjan** [comment]
The `sysnr: '50'` in connection parameters should be enough to connect to 3350 port.

Please see [SAP/PyRFC/#79](https://github.com/SAP/PyRFC/issues/79#issuecomment-466369061).
