### ISSUE TITLE
Unable to install node-rfc in Windows 10

### ISSUE THREAD

**Issue by rahul4sap** [SAP/node-rfc#78]
Hi All,

Not sure what wrong I am doing but I am not able to install node-rfc module in my Windows 10 machine.

Below are the steps I followed:

1. Downloaded SDK 750 from SAP service marketplace and extracted the zip into C:\nwrfcsdk (as mentioned in the [link](http://sap.github.io/node-rfc/install.html#installation)

2. Set the environment variables as mentioned below.

![image](https://user-images.githubusercontent.com/7673103/54081782-72801a80-4330-11e9-86b1-de79214e50ce.png)

3. Set the environment variable for NODE_PATH

set NODE_PATH=C:\Users\guptar29\AppData\Roaming\npm\node_modules

4. cd to my coding folder where performed npm install node-rfc where it throws bunch of error - mentioned below

![image](https://user-images.githubusercontent.com/7673103/54081834-5335bd00-4331-11e9-90f1-0517ba418f9c.png)

Kindly help!

Thanks,
Rahul

**Comment by bsrdjan** [comment]
The `npm install node-rfc` tries to install the old node-rfc release, for which only critical fixes are maintained. That node-rfc release does not support newer node versions, like node 10 used on your system and when the node-rfc installation package not found on npm, the installer tries to build the node-rfc from source on your system.

As the log shows, the build fails because it requires Python 2 ([Known Issues](https://github.com/SAP/node-rfc/tree/napi#known-issues)) and on your system the Python 3 is used.

As a solution I would recommend using the current node-rfc release, available as a prerelease, with bugs fixes, improvements and new features ([README](https://github.com/SAP/node-rfc/tree/napi)):

```shell
npm install node-rfc@next
```

The build is provided for node 10 and the installer should not complain about the Python 3.

**Comment by rahul4sap** [comment]
Thanks for your reply. I installed now node-rfc@next but now I am getting different error when trying to call this module in Node - below screenshot. 

`Error: The specified module could not be found.
\\?\node_modules\node-rfc\lib\binding\win32-x64-node-v64\sapnwrfc.node`

![image](https://user-images.githubusercontent.com/7673103/54173310-679bc600-44a7-11e9-925d-15f11303a844.png)

Appreciate your help in advance.

**Thanks,**
Rahul

**Comment by bsrdjan** [comment]
Could you please create the new project from scratch (run `npm init` in new folder and confirm all defaults) and post the full log of:

```shell
node -v
npm install node-rfc@next
node -e "console.log(require('node-rfc'))"
```

Here how it looks on one Windows test system:

```shell
λ node -v
v10.15.0

λ npm i node-rfc@next

> node-rfc@1.0.0-rc7 preinstall C:\src\test-node-rfc\node_modules\node-rfc
> npm install node-pre-gyp node-addon-api

npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-addon-api@1.6.2
+ node-pre-gyp@0.12.0
added 1 package from 32 contributors, updated 4 packages and audited 96 packages in 2.876s
found 0 vulnerabilities


> node-rfc@1.0.0-rc7 install C:\src\test-node-rfc\node_modules\node-rfc
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
[node-rfc] Success: "C:\src\test-node-rfc\node_modules\node-rfc\lib\binding\win32-x64-node-v64\sapnwrfc.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test-node-rfc@1.0.0 No description
npm WARN test-node-rfc@1.0.0 No repository field.

+ node-rfc@1.0.0-rc7
added 75 packages from 61 contributors and audited 104 packages in 9.66s
found 0 vulnerabilities


C:\src\test-node-rfc  (test-node-rfc@1.0.0)
λ node -e "console.log(require('node-rfc'))"
{ Client: [Function: Client], Pool: [Function: Pool] }
```

**Comment by bsrdjan** [comment]
The error message is telling that following file is for some reason missing on your system:

`node-rfc-demo-test\node_modules\node-rfc\lib\binding\win32-x64-node-v64\sapnwrfc.node` 

Looking into node-rfc [rc7 release package](https://github.com/SAP/node-rfc/releases), the file is included and should be installed by `npm install node-rfc@next`.

I don't have a Windows 10 system atm. to test, but let could you please try following.

Check the folder structure of `node-rfc-demo-test\node_modules\node-rfc\lib\binding`. It should look like below and sapnwrfc.node should be in the `win32-x64-node-v64` folder:
<img width="172" alt="Screenshot 2019-03-12 at 20 30 07" src="https://user-images.githubusercontent.com/1697847/54229956-aeb8a400-4505-11e9-8c04-b1b696191c8a.png">

If the folder or the file missing, could you please post the screenshot or the tree listing, like:

<img width="249" alt="Screenshot 2019-03-12 at 20 09 13" src="https://user-images.githubusercontent.com/1697847/54228678-f25dde80-4502-11e9-8547-99e7ab3023a7.png">

I can check on Windows 10 if there is possibly an installation bug. As a quick workaround, you can download the [rfc-win32-x64-node-v64.tar.gz](https://github.com/SAP/node-rfc/releases/download/1.0.0-rc7/rfc-win32-x64-node-v64.tar.gz) into `node-rfc-demo-test\node_modules\node-rfc\lib\binding` folder and unpack, to create the missing file.

I will try to reproduce on Windows 10.

**Comment by rahul4sap** [comment]
Surprisingly, this file `sapnwrfc.node` is already there in the folder `\node_modules\node-rfc\lib\binding\win32-x64-node-v64\` but still it throws that error.

```
C:\Users\guptar29\Documents\Code\node-rfc-demo-test\node_modules\node-rfc\lib\wrapper\sapnwrfc-client.js:26
    throw ex;
    ^

Error: The specified module could not be found.
\\?\C:\Users\guptar29\Documents\Code\node-rfc-demo-test\node_modules\node-rfc\lib\binding\win32-x64-node-v64\sapnwrfc.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\guptar29\Documents\Code\node-rfc-demo-test\node_modules\node-rfc\lib\wrapper\sapnwrfc-client.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\guptar29\Documents\Code\node-rfc-demo-test\node_modules\node-rfc\lib\index.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)

```
I tried the workaround but still no luck - Getting same error even after unpacking the `.tar` file.

Below are the screenshots which you asked.

![image](https://user-images.githubusercontent.com/7673103/54298435-c0ba4580-45de-11e9-94ee-db7dd150be66.png)

![image](https://user-images.githubusercontent.com/7673103/54298623-1abb0b00-45df-11e9-9925-f52326a90272.png)

**Comment by bsrdjan** [comment]
I reproduced the error by moving SAP NW RFC SDK library out of the PATH. The error message is complaining about that "module", not the node module, will add the case in documentation.

Could you please check the SAP NW RFC SDK library installation, in a following way:

1. The PATH points to SAP NW RFC SDK root folder. This looks correct on your first screenshot.

2. Check if files are indeed there, should look something like:

<img width="251" alt="Screenshot 2019-03-14 at 19 50 56" src="https://user-images.githubusercontent.com/1697847/54383656-d9843300-4692-11e9-96d1-948c3160e012.png">

3. If files are there, please check if SAP NW RFC SDK properly installed by running the `rfcexec` in bin folder. The output should be error message like below, complaining about parameters. If the popup or message comes up about not finding the DLL, something is wrong with the library installation. 

```shell
$ cd %SAPNWRFC_HOME%/bin
$ rfcexec
Error: Not all mandatory parameters specified
        Please start the program in the following way:
        rfcexec -t -a <program ID> -g <gateway host> -x <gateway service>
                -f <file with list of allowed commands> -s <allowed Sys ID>
The options "-t" (trace), "-f" and "-s" are optional.
```
If the output is different, could you please check if the correct SAP NW RFC SDK is downloaded for your platform? Could it be that your platform is 64 bit and 32 bit SAP NW RFC SDK downloaded? OR the 32 bit nodejs used, set by node version manager perhaps? You could also send me the link or screenshot of the location from which the SAP NW RFC SDK is downloaded.

**Comment by rahul4sap** [comment]
You were right!! My SDK version was not correct (had this nwrfc750P_3-70002726) hence this error. I downloaded the correct one now (nwrfc750P_3-70002755) from Service Marketplace and it worked well.

I have few other question as how can we use this on cloud foundry for which I will raise a new thread.

**Thanks again mate**

**Comment by cocolucio** [comment]
Hi! Im facing the same issue here and I tried with the version "nwrfc750P_3-70002755" which is not working for me. I wonder which version is for 64 or 32 bit.

**Comment by cocolucio** [comment]
I also tried with version "nwrfc750P_5-70002726.zip"

BTW I have Windows 10 64 bits

**Comment by bsrdjan** [comment]
Following node-rfc README [Prerequisites for all platforms](https://github.com/SAP/node-rfc#all-platforms) it should be straightforward (relatively :)):

More information on SAP NW RFC SDK section on SAP Support Portal:
https://support.sap.com/en/product/connectors/nwrfcsdk.html:
<img width="730" alt="Screenshot 2019-10-09 at 13 09 24" src="https://user-images.githubusercontent.com/1697847/66476559-32377500-ea96-11e9-9bc7-ff62e1099ced.png">

[SAP Note 2573790](https://launchpad.support.sap.com/#/notes/2573790)
<img width="727" alt="Screenshot 2019-10-09 at 13 11 29" src="https://user-images.githubusercontent.com/1697847/66476604-56935180-ea96-11e9-8280-2a212c064266.png">
 
[Service Marketplace](https://launchpad.support.sap.com/#/softwarecenter/template/products/_APP=00200682500000001943&_EVENT=DISPHIER&HEADER=Y&FUNCTIONBAR=N&EVENT=TREE&NE=NAVIGATE&ENR=01200314690100002214&V=MAINT)
<img width="1082" alt="Screenshot 2019-10-09 at 13 12 31" src="https://user-images.githubusercontent.com/1697847/66476715-95c1a280-ea96-11e9-9aed-7b275b66248e.png">
