### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by EmryRosario** [SAP/node-rfc#80]
node-rfc dependency not work for me, please help.

`Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by node_modules/node-rfc/build/rfc/rfc.node)`

**Comment by bsrdjan** [comment]
Are you using the docker container (which one?) and could you please describe steps leading to this error?

Did you try adding the missing library, like described [here](https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error) ?

**Comment by bsrdjan** [comment]
Thank you, will try to reproduce.

Could you please let me know your nodejs version and if you installed the node-rfc@next by `npm install node-rfc@next`, or built from source?

**Comment by EmryRosario** [comment]
My node version is 9.11.1, I installed node-rfc from the source (I have version 0.1.16 of node-rfc)

**Comment by bsrdjan** [comment]
Could you please try the prerelease, with many new features and bugs' fixes:

`npm install node-rfc@next`

The 0.1.16 is not maintained anymore, only critical bugs.

**Comment by bsrdjan** [comment]
Sorry, I overlooked you are using the nodejs release 9. Is it the standard one on Ubuntu 10.04 ?

This release is actually not supported and pre-compiled binaries are provided only for [nodejs LTS releases](https://github.com/nodejs/Release).

I would suggest using any LTS release (6, 8, 10 or 11), otherwise the package must be built from source on your system. You may try nodejs version managers, like [nvm](https://github.com/creationix/nvm) for example.

**Comment by EmryRosario** [comment]
> Sorry, I overlooked you are using the nodejs release 9. Is it the standard one on Ubuntu 10.04 ?
> 
> This release is actually not supported and pre-compiled binaries are provided only for [nodejs LTS releases](https://github.com/nodejs/Release).
> 
> I would suggest using any LTS release (6, 8, 10 or 11), otherwise the package must be built from source on your system. You may try nodejs version managers, like [nvm](https://github.com/creationix/nvm) for example.
> 
> If you go for older nodejs release, please upgrade the npm to the latest npm release (npm install npm), which is the only one supported. The default npm release for nodejs release you may check [here](https://nodejs.org/en/download/releases/).

Thanks, this worked for me 🙂.
