### ISSUE TITLE
Is the data encrypted in RFC communication

### ISSUE THREAD

**Issue by kunhuanglexicon** [SAP/node-rfc#81]
Hi,

I have one question regarding data encryption.

According the example code: 

`const rfcClient = require('node-rfc').Client;

// ABAP system RFC connection parameters
const abapSystem = {
	user: 'demo',
	passwd: 'welcome',
	ashost: '10.68.104.164',
	sysnr: '00',
	client: '620',
	lang: 'EN',
};
`
There are **user, passwd, ashost** in the source code, when the client make the connection to server, are those sensitive data be encrypted. And also for the response from server, are the data be encrypted? As those data my contain business sensitive data as well.

Thanks!

**Comment by bsrdjan** [comment]
This particular example illustrates the plain connection, without data encryption. 

For secured/encrypted communication, additional configuration is required, both on nodejs system and on ABAP system, including setting-up a trust between these two systems. 

This configuration is standard in production systems, usually implemented by SAP NetWeaver Network/Security consultants. When configured, [different connection parameters](http://sap.github.io/node-rfc/authentication.html) can be used.

For more info on SAP Secure Network Communication (SNC) and SNC configuration please check links in [SAP/PyRFC#87](https://github.com/SAP/PyRFC/issues/87#issuecomment-440267463).
