### ISSUE TITLE
node-pre-gyp preinstall ENOENT error

### ISSUE THREAD

**Issue by bsrdjan** [SAP/node-rfc#86]
The `npm install node-rfc@next` ends with ENOENT error and works with `--no-bin-links` switch only:

```shell
npm install node-rfc@next --no-bin-links
```
It looks like node-pre-gyp or the npm issue, the investigation starts from node-pre-gyp: [node-pre-gyp/#446](https://github.com/mapbox/node-pre-gyp/issues/463).

**Comment by razims** [comment]
Please just go with `"node-pre-gyp": "0.12.0"` looks like release 0.13.0 was untagged. Version 0.12.0 works pretty well.

**Comment by bsrdjan** [comment]
Fixed with rc10
