### ISSUE TITLE
Building node-rfc on win10 in closed network fails

### ISSUE THREAD

**Issue by DanielMilo** [SAP/node-rfc#87]
Hello,
I need assistance with installing node-rfc in a closed environment:

I've downloaded the required npm library and set that up in my network. 
I've installed sapnwrfcsdk.
I've installed python and vs.
I'm installing like this:
`npm i node-rfc@1.0.0-rc8 -g --build-from-source`
And I'm facing an error:
in the post install phase it runs `node-pre-gyp install --fallback-to-build`
after that it tries to download using needle: "using needle for node-pre-gyp https download" but fails (closed network) so it falls back to source compile with node-gyp.
it fails to resolve github.com which should be fine
and then I'm getting the error:
`install got an error, rolling back install`
`configure error`
`Error: connect ECONNREFUSED <IP>`
the system is Windows_NT 10.0.17134

_(sorry for not copying the whole text, the machine I was trying to install it on cannot reach normal internet, so I copied what I could)_

Do you have any suggestions?

**Comment by bsrdjan** [comment]
The build from source using `npm i node-rfc@next --build-from-source` fails without network access because it starts with searching the npmjs.com repository first. After finding the node-rfc package there, the network is required again, to fetch the source code and build dependencies from GitHub and npmjs.

To make the build from source without internet access possible, both must be provided upfront:

```shell

# ((( internet access )))

# clone the source code from GitHub
$ git clone --single-branch --branch napi https://github.com/sap/node-rfc.git

# install build dependencies from npmjs
$ cd node-rfc
$ npm run install:dev

# ((( no internet access )))

# build the node-rfc binary from source
$ node-pre-gyp clean configure build
# # build the node-rfc JavaScript wrapper from TypeScript source (optional)
# $ tsc -p src/ts

# test
node -e "console.log(require('./lib'))"
{ Client: [Function: Client], Pool: [Function: Pool] }
```
