### ISSUE TITLE
Error installing SAP NW RFC SDK

### ISSUE THREAD

**Issue by davidacb** [SAP/node-rfc#89]
Hello, 

I am having issues installing the SPA NW RFC SDK. this is the following error when i try to run the rrfcexec.
![image](https://user-images.githubusercontent.com/49650425/59497943-57bbc580-8e8c-11e9-8b64-5d2776f9129e.png)

And this is the error when i run the command node -e "console.log(require('node-rfc'))".
![image](https://user-images.githubusercontent.com/49650425/59498481-7078ab00-8e8d-11e9-95d9-c68e1e3846cf.png)

Could you help me?

Kind regards,

**Comment by bsrdjan** [comment]
It looks like `C:\Users\david.barreiro\lib` is not on PATH ?

[SAP NW RFC SDK Installation - Windows](http://sap.github.io/node-rfc/install.html#windows)

**Comment by davidacb** [comment]
Hi, thank you for the quick answer. 

It is on the PATH. I already resolved the issue. Somehow the .net Framework was missing on my PC. installed it and it is already working!

Kind regards,
