### ISSUE TITLE
How to write an RFC server program with this JavaScript API

### ISSUE THREAD

**Issue by vbansal22** [SAP/node-rfc#9]
This looks like a very good API. I am interested in finding out how I can use this API to write event driven RFC server programs.

Thanks,

--vikram

**Comment by bsrdjan** [comment]
Hi Vikram,
you can refer to [PyRFC](https://github.com/SAP/PyRFC) connector and the [Server Scenario](http://sap.github.io/PyRFC/server.html), the approach is the same.
Kind regards,
srdjan
