### ISSUE TITLE
Issues installing node rfc on Linux

### ISSUE THREAD

**Issue by davidacb** [SAP/node-rfc#90]
Hello, i am facing issues installing node rfc on linux. 
Is there pre built binaries for this nodejs version? 
Here a the screenshots:
![image](https://user-images.githubusercontent.com/49650425/59669618-7682ca80-91b2-11e9-8bec-637621225c20.png)
![image](https://user-images.githubusercontent.com/49650425/59669652-85697d00-91b2-11e9-9214-1c68568219e3.png)

Thanks, 
David Barreiro

**Comment by bsrdjan** [comment]
Hi David,

no pre-built for node 9, only for [LTS releases](https://github.com/SAP/node-rfc/tree/napi#supported-platforms).

Is it a docker container and which one? Would using a newer nodejs release be an option? 

Regards,
Srdjan

**Comment by davidacb** [comment]
Hi, 
We upgrade to a newer version and it is already working, thanks! 

Kind regards, 
David Barreiro
