### ISSUE TITLE
Retrieve export parameter on RFC FM 

### ISSUE THREAD

**Issue by davidacb** [SAP/node-rfc#91]
Hello, 

Is there a way when executing an RFC FM through node-rfc to retrieve back the export parameter of the RFC FM? 

Kind regards, 
David Barreiro

**Comment by bsrdjan** [comment]
They should be normally returned, unless the "filter" option set to 1, filtering them out:

```node
const rfcClient = require('node-rfc').Client;

const client = new rfcClient(abapSystem, {
    filter: 1
});
```
