### ISSUE TITLE
Problem to invoke rfc function

### ISSUE THREAD

**Issue by strife-cloud** [SAP/node-rfc#92]
Hello, I'm trying to invoke some rfc function but I don't have documentation on this part and I don't know which parameters should I pass to invoke properly the function, here some screen on the function someone did from my work:

![image](https://user-images.githubusercontent.com/7645102/60813863-dc9cb500-a194-11e9-932b-1cbdfd89ce99.png)
![image](https://user-images.githubusercontent.com/7645102/60813874-e1616900-a194-11e9-9f6a-8187da3a347c.png)
![image](https://user-images.githubusercontent.com/7645102/60813883-e45c5980-a194-11e9-934f-9750d9bef9a4.png)
![image](https://user-images.githubusercontent.com/7645102/60813891-e7efe080-a194-11e9-9013-0f021cdc013b.png)

And here what I tried, I suppose it's completely wrong (at least I succed at connected) but I have literally no clues on what to pass
![image](https://user-images.githubusercontent.com/7645102/60814146-651b5580-a195-11e9-8bfb-e90772365c0a.png)

Is there some documentations about rfc call?

Thank you,
Danh

**Comment by bsrdjan** [comment]
Hi Danh, 
the code looks correct, are you getting any error or the res is just empty? Regarding the documentation, the function module whose name starts with "Z" is not SAP standard function module. You may click the "Function Module Documentation" button, shown on the right-hand side of the top toolbar (the first screenshot), and see if any documentation provided by function module author.

**Comment by strife-cloud** [comment]
Sorry it does work, I just remove client.close() and it works like a charm but is there more documentation about which parameter you can pass because I have litteraly have no clues about import structure, export structure for example. Here in your example I don't know what it's IMPORTSTRUCT, RFCTABLE

![image](https://user-images.githubusercontent.com/7645102/60872293-b75f8380-a234-11e9-987a-f9a70a4e9e84.png)

**Comment by bsrdjan** [comment]
No every remote enabled function module is SAP standard API and therefore not each one is documented. Better documented should function modules starting with "BAPI" prefix, implementing SAP Business Applications Programming Interface. You may check BAPI_USER_GET_DETAIL for example.

**Comment by strife-cloud** [comment]
Thank you for your guidance then!
