### ISSUE TITLE
long RAW data not pass to RFC correctly 

### ISSUE THREAD

**Issue by Sgwser** [SAP/node-rfc#93]
When pass a string into the RFC RAW, it only take the first 8 chars, others are converted to 0. I did a debug on tcode SE37 and found the RFC below in CONTENT_LINE only get the first 8 chars.
 
iJson = {"I_PARTNER": {…},"I_GUID": {…},"T_NOTES": [],"T_DISPUTES": […],
    "T_FILECONTENT": [
        {
            "ID": "001",
            "FILE_ID": "001",
            "CONTENT_LINE": "THIS IS A TEST",
            "COMP_ID": "file.txt",
            "MIMETYPE": "text/plain",
            "COMP_SIZE": 14
        }
    ]
} 
 
sapclient.invoke(‘APAR_EBPP_CHANGE_DISPUTE’, iJson, function(err1, res) { …
 
RFC return:
 
"T_FILECONTENT":[{"ID":"001","FILE_ID":"001","CONTENT_LINE":{"type":"Buffer","data":[84,72,73,83,32,105,115,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}

**Comment by bsrdjan** [comment]
The `CONTENT_LINE": Buffer.from("THIS IS A TEST")` should work as expected and when passing a string instead of Buffer, the exception should be raised:

```shell
{ major: 7500, minor: 0, patchLevel: 3, binding: '1.0.0-rc11' }
Error: [TypeError: Buffer expected when filling field 'CONTENT_LINE' of type 4]
```
I tested using the latest node-rfc release (the @next pre-release, `npm install node-rfc@next`) and got the above error in my test system. Is your node-rfc release eventually older?

Here my test:

**script**

```node
let tables = {
    "T_FILECONTENT": [{
        "ID": "001",
        "FILE_ID": "001",
        "CONTENT_LINE": Buffer.from("THIS IS A TEST"),
        "COMP_ID": "file.txt",
        "MIMETYPE": "text/plain",
        "COMP_SIZE": 14
    }]
};

console.log(client.version);

client.open().then(() => {
    client.call("APAR_EBPP_CHANGE_DISPUTE", tables)
        .then(result => {
            console.log(tables.T_FILECONTENT);
            console.log(result.T_FILECONTENT);
        })
        .catch(e => {
            console.error("Error:", e);
        })
        .finally(() => {
            client.close();
        });
});
```

**output**

```shell
~/s/N/node-rfc ❯❯❯ node ci/issue.js                                                                     (py2715) napi
{ major: 7500, minor: 0, patchLevel: 3, binding: '1.0.0-rc11' }
[ { ID: '001',
    FILE_ID: '001',
    CONTENT_LINE: <Buffer 54 48 49 53 20 49 53 20 41 20 54 45 53 54>,
    COMP_ID: 'file.txt',
    MIMETYPE: 'text/plain',
    COMP_SIZE: 14 } ]
[ { ID: '001',
    FILE_ID: '001',
    CONTENT_LINE:
     <Buffer 54 48 49 53 20 49 53 20 41 20 54 45 53 54 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... >,
    COMP_ID: 'file.txt',
    MIMETYPE: 'text/plain',
    COMP_SIZE: 14 } ]
~/s/N/node-rfc ❯❯❯      
```

**Comment by Sgwser** [comment]
Hi Srdjan, after install node-rfc (npm install --build-from-source node-rfc@next) and change to use "CONTENT_LINE": Buffer.from("THIS IS A TEST"), the RFC APAR_EBPP_CHANGE_DISPUTE works very well. Unfortunately when I do a reverse calling to download the file by rfc

sapclient.invoke('APAR_EBPP_DISPUTE_FILE_GET', requestJson, function(err, data){

get return data.BIN_CONTENT = [{"LINE":{"type":"Buffer","data":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}}]

**Comment by bsrdjan** [comment]
Could you please logon to ABAP backend system, start the SE37 transaction and test call the APAR_EBPP_DISPUTE_FILE_GET function module, with the same parameters used in nodejs script?

If the result is the same, check again the input parameters and the documentation. If the result is different, than we can check the node-rfc.

**Comment by Sgwser** [comment]
Actually I did. Here is what I got in the debug of SE37 before reaching to node-rfc. BIN_CONTENT:
5468697320697320612066696C652075706C6F6164207465737420000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

The output of in node-rfc:
{"COMP_ID":"file.txt", … ,"OBJECTID":"C2CEC8448F751ED9ABC111DBFA64CA7D",
"BIN_CONTENT":[{"LINE":{"type":"Buffer","data":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}}],"T_MESSAGES":[]}

**Comment by bsrdjan** [comment]
Could you please set the standard breakpoint at first line of APAR_EBPP_DISPUTE_FILE_GET and start the test in SE37, so that ABAP debugger comes up and you can see input parameters.

At the same or next line, you may set the [external breakpoint](https://wiki.scn.sap.com/wiki/display/Duetent/Set+External+Breakpoints+for+ABAP+Debugging), for the user the node-rfc is using. After starting the nodejs script, the node-rfc calls the APAR_EBPP_DISPUTE_FILE_GET and ABAP debugger shows up. That way can be verified if APAR_EBPP_DISPUTE_FILE_GET called with exactly the same input parameters, as SE37 test case.

You could make screenshots of these input parameters in both cases (SE37 and nodejs), to check if any difference when calling from nodejs/node-rfc:

![Screenshot 2019-07-24 at 14 14 16](https://user-images.githubusercontent.com/1697847/61792643-83cc4e00-ae1d-11e9-8bf1-0a5850fa9d67.png)

![Screenshot 2019-07-24 at 14 14 25](https://user-images.githubusercontent.com/1697847/61792650-87f86b80-ae1d-11e9-9915-9b5bf40a7958.png)

**Comment by Sgwser** [comment]
See below, the highlight objectID is used to identify we made a call to the same object to retrieve the file:

[cid:image001.png@01D541FC.2030F0E0]

[cid:image002.png@01D541FC.9584F3A0]

[cid:image003.png@01D541FC.9584F3A0]

**Comment by bsrdjan** [comment]
Could you please edit your reply direct in GitHub because disclaimers and additional content are getting copied each your reply (see above) ?

**Comment by bsrdjan** [comment]
Could you please edit your reply direct in GitHub ? Images are not visible and disclaimers and additional contend (incl. Email addresses) are getting appended to your posts.

**Comment by Sgwser** [comment]
![image](https://user-images.githubusercontent.com/53098239/61795879-5ddd8400-adf2-11e9-8f4b-751ef2bc7687.png)

**Comment by Sgwser** [comment]
Hi Srdjan, I post the image to the GitHub, see it there.

**Comment by bsrdjan** [comment]
Thanks. Is this a screenshot from SE37 or from nodejs test? Could you please post also the other one (from the nodejs test?) and check if input parameters look the same?

**Comment by Sgwser** [comment]
Sorry Srdjan, I cannot reveal all details. The bottom black background screen shot is from the output of calling node-rfc function APAR_EBPP_DISPUTE_FILE_GET, the up portions are shot from se37. I am the only person on the system at the time, it is the call from node-rfc.

----------------------------------------------------------------------



Confidentiality Notice:  This e-mail message, including any attachments, is for the sole use of the intended recipient(s) to which it is addressed and may contain information that is confidential, privileged or exempt from disclosure under applicable law.  Any unauthorized review, use, disclosure, printing, storing, copying or distribution is prohibited.  If you are not the intended recipient, or if you have received this email in error, please contact the sender by reply e-mail and delete all copies of the original message.  Unless specifically stated otherwise, nothing in this email is intended to serve as an electronic or digital signature.

**Comment by bsrdjan** [comment]
I could not replicate locally and would like to check in your system. Could you please create one SAP customer incident, for the component BC-MID-RFC-SDK and mention it should be processed by me (Srdjan Boskovic) ? Than I can have a look direct in your system.

**Comment by Sgwser** [comment]
A SAP incident has been opened: 002075129500004255202019. Thank you for help.

**Comment by bsrdjan** [comment]
Updated the incident with test system connection request.
