### ISSUE TITLE
Not so easy to use in VSCode or Electron

### ISSUE THREAD

**Issue by Mabenan** [SAP/node-rfc#94]
Hi,

after a day of screaming i finally found the reason why this module doesn't run out of the box with VSCode. The Reason here is that it has to be build with node_module_version 69 or higher. That maybe sounds easy but the problem here is that there is no Node Version with this ABI Version the reason for this can be found here https://github.com/nodejs/TSC/issues/651.

So the easy solution seams to be to compile against ABI Version 72 which is Node Version 12.6.0. This works fine but if you try it the following way

npm install node-rfc@v1.0.0-rc10 --build-from-source

It generates the binding folders with the ABI version. Which results in the folder
win32-x64-node-v72

This folder won't be found at runtime because the module loader searches for the folder
win32-x64-node-v72

A solution for this could be to still generate the folders with version but also generate a folder that doesn't have a version and can be use as fallback in sapnwrfc-client.ts

**Comment by bsrdjan** [comment]
Could you please explain what is exactly not running out of the box, because VSCode users (including me) did not reported the issue so far? Also the folder name `win32-x64-node-v72` is identical in comment below:

> It generates the binding folders with the ABI version. Which results in the folder
> win32-x64-node-v72
> 
> This folder won't be found at runtime because the module loader searches for the folder
> win32-x64-node-v72

The node-rfc is built for [LTS releases](https://nodejs.org/en/about/releases/) and their corresponding [ABI versions](https://nodejs.org/en/download/releases/) and the latest node-rfc release includes the [v72 binaries](win32-x64-node-v72) as well. What is exactly missing?

**Comment by Mabenan** [comment]
Sorry, it should have been that way.

It generates the binding folders with the ABI version. Which results in the folder
win32-x64-node-v72

This folder won't be found at runtime because the module loader searches for the folder
win32-x64-node-v69

The concrete error is when i want to use the node-rfc lib in an vscode extension. This is because VSCode uses his own node processor.

**Comment by bsrdjan** [comment]
I would not merge the workaround into node-rfc, for fixing (hopefully temporary) gap in Electron vs-code extension. Thank you very much for the pull request helping other Electron extension users fix the issue.
